initial commit of Smith2018ContactMesh and Smith2018ArticularContactForce
opensim-org/opensim-core pull request #2658
Opened 2019-12-29 14:02 UTC by clnsmith

### Brief summary of changes
This PR introduces a new ContactGeometry and Force component to represent articular contact using triangulated surfaces meshes based on the method introduced in this paper:

Smith, C. R., Won Choi, K., Negrut, D., & Thelen, D. G. (2018). Efficient computation of cartilage contact pressures within dynamic simulations of movement. Computer Methods in Biomechanics and Biomedical Engineering: Imaging & Visualization, 6(5), 491-498.

https://www.tandfonline.com/doi/abs/10.1080/21681163.2016.1172346

### Testing I've completed
Testing is a work in progress. Currently I added a test to testForces that builds a model using these components and performs a simple forward simulation. I will add more testing soon to make sure results are correct. 

I tried to add to testComponents, but without a mesh file (.stl etc) the Smith2018ContactMesh fails.

### Looking for feedback on...
Overall layout of components etc. This is a pretty good sized chunk of code, so it may take a while to review. 

### CHANGELOG.md (choose one)
- updated to introduce new components

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

2019-12-29 15:50 UTC, chrisdembia commented
AppVeyor (Windows testing) generates warnings like the following:

```
C:\projects\opensim-core\OpenSim\Simulation\Model\Smith2018ArticularContactForce.cpp(349): warning C4244: 'argument': conversion from 'SimTK::Real' to 'int', possible loss of data
```

Could you fix these issues? Once the tests pass, we should create a separate PR to merge these components into the `camsknee` branch without review.

In parallel, we can review these changes for being merged into the master branch.

2019-12-29 15:51 UTC, chrisdembia commented
The Travis-CI build fails due to the use of tabs instead of spaces.

2019-12-29 18:47 UTC, clnsmith commented
I just pushed a commit that should address both of these issues.

Apparently visual studio edit->advanced->untabify selected lines doesn't actually remove all tabs.

2019-12-30 01:55 UTC, chrisdembia commented
I quickly skimmed this PR. I think it will take a while to review.

2019-12-30 13:55 UTC, clnsmith commented
> I quickly skimmed this PR. I think it will take a while to review.

Yeah agreed. Feel free to just make some high level comments to begin with. I will keep cleaning up the code as I address these. 

The only thing that I think is important to try to finalize before the workshop would be the user interface (ie properties and component types) so the representation in the .osim model file is stable.

2020-01-02 14:45 UTC, chrisdembia requested changes
I have some initial disorganized comments.

I have not finished thinking about the user interface.

I made a PR into your fork: https://github.com/clnsmith/opensim-core/pull/3

> Reviewed 4 of 12 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-:-LxahjSQ9vlaVgeD2sN6:b2rsubl)* status: 5 of 12 files reviewed, 36 unresolved discussions (waiting on @clnsmith)

___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 40 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LxYUWYW7wtrtMkX5YZY:-LxYUWYX-sGHS7CrmUzQ:b-4efwv0) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L40)):*
> ```objc
>  interpenetrate and the local overlap depth (proximity) is calculated for 
>  each triangle. The contact pressure on each triangle face is then calculated 
>  based on the overlap depth (see below).
> ```

Do you think it would make sense to bring over some figures from the paper (if the copyright permits it)?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 40 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LxacBeA9wQF7BJq6SsO:-LxacBeA9wQF7BJq6SsP:b-3lavhy) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L40)):*
> ```objc
>  interpenetrate and the local overlap depth (proximity) is calculated for 
>  each triangle. The contact pressure on each triangle face is then calculated 
>  based on the overlap depth (see below).
> ```

I love how detailed this documentation is.

Most users will want to know "should I use this contact model or a different contact model?" and "how do I use this contact model?". I think the documentation could be organized a bit more to answer these two questions before delving into the implementation.

One question I have is what makes this contact model specific to articulations versus foot-ground contact? Might be good to define "articular", too. Can this model be used only for articulations?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 49 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LxYUqvk8ylmbGjK5Do_:-LxYUqvk8ylmbGjK5Doa:b-rby0ef) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L49)):*
> ```objc
>  method to efficiently detect contact between triangular meshes using object 
>  Oriented Bounding Boxes (OBB, a common approach in computer graphics) and 
>  several additional speed ups that take advantage of the constrained nature of 
> ```

What are the constraints? Does this mean the surfaces *must* intersect?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 68 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LxYjtzW73cAm-_x0h-W:-LxYjtzW73cAm-_x0h-X:b-os4qt5) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L68)):*
> ```objc
>  generally small. Thus, after reposing the meshes, (i.e. realizePosition) each 
>  triangle in the casting mesh is tested against the contacting target triangle 
>  from the previous pose. Additional speed up is gained by casting the normal 
> ```

Is the case of "no previous pose" handled gracefully?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 128 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LxaYy-PBbs3WBh0bbAf:-LxaYy-Q8Ae9kXOLw0bc:b-cf7y8j) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L128)):*
> ```objc
>  to accomodate variable properties. The use_lumped_contact_model property 
>  controls whether the constant property or variable property formulation is 
>  used.
> ```

This paragraph is a bit hard for me to follow.
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 137 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LxaY4JE1j4rOQzc8moe:-LxaY4JE1j4rOQzc8mof:bahzbcr) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L137)):*
> ```objc
>  \f[
>    P_\mathrm{casting} = f(E,\nu,h,d_\mathrm{casting})\:
>    (linear or non-linear formulation above)
> ```

This is not formatted well when generating the HTML documentation:

![image.png](https://files.reviewableusercontent.io/images/reviewable/846001/GWm51fqkISQ6d8z9zVOiSPSx/image.png)
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 167 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Lxa_ceh9wCLnrcHqO1P:-Lxa_ceh9wCLnrcHqO1Q:b-6bjptc) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L167)):*
> ```objc
>  system of equations is solved using a numerical solver. 
> 
>  The min_proximity and max_proximity properties limit the search region for a 
> ```

These are distances in meters along the ray?

How does "proximity" differ from "penetration depth" or "overlap depth"?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 172 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Lxa_S2R66L34aa1I1nY:-Lxa_S2R66L34aa1I1nZ:b-llga8z) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L172)):*
> ```objc
>  from being found. This is particularly important for situations with highly
>  curved meshes where a ray cast from the casting_mesh may intersect the 
>  target_mesh multiple times, or at infeasible contact locations. An example
> ```

Can you explain? This description hints that, if the proximity properties are not set properly, one could get invalid results. That does not seem desirable.
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 176 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Lxa_iqHAhVwSMFCiLnw:-Lxa_iqHAhVwSMFCiLnx:b-w886uo) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L176)):*
> ```objc
>  cartilage mesh can interesect the backsides of the femoral condyles, or the 
>  the sides of the trochealar groove multiple times. The min_proximity can be 
>  set to a negative value if you would like distance maps for the out of 
> ```

What is a distance map?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 182 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Lxa_nWPCrRgP5O_ghJ3:-Lxa_nWPCrRgP5O_ghJ4:b-ba69aa) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L182)):*
> ```objc
>  mapped.
> 
>  This component has some outputs such as tri_proximity, tri_pressure, and 
> ```

Would it be possible to use the full word `triangle` everywhere?

Relatedly, should these be named `mesh_proximity`, etc.?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 191 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LxabBKj85ZLuELMPPQo:-LxabBKj85ZLuELMPPQp:b-js4966) ([raw file](https://github.com/opensim-org/opensim-core/blob/b284515759b338dccc6fed71e7859cb8891edcfd/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L191)):*
> ```objc
>  summary metrics in a subspace of the mesh. The entries in the 
>  1 x 6 SimTK::Vector correspond to the subset of 
>  triangles whose center is located in the half space [+x, -x [...]

2020-01-09 00:56 UTC, chrisdembia requested changes
Hey Colin, I looked through `Smith2018ContactMesh` a little bit. I think these two components might be our most complex components!

The next time we chat synchronously, perhaps we could discuss (a) whether `Smith2018ContactMesh` should derive from `ContactGeometry` and if `Smith2018ContactMesh` should have its own scale factors.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-:-Ly6n1Pb9FJ8TOuqbXJK:b-peia4m)* status: 5 of 12 files reviewed, 57 unresolved discussions (waiting on @clnsmith)

___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 268 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6kU9609nQE7Ko5GxX:-Ly6kU9609nQE7Ko5GxY:b-9rl4p4) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L268)):*
> ```objc
>     // OUTPUTS
>     //=========================================================================
>     //number of colliding triangles
> ```

Please always place a space after `//`.
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 511 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6kqSb8akS1eMXCe53:-Ly6kqSb8akS1eMXCe54:b-5tk156) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L511)):*
> ```cpp
>                 tri_pressure(i) = K * tri_proximity(i) / h;
>                 tri_energy(i) = 0.5 * tri_area(i) * K *
>                     pow(tri_proximity(i), 2) / h;                
> ```

Use `SimTK::square()` instead.
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 537 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6kszY9Nt4nwrTqBlI:-Ly6kszY9Nt4nwrTqBlJ:b-x4yjfs) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L537)):*
> ```cpp
>             double depthC = kT / (kT + kC)*tri_proximity(i);
> 
>             double energyC = 0.5 * tri_area(i) * kC * pow(depthC, 2);
> ```

Use `SimTK::square()`.
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 634 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6kvwN7_DZ8Exn__3c:-Ly6kvwN7_DZ8Exn__3d:btyept9) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L634)):*
> ```cpp
> * @param flag2 A status flag
> * @param ptr Pointer to data structure containing values for h1, h2, k1, k2, dc
> */
> ```

Doxygen comments should go in the header.
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 1015 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6Y5O73pwAO88eCZrA:-Ly6Y5O73pwAO88eCZrB:bodgp0w) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L1015)):*
> ```cpp
>     stats.center_of_proximity(0) = COPrx_x;
>     stats.center_of_proximity(1) = COPrx_y;
>     stats.center_of_proximity(2) = COPrx_z;
> ```

No need to do this elementwise.
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 1018 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6l3sACjmXkJtIoBuD:-Ly6l3sACjmXkJtIoBuE:b-9l9mdz) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L1018)):*
> ```cpp
> 
>     //Center of Pressure
>     SimTK::Vector Num = tri_pressure.elementwiseMultiply(tri_area);
> ```

Only the names of classes/structs should start with an upper-case letter.
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 1036 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6YLSi348J1f1ccWw6:-Ly6YLSi348J1f1ccWw7:bodgp0w) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L1036)):*
> ```cpp
>     stats.center_of_pressure(0) = COPx;
>     stats.center_of_pressure(1) = COPy;
>     stats.center_of_pressure(2) = COPz;
> ```

No need to do this elementwise.
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 1155 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6YQkE4fHyORXLQc7p:-Ly6YQkE4fHyORXLQc7q:b-ck7msz) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L1155)):*
> ```cpp
>     constructProperty_poissons_ratio(0.0);
>     constructProperty_thickness(0.0);
>     constructProperty_use_variable_thickness(true);
> ```

These defaults should be functional rather than 0. If you want to force users to always provide a value, you could use NaN as the default and check in `extendFinalizeFromProperties()` that the user provided a value, but I prefer providing reasonable defaults.
___
*[OpenSim/Simulation/Model/Smith2018ContactMesh.h, line 34 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6mCc06Ww_jDgvKgd5:-Ly6mCc06Ww_jDgvKgd6:b-idcn3y) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ContactMesh.h#L34)):*
> ```objc
> //=============================================================================
> //                       Smith2018ArticularContact
> //=============================================================================
> ```

In general, this class description could be organized better so that the information relevant to all users come first. For example, most users will likely inherit meshes from others. So details about how to create a mesh could go farther down, and it would be nice to have a subheading such as "Choosing the coarseness of the mesh".
___
*[OpenSim/Simulation/Model/Smith2018ContactMesh.h, line 41 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6lKJu8UwBoyV97mzG:-Ly6lKJu8UwBoyV97mzH:b-ifzdjr) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ContactMesh.h#L41)):*
> ```objc
> only the contact surface. The mesh does not need to be closed (ie water tight) 
> and a smaller number of triangles in the mesh will lead to faster 
> collision dection performance. The normal vectors of the mesh should be 
> ```

typo "dection" 
___
*[OpenSim/Simulation/Model/Smith2018ContactMesh.h, line 43 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6lQWFA3ZWs0379I1f:-Ly6lQWFA3ZWs0379I1g:b5nfy2v) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ContactMesh.h#L43)):*
> ```objc
> collision dection performance. The normal vectors of the mesh should be 
> pointing outwards from the articular surface towards the opposing contact 
> mesh. Misdirected triangle normals is a common issue when constructing new 
> ```

What happens if the objects are facing the opposite direction from what's intended? For example, what happens if the tibia is above the femur? This specific scenario is not likely, but it's possible in general.
___
*[OpenSim/Simulation/Model/Smith2018ContactMesh.h, line 47 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-Ly6lXS_8cnBM1NJRx3M:-Ly6lXS_8cnBM1NJRx3N:b-i7u69l) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ContactMesh.h#L47)):*
> ```objc
> the triangle areas and normals, and the derivatives of these outputs with 
> respect to joint coordinates are commonly calculated in integrators [...]

2020-01-16 20:20 UTC, carmichaelong requested changes
I just finished up a first pass of the code. Thanks for all the hard work on getting this ready. For such a huge class, it was mostly easy to follow along. Happy to chat about steps moving forward, but I think this your goal of a stable interface by the workshop is a good timeline.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2658)* status: 5 of 12 files reviewed, 75 unresolved discussions (waiting on @clnsmith)

___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 66 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyQooTc9IKOv0Z1AJwY:-LyQooTc9IKOv0Z1AJwZ:bksn8c8) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L66)):*
> ```objc
> The major speed-up in the algorithm leverages the fact that changes in joint
> coordinates and thus articular contact patterns between time steps are
> generally small. Thus, after reposing the meshes, (i.e. realizePosition()) each
> ```

Is it guaranteed that "time steps are small" or should users only use this in cases when time steps are on? (e.g., is there anything stopping users from using this contact in a forward simulation with very loose tolerances or with fixed time steps?)
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 87 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyQpKfg9PB7nsQiMWI2:-LyQpKfg9PB7nsQiMWI3:b-xd7r1z) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L87)):*
> ```objc
> casting_mesh and target_mesh are switched, the simulation results will NOT be
> exactly the same. For best performance, the casting_mesh should be set to the
> mesh that contains the smaller number of triangles.
> ```

Comments like this that explain some of the implications for users are great!
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 156 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyQsSro3zDcKsrcvKcw:-LyQsSro3zDcKsrcvKcx:bxr6t21) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L156)):*
> ```objc
> force equilibrium, assuming that the force applied to a pair of contacting
> triangles is equal and opposite. This formulation further assumes that the
> triangles in contact have the same area. The fourth equation states that the
> ```

Does this mean that when using this class, one should make sure that triangles in contact have the same area always? How sensitive is the formulation when this assumption is not followed?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 236 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyR-ukn4ticlc3viD0I:-LyR-ukn4ticlc3viD0J:b-msc5jz) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L236)):*
> ```objc
>     // PROPERTIES
>     //=========================================================================
>     OpenSim_DECLARE_PROPERTY(min_proximity, double, "The minimum overlap "
> ```

What happens if a user sets min_proximity > max_proximity?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 405 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyQxUs7-0vDhG1oUlNv:-LyQxUs7-0vDhG1oUlNw:bk8q6tt) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L405)):*
> ```objc
>     Smith2018ArticularContactForce();
> 
>     Smith2018ArticularContactForce(const std::string& name,
> ```

When should a user use this constructor or another constructor? e.g., does this particular one use the parameters of the mesh passed in while the one below overrides the mesh with the passed in contact parameters?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.h, line 745 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyR-TFw6q7n7UCF_3ko:-LyR-TFw6q7n7UCF_3kp:b5z4pjg) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.h#L745)):*
> ```objc
>     // PROPERTIES
>     //=========================================================================
>         OpenSim_DECLARE_PROPERTY(elastic_modulus, double, 
> ```

What are the default values?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 135 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyR1JAi2IVt19Uc-3rW:-LyR1JAi2IVt19Uc-3rX:b1iit3l) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L135)):*
> ```cpp
>     Super::extendAddToSystem(system);
> 
>     Smith2018ArticularContactForce::ContactParameters target_mesh_params = 
> ```

Are these two parameters used in this function?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 221 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyR324b3EaOEZOX86q9:-LyR324b3EaOEZOX86qA:bmv26m) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L221)):*
> ```cpp
>         casting_mesh_def_vec3, Stage::Dynamics);
> 
>     addCacheVariable<double>("target.contact_area",0, Stage::Dynamics);
> ```

Add a space between "," and "0"
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 433 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyRcMZ01oRtU45go2ro:-LyRcMZ01oRtU45go2rp:b-5zghaq) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L433)):*
> ```cpp
>     else {
>         cache_mesh_name = "target";
>         tContactParams = get_casting_mesh_contact_params();
> ```

The variable names look flipped here, but I'm assuming this is to account for some flip in which is the cached mesh? Maybe some comments here could help for maintainability?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 515 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LySijeW53ueZlpgJ8ZV:-LySijeW53ueZlpgJ8ZW:b48n7hl) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L515)):*
> ```cpp
>             }
> 
>             if (get_elastic_foundation_formulation() == "nonlinear") {
> ```

Is there a specific reason to use continue's here rather than an if/else if statement? What happens if get_elastic_foundation_formulation returns something other than "linear" or "nonlinear"?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 561 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyRd3DB1AY0aNYrVvm-:-LyRd3DB1AY0aNYrVvm0:b3pf5ib) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L561)):*
> ```cpp
> 
>             //solution params
>             double ftol = 1e-4, xtol = 1e-4, gtol = 0.0;
> ```

Should a user be able to adjust these parameters for their own model?
___
*[OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp, line 713 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2658#-LyRfWjz3ZcIpHhYRKIJ:-LyRfWjz3ZcIpHhYRKIK:b-7ix0j2) ([raw file](https://github.com/opensim-org/opensim-core/blob/446e6a4ea2176b1052abe3eefbd42aee1e98d41b/OpenSim/Simulation/Model/Smith2018ArticularContactForce.cpp#L713)):*
> ```cpp
 [...]

2026-07-08 13:14 UTC, nickbianco commented
Closing: stale PR.

2026-07-08 13:14 UTC, closed without merging