[WIP] TGCS2021 IMU Tracking Example
opensim-org/opensim-core pull request #2996
Opened 2021-05-06 00:42 UTC by nickbianco

Related issue #2982

### Brief summary of changes
First pass at implementing the IMU tracking example for the TGCS workshop. This example example is a modification of the squatToStand tracking example from the last TGCS workshop.

### Looking for feedback on...

1.  Is this the right amount of content for one 30 minute example? I currently have separate parts for the non-noisy and noisy acceleration tracking example, but this could be combined into one part. Or we don't have participants "follow-the-leader" for the noisy accelerations steps, but just 

2. How will @aymanhab's SyntheticIMUReporter fit into this example? 

3. Should we have a step to add IMU frames to the model (right now I just use body frames)? Technically this isn't a totally necessary step, but it would be nice to mimic a real model that someone would potential use with OpenSense and/or Moco for IMU-tracking.

4. Other general comments about the example are welcome.

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

2021-05-06 19:27 UTC, aymanhab commented
@nickbianco PR #2997  has the refined API for reporting IMU data, and should help us collectively picture how these pieces will be integrated.

2021-05-06 19:29 UTC, aymanhab commented on Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m
> +% model = getMuscleDrivenModel();
The name is a bit generic (TorqueDrivenModel of what?) I'd suggest we pinpoint name, tie to example/context

2021-05-06 19:32 UTC, aymanhab commented on Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m
> +solver.set_num_mesh_intervals(50);
Rationale for these numbers if educational, e.g. how they affect convergence, accuracy, speed etc. could be helpful in a tutorial

2021-05-06 19:34 UTC, aymanhab commented on Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m
> +
You can add SyntheticIMUs manually/programmatically and wire their outputs below

2021-05-06 19:40 UTC, aymanhab commented
@nickbianco minor comments but looks great overall. I'll ask for another review from @carmichaelong as a more prototypical user/participant. We probably can merge this once done then refactor as the changes shouldn't be tricky AFAICT.

2021-05-06 21:39 UTC, carmichaelong requested changes
So... I definitely went a little too deep on the comments here, so most of them are safe to ignore at this point (especially ones about plotting). Overall this is in great shape already.

More relevant comments at this stage:
1. I think we're probably in similar agreement that some parts of this need to be either pre-done or follow-the-leader for 30 min. We'll definitely need to test with others to figure out timing, but my first guess is that you'd want maybe:
- all plotting code given
- parts 1, 2, 3 given but stepped through together(?). The visualizer and plots already in the example could help people feel like they're following along too if you step and discuss them clearly
- follow-the-leader for the rest?

2. strong +1 for creating separate IMU frames (also commented on the relevant code line)

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-M_2RwYPCZ1KRM4IXmEt:b-olkgac)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 9 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-MZz6yifvy5-GXqyjzX3-r1-9:-M_2PLSw6aeMLCuYwOmk:bn8ofd8) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L9)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

The name is a bit generic (TorqueDrivenModel of what?) I'd suggest we pinpoint name, tie to example/context
</blockquote></details>

Perhaps just even noting that the model is one-legged, 3dof model with added coordinate actuators is useful for context, and then can tell the user to check out getTorqueDrivenModel()` below to see how this model was generated
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 11 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2Nhbp21Tq1JXCXXNN:-M_2Nhbp21Tq1JXCXXNO:b-190f2k) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L11)):*
> ```objc
> % model = getMuscleDrivenModel();
> 
> %% Part 1: Effort minimization prediction
> ```

Just a little more high-level detail here might be helpful. Perhaps something like "Generate a simulation of a sit-to-stand motion that will be used to create synthetic IMU signals later. This simulation is generated by solving for a minimum effort solution."
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 53 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2NWtW96xoghcrYX9i:-M_2NWtW96xoghcrYX9j:bocgegs) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L53)):*
> ```objc
> problem.setStateInfoPattern('/jointset/.*/speed', [], 0, 0);
> 
> % Part 1d: Add a MocoControlCost to the problem.
> ```

MocoControlCost -> MocoControlGoal
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 69 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2OHtY2atw6ElHABRS:-M_2OHtY2atw6ElHABRT:b-k2uti1) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L69)):*
> ```objc
> end
> 
> %% Part 2: Add IMU tracking frames to the model 
> ```

Adding separate IMU frames with different orientations on a couple sensors would be cool. I think it's a small step for us to add, but would seem like a big difference to end users learning how this all works
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 127 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2QQ5l8PlhtZ1HMfY7:-M_2QQ5l8PlhtZ1HMfY8:b-ador7y) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L127)):*
> ```objc
>     
> %% Part 6: Noisy synthetic acceleration tracking problem 
> % Part 6a: Add noise to synthetic accelerations
> ```

Would be nice to know (on a high level) the type of noise and roughly how much is being added here for context
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 137 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2Q9GV6Vkaf_qUwmVn:-M_2Q9GV6Vkaf_qUwmVo:buhsbm7) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L137)):*
> ```objc
> 
> % Part 6c: Plot the synthetic acceleration signals.
> plotAccelerationSignals(accelerationReference, accelerationReferenceNoisy);
> ```

I'm going back and forth on this comment... my inclination is to add a legend even though it's sort of obvious which one is the "noisy" trajectory and which isn't
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 147 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2Qhv8DjxuN2iNm7ef:-M_2Qhv8DjxuN2iNm7eg:b-cfa2dm) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L147)):*
> ```objc
> 
> %% Part 7: Compare noisy tracking solution to previous tracking solution
> mocoPlotTrajectory('trackingSolution.sto', 'noisyTrackingSolution.sto', ...
> ```

The kinematics plots from this are super cool. The plots from the actuators are almost hard to believe that even though the actuators were noisy, the kinematics were pretty smooth. Might also be good to play around with the plotting settings since a dashed line that's super noisy is hard to read at times


<!-- Sent from Reviewable.io -->

2021-05-11 22:11 UTC, nickbianco reviewed
Thanks for the helpful reviews @aymanhab and @carmichaelong. I've addressed everything not related to the new IMUDataReporter. I'll make those changes once that PR is through.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-M_STRut3NHmrZ5B3iOJ:b-4u6fsi)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 9 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-MZz6yifvy5-GXqyjzX3-r1-9:-M_SJ1Un7PPtYHBPkFO3:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L9)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Perhaps just even noting that the model is one-legged, 3dof model with added coordinate actuators is useful for context, and then can tell the user to check out getTorqueDrivenModel()` below to see how this model was generated
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 11 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2Nhbp21Tq1JXCXXNN:-M_SJ2r65EnOd46v6V4E:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L11)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Just a little more high-level detail here might be helpful. Perhaps something like "Generate a simulation of a sit-to-stand motion that will be used to create synthetic IMU signals later. This simulation is generated by solving for a minimum effort solution."
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 53 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2NWtW96xoghcrYX9i:-M_SJ4we9bZyQ6caUNnq:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L53)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

MocoControlCost -> MocoControlGoal
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 58 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-MZz6yifvy5-GXqyjzX3-r1-58:-M_SM7n3649X23F0Pmp_:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L58)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Rationale for these numbers if educational, e.g. how they affect convergence, accuracy, speed etc. could be helpful in a tutorial
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 127 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2QQ5l8PlhtZ1HMfY7:-M_SODnx2e2KbWJWeTQj:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L127)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Would be nice to know (on a high level) the type of noise and roughly how much is being added here for context
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 137 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2Q9GV6Vkaf_qUwmVn:-M_SQuQn9fUSfhMRKIiZ:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L137)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

I'm going back and forth on this comment... my inclination is to add a legend even though it's sort of obvious which one is the "noisy" trajectory and which isn't
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 147 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2Qhv8DjxuN2iNm7ef:-M_SQv9c97hS68y3cSZm:b-z52903) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L147)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

The kinematics plots from this are super cool. The plots from the actuators are almost hard to believe that even though the actuators were noisy, the kinematics were pretty smooth. Might also be good to play around with the plotting settings since a dashed line that's super noisy is hard to read at times
</blockquote></details>

This was honestly confusing to me too. I've been double checking that I wasn't accidentally plotting the original tracking solution instead. Do these noisy controls make sense to you consider how smooth the dynamics look? I'm honestly not sure that this makes sense to me yet.


<!-- Sent from Reviewable.io -->

2021-06-07 18:40 UTC, nickbianco reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @aymanhab and @carmichaelong)

___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 69 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-M_2OHtY2atw6ElHABRS:-MbblY8t46yNp2OWiXrC:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L69)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Adding separate IMU frames with different orientations on a couple sensors would be cool. I think it's a small step for us to add, but would seem like a big difference to end users learning how this all works
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 72 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-MZz6yifvy5-GXqyjzX3-r1-72:-MbblYWqDxQEQS5X1NCp:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/032ae88b95e902566456e481e0d1569a1e22c6f8/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L72)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

You can add SyntheticIMUs manually/programmatically and wire their outputs below
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-07 18:46 UTC, nickbianco reviewed
@aymanhab @carmichaelong I've updated the IMU tracking example to include the new IMU component. I decided to use the `analyzeVec3()` function in SimulationUtilities as it was simpler for the scripting example compared to IMUDataReporter. 

After the next round of reviews is done, I will create the fill-in-the-blank version of this example to get feedback on which portions we'll provide for users in the workshop and which portions we'll have them fill in.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-MbblcUt0BsSWNcsIbOv:b2drguf)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @aymanhab and @carmichaelong)



<!-- Sent from Reviewable.io -->

2021-06-09 17:53 UTC, aymanhab reviewed
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @carmichaelong)



<!-- Sent from Reviewable.io -->

2021-06-10 20:56 UTC, carmichaelong reviewed
Just reviewed and ran the example locally. Changes look great overall. Two comments, neither of which are necessarily blocking:
1. Out of the box, I don't see the skeletal model when the visualizer pops up (I only see the moving IMU blocks)
2. The noisy solution is still a little confusing (and I have no sense if the inertia of the bones would be enough to "smooth" out the kinematics), but I think you said this might be removed anyway? Going through the code, I noticed that the comparison between noisy and normal signals was only done through plotting. While I would assume that  that updating `accelerationIMUTracking` with `accelerometerSignalsNoisy` is done correctly, I tried to find a `getAccelerationReference` or similar method to double check but couldn't find an easy way to do this (granted I didn't try for super long)

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-MbrgPmDCTIC8cuthlHM:bbyxzk0)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @nickbianco)



<!-- Sent from Reviewable.io -->

2021-06-11 19:54 UTC, nickbianco reviewed
Thanks @carmichaelong. I've removed the noisy accelerations section per our discussion in dev meeting. 

I did some testing with the geometry files and I don't think the full distribution solves the issue. I think we need to copy the "Geometry" folder into each example folder (similar to the OpenSense example). I'll do this via CMake so we don't have copies of the this folder in the source.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-MbwcEiq3IHvdykwU_me:b-71m5vc)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @nickbianco)



<!-- Sent from Reviewable.io -->

2021-06-11 22:53 UTC, nickbianco reviewed
@carmichaelong @aymanhab I've updated the CMake to provide a copy of the Geometry folder for the squat-to-stand example. Let me now if you can see the skeleton when you run the example now.

I've also made a few final tweaks to this example, including simplifying the solver settings for the predictive problem. Unless you have any final thoughts, I'll start creating the fill-in-the-blank example and the Python versions.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-MbxGFJN4HSYD_k9QLS5:b-5bwrcc)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @nickbianco)



<!-- Sent from Reviewable.io -->

2021-06-14 18:23 UTC, carmichaelong requested changes
Geometry is showing up for me now. I've also left some quick minor comments too.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-McAjeP-COOEYMTue-Hz:b-2osamd)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @nickbianco)

___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/mocoPlotTrajectory.m, line 43 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-McAXUry-wy_GVUbw4fn:-McAXUry-wy_GVUbw4fo:b-pokvsa) ([raw file](https://github.com/opensim-org/opensim-core/blob/6397312b51ee532d1861126f4f4e6eb3acb9c2cf/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/mocoPlotTrajectory.m#L43)):*
> ```objc
>     end
>     
>     stateName = stateNames.get(i); %.toCharArray';
> ```

remove commented part of line?
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/mocoPlotTrajectory.m, line 85 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-McAfDNf8MjKx8Le0C43:-McAfDNg40vpwkJ158WV:b-ydxpa7) ([raw file](https://github.com/opensim-org/opensim-core/blob/6397312b51ee532d1861126f4f4e6eb3acb9c2cf/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/mocoPlotTrajectory.m#L85)):*
> ```objc
>         hold on
>         yB = trajB.getControlMat(controlNames.get(i));
>         plot(trajB.getTimeMat(), yB, '-b', 'linewidth', 2.5);
> ```

I'm assuming this dashed blue line was removed because it looked weird with a noisy plot from before? Now that it's smooth again, could consider making the blue line dashed to match the same style as the states plot above.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 149 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-McAXZde3b7bDL8VfPet:-McAXZde3b7bDL8VfPeu:b8oiaxz) ([raw file](https://github.com/opensim-org/opensim-core/blob/6397312b51ee532d1861126f4f4e6eb3acb9c2cf/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L149)):*
> ```objc
> 
> %% Part 5: Compare tracking solution to original prediction
> % Part 5a: Plot the tracking solution against the prediction. This is 
> ```

This is *a* convenience function...
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 239 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-McAkbF-7IeKwVSBBgvl:-McAkbF-7IeKwVSBBgvm:b-i2gkwy) ([raw file](https://github.com/opensim-org/opensim-core/blob/6397312b51ee532d1861126f4f4e6eb3acb9c2cf/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L239)):*
> ```objc
> torso = accelerationsReference.getDependentColumn(...
>     '/bodyset/torso/torso_imu_offset').getAsMat();
> plot(time, torso(:,1), 'b-', 'linewidth', 3)
> ```

For each the three subplots, the first line style could be `r-` and the second could be `b--` to match previous plots
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 247 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-McAkXAjBTvE5Lr8s_FN:-McAkXAjBTvE5Lr8s_FO:b-ro23mf) ([raw file](https://github.com/opensim-org/opensim-core/blob/6397312b51ee532d1861126f4f4e6eb3acb9c2cf/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L247)):*
> ```objc
> end
> if nargin == 2
>     legend('reference', 'tracking solution', 'location', 'best');
> ```

The legend could be changed to "predict" and "track" to match with other plots


<!-- Sent from Reviewable.io -->

2021-06-15 18:49 UTC, nickbianco reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @aymanhab and @carmichaelong)

___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/mocoPlotTrajectory.m, line 43 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-McAXUry-wy_GVUbw4fn:-McG-KzKAVYvdihzTxRC:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6397312b51ee532d1861126f4f4e6eb3acb9c2cf/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/mocoPlotTrajectory.m#L43)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

remove commented part of line?
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/mocoPlotTrajectory.m, line 85 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-McAfDNf8MjKx8Le0C43:-McG-L_P70KK3nazIfXW:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6397312b51ee532d1861126f4f4e6eb3acb9c2cf/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/mocoPlotTrajectory.m#L85)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

I'm assuming this dashed blue line was removed because it looked weird with a noisy plot from before? Now that it's smooth again, could consider making the blue line dashed to match the same style as the states plot above.
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 149 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-McAXZde3b7bDL8VfPet:-McG-MER2qbO8aWQT5zH:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6397312b51ee532d1861126f4f4e6eb3acb9c2cf/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L149)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

This is *a* convenience function...
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 239 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-McAkbF-7IeKwVSBBgvl:-McG-Nma2uvM8aWDe8YM:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6397312b51ee532d1861126f4f4e6eb3acb9c2cf/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L239)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

For each the three subplots, the first line style could be `r-` and the second could be `b--` to match previous plots
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m, line 247 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-McAkXAjBTvE5Lr8s_FN:-McG-ORi8c45yemA2yJN:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6397312b51ee532d1861126f4f4e6eb3acb9c2cf/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking_answers.m#L247)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

The legend could be changed to "predict" and "track" to match with other plots
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-16 19:05 UTC, nickbianco reviewed
@carmichaelong, @aymanhab  Finished the fill-in-the-blanks file, ready for review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-McLCWqS5f6yONcqWDM3:b1lpkun)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @aymanhab and @carmichaelong)



<!-- Sent from Reviewable.io -->

2021-06-16 23:58 UTC, carmichaelong approved these changes
Ran the example again locally just to double check and it's all looking good to me. 

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-McLrBQE6JxZ7dZJliEl:b-vow9qz)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2021-06-17 00:56 UTC, nickbianco reviewed
:thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-McMSuD86Uu6BsuouwZS:b4c9lyr)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2021-06-24 20:40 UTC, nickbianco reviewed
@aymanhab @carmichaelong Python versions created. Ready for review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-MczkDWJ3ZHW4az6GQDi:b-zfk1oq)* status: 1 of 16 files reviewed, all discussions resolved (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2021-06-25 21:01 UTC, carmichaelong commented
On Python 3.8 with Numpy 1.20.2 and matplotlib 3.3.4, python example worked for me locally (using PYTHONPATH)

2021-06-28 21:09 UTC, nickbianco reviewed
Great! Thanks for testing @carmichaelong.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-MdJS4Ua3Yf2YzBgLWVJ:ba7whsy)* status: 1 of 16 files reviewed, all discussions resolved (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2021-06-30 17:04 UTC, carmichaelong requested changes
Just one more minor comment. Good to go after that is addressed

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-MdSr8VS1kAGCAEjRURf:b-je7h6o)* status: 1 of 17 files reviewed, 1 unresolved discussion (waiting on @aymanhab and @nickbianco)

___
*[Bindings/Python/examples/Moco/exampleSquatToStand/exampleSquatToStand_answers.py, line 109 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-MdSqkLd4nDrQlb4s8GN:-MdSqkLe-kYZyf2KRsLn:b-t89ke9) ([raw file](https://github.com/opensim-org/opensim-core/blob/ce6225c3bd52a845c5937b0ff21dc86e9951f880/Bindings/Python/examples/Moco/exampleSquatToStand/exampleSquatToStand_answers.py#L109)):*
> ```Python
> ## Part 4: Muscle-driven Inverse Problem
> # Create a MocoInverse tool instance.
> inverse = MocoInverse()
> ```

missing osim preflix


<!-- Sent from Reviewable.io -->

2021-06-30 17:36 UTC, nickbianco reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996)* status: 1 of 17 files reviewed, 1 unresolved discussion (waiting on @aymanhab and @carmichaelong)

___
*[Bindings/Python/examples/Moco/exampleSquatToStand/exampleSquatToStand_answers.py, line 109 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-MdSqkLd4nDrQlb4s8GN:-MdSzao87EhRMWd59Rh0:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/ce6225c3bd52a845c5937b0ff21dc86e9951f880/Bindings/Python/examples/Moco/exampleSquatToStand/exampleSquatToStand_answers.py#L109)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

missing osim preflix
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-30 17:51 UTC, carmichaelong approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2996#-:-MdT22kn62SF7N-A4JpX:bnfp4nl)* status: 1 of 17 files reviewed, all discussions resolved (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2021-06-30 21:08 UTC, merged

2021-06-30 21:09 UTC, nickbianco commented
Thanks @carmichaelong.