Add synthetic imu
opensim-org/opensim-core pull request #2997
Opened 2021-05-06 19:25 UTC by aymanhab

Fixes issue #2566 

### Brief summary of changes
Introduced SyntheticIMU object and an Analysis that reports data from the SyntheticIMUs.

### Testing I've completed
Test case was added to testAnalyzeTool

### Looking for feedback on...
Naming, convenience, ease-of-use.

### CHANGELOG.md (choose one)
Will be updated once close to ready/reviewed

2021-05-06 19:41 UTC, aymanhab commented
@nickbianco For your review and as a potential customer.

2021-05-06 21:14 UTC, aymanhab commented
@carmichaelong

2021-05-07 00:36 UTC, nickbianco requested changes
Thanks for the great first draft on this. I left a bunch of thoughts about how to potentially simplify the reporter and add clarity to which model frames are designated as "IMU frames". Let me know what you think about these ideas. I'm pretty flexible as far as compatibility with the TGCS workshop example goes.

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-:-M_3DvYfDMZv1T5SSvq4:b-f58z98)* status: all files reviewed, 22 unresolved discussions (waiting on @aymanhab)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 373 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_310dl0ao2NuF2CALs:-M_310dl0ao2NuF2CALt:bbsgay0) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L373)):*
> ```cpp
>     Joint& joint = pendulum.updJointSet()[0];
>     auto& qi = joint.updCoordinate();
>     qi.setValue(s, SimTK::Pi/2.); // static
> ```

This is static because it's at the lowest potential energy position?
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-M_30vzm1tmZN3DsOrZN:b-6ri78b) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
> ```cpp
>     // Compare results to Body kinematics
>     /* Attempt to compare to createSyntheticIMUAccelerationSignals  doesn't
>     * work now since the latter requires passing in controls!
> ```

You should be able to pass in an empty controls table.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 4 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_31LlW8TiMZiGLj5XZ:-M_31LlW8TiMZiGLj5X_:b90t2l3) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L4)):*
> ```objc
> #define _SYNTHETIC_IMUDATA_REPORTER_h_
> /* -------------------------------------------------------------------------- *
>  *                         OpenSim:  SyntheticIMUDataReporter.h               *
> ```

Since this class could also be useful for reporting model-generated IMU acceleration signals, I'm wondering if this reporter could have a more general name. Some ideas: `InertialSensorReporter`, `InertialMeasurementUnitReporter`, or even just `IMUReporter`.  This would also suggest changing the name of the `SyntheticIMU` class too. I'll leave some comments there as well.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 12 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_31pVT13947wdzJzGG:-M_31pVT13947wdzJzGH:bb6ht36) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L12)):*
> ```objc
>  * through the Warrior Web program.                                           *
>  *                                                                            *
>  * Copyright (c) 2005-2017 Stanford University and the Authors                *
> ```

2021
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 65 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_345tz0T-IS12Vz7D2:-M_345tz0T-IS12Vz7D3:b-d2tk36) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L65)):*
> ```objc
>             "Report linear accelerations of Synthetic IMUs, default is true.");
> 
>     OpenSim_DECLARE_PROPERTY(IMU_frames, std::string,
> ```

I think all lowercase property names are preferred, i.e. `imu_frames`.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 66 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34HgF15hU36zpMWoD:-M_34HgF15hU36zpMWoE:b-hjac0j) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L66)):*
> ```objc
> 
>     OpenSim_DECLARE_PROPERTY(IMU_frames, std::string,
>             "What frames to report. Frames, Bodies, Custom are valid. If Custom populate ");
> ```

The doc string is incomplete.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_34bbb2Om7mCgYMeSe:byf1dsn) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
> ```objc
>             "What frames to report. Frames, Bodies, Custom are valid. If Custom populate ");
>     OpenSim_DECLARE_LIST_PROPERTY(frame_paths, std::string,
>             "ComponentPaths for frames to attach Synthetic IMUs to, if IMU_attachments is set to Custom.");
> ```

I see why you have both `imu_frames` and `frame_paths`, but I think it might be simpler to just have `frame_paths` and always have users provide the frames they want to calculate quantities for. I think most users will have a specify set of `Frame`s that represent their IMUs in the model, and these should probably be distinct from Bodies.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_37Km3EXPTzpfSUV9X:-M_37Km3EXPTzpfSUV9Y:b4b9hf2) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L119)):*
> ```objc
>     // ANALYSIS
>     //--------------------------------------------------------------------------
>     int
> ```

The code formatting here and for the next several lines is a little wonky.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 10 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_32qh594X-hJlqbzdB:-M_32qh594X-hJlqbzdC:bb6ht36) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L10)):*
> ```cpp
>  * through the Warrior Web program.                                           *
>  *                                                                            *
>  * Copyright (c) 2005-2020 Stanford University and the Authors                *
> ```

2021
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 51 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_383om676fmBvqHsgP:-M_383om676fmBvqHsgQ:b-i7cn98) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L51)):*
> ```cpp
>  */
> SyntheticIMUDataReporter::SyntheticIMUDataReporter(Model *aModel) :
>     Analysis(aModel), _modelLocal(nullptr) {
> ```

This could use an indent.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 55 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_389WsCzKpdzCQ_3Zp:-M_389Wt8QRLlMi5yhW_:bg187qd) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L55)):*
> ```cpp
>     constructProperties();
>     if(aModel) 
>         setModel(*aModel);
> ```

Unless on a single line, I prefer if-statements with brackets.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 65 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_386HiCB6zrnqjys4Y:-M_386HiCB6zrnqjys4Z:bo6awcd) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L65)):*
> ```cpp
> SyntheticIMUDataReporter::SyntheticIMUDataReporter(const SyntheticIMUDataReporter &aSyntheticIMUDataReporter): 
>     Analysis(aSyntheticIMUDataReporter),
>     _modelLocal(nullptr) {
> ```

Indent.
___
*[OpenSim/Analyses/SyntheticIMUDataReporte [...]

2021-05-07 16:11 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: all files reviewed, 22 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 373 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_310dl0ao2NuF2CALs:-M_4x2Ih0lOyxt6SkPb4:b-rf9ajn) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L373)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This is static because it's at the lowest potential energy position?
</blockquote></details>

Yes, just a trivial case, but will beef this up to compare against BodyKinematics output which computes similar quantities already.
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-M_4xJs52ih9T1kI3Fng:b-8gsqwa) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

You should be able to pass in an empty controls table.
</blockquote></details>

Unfortunately no, the Analyze method downstream is very strict requiring Controls that match model in size and sampling. I'd prefer not to weaken this requirement but this also opens the question of whether/how to enforce that dynamics can be evaluated to compute Accelerations
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 4 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_31LlW8TiMZiGLj5XZ:-M_4yAlD1pW0AUr9Vf6N:b9ihgcp) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L4)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Since this class could also be useful for reporting model-generated IMU acceleration signals, I'm wondering if this reporter could have a more general name. Some ideas: `InertialSensorReporter`, `InertialMeasurementUnitReporter`, or even just `IMUReporter`.  This would also suggest changing the name of the `SyntheticIMU` class too. I'll leave some comments there as well.
</blockquote></details>

I'm pretty open, the rationale was using "Synthetic-IMU" as an abstraction that we can build upon (with attachment, noise-model, visualization, possibly saturation-limits etc.) and this Reporter reads the "data" off these Synthetic-IMUs. This makes it sensible to go back and generate data from existing simulations by attaching a synthetic-IMUs. I understand agreeing on a short but descriptive name is always a challenge. 
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 65 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_345tz0T-IS12Vz7D2:-M_5-pAiBWBNfmpt8AmZ:bfw8rka) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L65)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I think all lowercase property names are preferred, i.e. `imu_frames`.
</blockquote></details>

ok, will do.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 66 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34HgF15hU36zpMWoD:-M_504LkD-dVkXd9xcQC:b-z1tph9) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L66)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

The doc string is incomplete.
</blockquote></details>

good catch :+1: 
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_37Km3EXPTzpfSUV9X:-M_50T33Dx8M8xu8MLd-:b-55o907) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L119)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

The code formatting here and for the next several lines is a little wonky.
</blockquote></details>

:smiley: Wonky!
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 182 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3A1Po92pkVC_7BiDA:-M_514Ba942_qm0qgHW6:b-yv5ocl) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L182)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

`_modelLocal` is a copy? I'm just wondering if it makes sense not to add the `_orientationsReporter` if `get_report_orientations()` is false, etc.
</blockquote></details>

Yes it's a copy since Analyses should be passive and not have side-effect on the model being analyzed. 
I debated this and the main reason I add them all is that in essence the IMU records all the data anyway internally but we only report what the user wants. You may have orientation errors dependent on angular_velocity but this is a bit hypothetical at the moment, so I'm open.
___
*[OpenSim/Simulation/OpenSense/SyntheticIMU.h, line 46 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3EqiZ8-e61dTxgQUB:-M_57DgA1LZMbaCiGCH2:bdhblef) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Simulation/OpenSense/SyntheticIMU.h#L46)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Is there a way that this class could automatically add visualization for IMU Frames placed on the model? That would be a nice addition (and helpful for the workshop).
</blockquote></details>

As of now it's computational only but sure can add visuals if needed.
___
*[OpenSim/Simulation/OpenSense/SyntheticIMU.h, line 48 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3CQ8l4z1vl1uUbIf-:-M_57dzE17F2jnoUKhg6:b7cxiad) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Simulation/OpenSense/SyntheticIMU.h#L48)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

The name `attachment_frame` could suggest that the IMU is positioned and oriented differently than the position and orientation of this `Frame`, but currently that is not true. I think it could make more sense to call this `Frame` "the" IMU frame.
</blockquote></details>

so, what's the name of the socket? "the", what will it look like from inside the code of the IMU?
___
*[OpenSim/Simulation/OpenSense/SyntheticIMU.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_327MaDbC9nvwN9TOo:-M_6aCDt3R9HBccREpJ_:b-35i107) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Simulation/OpenSense/SyntheticIMU.h#L68)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Did you plan to add in the gravity offset and re-expression into the body frame here? That would replace the need for the utility function I created.
</blockquote></details>

Very easy to add as outputs and that's where having an expert client of the class shines.


<!-- Sent from Reviewable.io -->

2021-05-07 16:30 UTC, aymanhab reviewed
Thanks for the excellent feedback @nickbianco, if @carmichaelong can chime in on the naming/usage as well that would help moving this forward.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-:-M_6aRcVAWDrPLRg7x_P:bir6dfz)* status: all files reviewed, 22 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 12 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_31pVT13947wdzJzGG:-M_6bfq68p9PMcpX18BE:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L12)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 65 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_345tz0T-IS12Vz7D2:-M_6beHNAVQB93u666QC:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L65)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

ok, will do.
</blockquote></details>

Done.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 66 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34HgF15hU36zpMWoD:-M_6bwGrDg5VglhAcv07:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L66)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

good catch :+1: 
</blockquote></details>

Done.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_6c4Lb4laYWNksJYkB:b-mc2ww4) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I see why you have both `imu_frames` and `frame_paths`, but I think it might be simpler to just have `frame_paths` and always have users provide the frames they want to calculate quantities for. I think most users will have a specify set of `Frame`s that represent their IMUs in the model, and these should probably be distinct from Bodies.
</blockquote></details>

The competing needs here are: making easy things easy and making hard things possible, I felt this strikes a reasonable balance but open to counter arguments. 
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_37Km3EXPTzpfSUV9X:-M_6dZDy872EUybqSnk3:b-886gsx) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L119)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

:smiley: Wonky!
</blockquote></details>

Fixed
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 51 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_383om676fmBvqHsgP:-M_6e8yOCP_-cwtGU4zs:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L51)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This could use an indent.
</blockquote></details>

Done.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 55 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_389WsCzKpdzCQ_3Zp:-M_6e7oQBlKOcecp3M48:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L55)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Unless on a single line, I prefer if-statements with brackets.
</blockquote></details>

Done.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 65 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_386HiCB6zrnqjys4Y:-M_6eAYU720JrqnFzSpp:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L65)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Indent.
</blockquote></details>

Done.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 132 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_38O909hoBZs1DtkFt:-M_6eHT6A8nO071nKRta:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L132)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Is this still needed for debugging or can we remove it?
</blockquote></details>

Done.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 180 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3978M9dXGZaNscp49:-M_6eWeG4nqPdxVeeWpI:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L180)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

"already"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-07 18:37 UTC, nickbianco requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: all files reviewed, 10 unresolved discussions (waiting on @aymanhab)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 373 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_310dl0ao2NuF2CALs:-M_70wiW2lyBPXes95gV:brxp9sd) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L373)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Yes, just a trivial case, but will beef this up to compare against BodyKinematics output which computes similar quantities already.
</blockquote></details>

Sounds good!
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-M_71hYx2wNmxoDG61Jf:bdmntgc) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Unfortunately no, the Analyze method downstream is very strict requiring Controls that match model in size and sampling. I'd prefer not to weaken this requirement but this also opens the question of whether/how to enforce that dynamics can be evaluated to compute Accelerations
</blockquote></details>

Oh right. You could try creating an "empty" controls table with the same time vector as the states table and no columns. I think that might work and is easy to construct.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 4 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_31LlW8TiMZiGLj5XZ:-M_74OQb-KY28u4zwHap:b-yqb7ii) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L4)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

I'm pretty open, the rationale was using "Synthetic-IMU" as an abstraction that we can build upon (with attachment, noise-model, visualization, possibly saturation-limits etc.) and this Reporter reads the "data" off these Synthetic-IMUs. This makes it sensible to go back and generate data from existing simulations by attaching a synthetic-IMUs. I understand agreeing on a short but descriptive name is always a challenge. 
</blockquote></details>

I realize my original comment wasn't very clear. I think my main point was that since all these quantities are model generated, it's maybe redundant to have `synthetic` as part of the name. Maybe I'm overthinking this though.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_74km-5S2vJP_47d0l:bz9jx7) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

The competing needs here are: making easy things easy and making hard things possible, I felt this strikes a reasonable balance but open to counter arguments. 
</blockquote></details>

I'm was thinking that getting all frames in the model (or even just bodies) could be data overload. For my use cases, I would probably only use the `Custom` mode. But it could be good to get another perspective here.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 182 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3A1Po92pkVC_7BiDA:-M_72USUC9Q0tRyzTcwJ:bvaz77s) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L182)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Yes it's a copy since Analyses should be passive and not have side-effect on the model being analyzed. 
I debated this and the main reason I add them all is that in essence the IMU records all the data anyway internally but we only report what the user wants. You may have orientation errors dependent on angular_velocity but this is a bit hypothetical at the moment, so I'm open.
</blockquote></details>

That makes sense, I'm fine with how it is then.
___
*[OpenSim/Simulation/OpenSense/SyntheticIMU.h, line 46 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3EqiZ8-e61dTxgQUB:-M_75vrq5qeIBc4jFUnj:bk847xl) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Simulation/OpenSense/SyntheticIMU.h#L46)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

As of now it's computational only but sure can add visuals if needed.
</blockquote></details>

Just curious, how would this work? Can you modify the visual geometry of the frame through a Socket?
___
*[OpenSim/Simulation/OpenSense/SyntheticIMU.h, line 48 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3CQ8l4z1vl1uUbIf-:-M_72y9Y3L9JWu1KoJ_n:b-163hlf) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Simulation/OpenSense/SyntheticIMU.h#L48)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

so, what's the name of the socket? "the", what will it look like from inside the code of the IMU?
</blockquote></details>

Sorry, I didn't mean to suggest "the" should be the name haha. I think `frame` would be fine. I just want to be clear on what this frame represents.
___
*[OpenSim/Simulation/OpenSense/SyntheticIMU.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_327MaDbC9nvwN9TOo:-M_73laL6W9t1WNkg83U:bi36avt) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Simulation/OpenSense/SyntheticIMU.h#L68)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Very easy to add as outputs and that's where having an expert client of the class shines.
</blockquote></details>

Awesome, let's do it.


<!-- Sent from Reviewable.io -->

2021-05-08 20:47 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: 10 of 13 files reviewed, 10 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 4 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_31LlW8TiMZiGLj5XZ:-M_Cd9dI-F-HM6oCY1dz:b-7pck07) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L4)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I realize my original comment wasn't very clear. I think my main point was that since all these quantities are model generated, it's maybe redundant to have `synthetic` as part of the name. Maybe I'm overthinking this though.
</blockquote></details>

We can rename SyntheticIMU everywhere to IMU with the implicit assumption that it's synthetic or that it's our own model/abstraction of an IMU, not sure how confusing would that be to users but name will be shorter. We can add special visuals as our opensense examples have no IMU abstraction anyway just a frame with arbitrary attached orange brick.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_CdsKU0Sgnu0yEW1X8:b-rnr40p) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I'm was thinking that getting all frames in the model (or even just bodies) could be data overload. For my use cases, I would probably only use the `Custom` mode. But it could be good to get another perspective here.
</blockquote></details>

Would you prefer we make the default "Custom" so default does nothing? The reason I prefer not to throw now is that we don't validate before running and since Analyses are not components we don't have a hook to validate before the "begin" method is called, but I can try to find a workaround..
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 177 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_38so6AjloyPFBNkl8:-M_CeZxu9yCWnwuC_7-j:bikwj3l) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L177)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This might end up changing, but if there's an input error, I'd prefer it would through an Exception and not report anything.
</blockquote></details>

See comment above regarding throwing 
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 182 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3A1Po92pkVC_7BiDA:-M_CeecQ6Zd1TA_fPA3N:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L182)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

That makes sense, I'm fine with how it is then.
</blockquote></details>

Done.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.cpp, line 274 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3Ad76Dd_OtDSErazq:-M_CfAHR0yr2qoVfhfdo:bb6un1j) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.cpp#L274)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Similar to the above comment, `auto& rotationsTable = _orientationsReporter.getTable();` could be brought into this if-statement, and same for the velocities and accelerations.
</blockquote></details>

Done
___
*[OpenSim/Simulation/OpenSense/SyntheticIMU.h, line 46 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3EqiZ8-e61dTxgQUB:-M_CfEeP6L0h6mxcnN-k:bclvmim) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Simulation/OpenSense/SyntheticIMU.h#L46)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Just curious, how would this work? Can you modify the visual geometry of the frame through a Socket?
</blockquote></details>

No, we'll implement generateDecorations method and have it create geometry and position it based on the socket.
___
*[OpenSim/Simulation/OpenSense/SyntheticIMU.h, line 48 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3CQ8l4z1vl1uUbIf-:-M_Cip_z-5F8qOmaU0oN:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Simulation/OpenSense/SyntheticIMU.h#L48)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Sorry, I didn't mean to suggest "the" should be the name haha. I think `frame` would be fine. I just want to be clear on what this frame represents.
</blockquote></details>

Done.
___
*[OpenSim/Simulation/OpenSense/SyntheticIMU.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_327MaDbC9nvwN9TOo:-M_CivGk6gFujldS4aIy:bdcxv9f) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Simulation/OpenSense/SyntheticIMU.h#L68)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Awesome, let's do it.
</blockquote></details>

Coming up next!


<!-- Sent from Reviewable.io -->

2021-05-10 17:37 UTC, aymanhab commented
@carmichaelong and @antoinefalisse can you chime in on the naming discussion, thank you

2021-05-10 17:40 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: 7 of 13 files reviewed, 10 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 373 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_310dl0ao2NuF2CALs:-M_DPyeHAwE5VosVrwRE:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L373)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Sounds good!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-10 18:40 UTC, carmichaelong reviewed
Really cool to see all of this coming together so quickly. I left a some comments on naming and interface in replies.

> Reviewed 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-:-M_MZiRt4Di0iGcg-HgF:br8b8vf)* status: 9 of 13 files reviewed, 10 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 4 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_31LlW8TiMZiGLj5XZ:-M_MVBnI6QCppDHW4JxC:b4dczey) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L4)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

We can rename SyntheticIMU everywhere to IMU with the implicit assumption that it's synthetic or that it's our own model/abstraction of an IMU, not sure how confusing would that be to users but name will be shorter. We can add special visuals as our opensense examples have no IMU abstraction anyway just a frame with arbitrary attached orange brick.
</blockquote></details>

I think I'm still wrapping my head around all of the classes being added here, so definitely let me know if it seems like I'm missing some things here. A few thoughts:
- It sounds like the separate `SyntheticIMU` abstraction (vs just using `Frame`) is to add additional support for noise, visualization, etc down the road. This reporter seems to support bodies and frames too. What will happen if a user asks to add a noise model to a body or frame?
- I'm leaning towards dropping `Synthetic` in all the names, since it seems all model generated regardless, and still could be used to model an IMU that can be tracked by a real IMU with data.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_MR7x67RLLL3Yn2Tj6:b-dtlbun) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Thoughts? @carmichaelong 
</blockquote></details>

Not to complicate things with more ideas, but another way to go about this is to do what `BodyKinematics` does, which is to have one list, but optional keywords for including everything (`BodyKinematics` used `all`, and this could be `all_frames` and `all_bodies`). This would need only one list and still allow for easy access that users might be familiar with already.


<!-- Sent from Reviewable.io -->

2021-05-11 18:06 UTC, aymanhab commented
Ready for round 2 of reviews

2021-05-11 18:08 UTC, aymanhab commented
@nickbianco Any idea why ci on osx  fails here on moco related libraries as opposed to master branch while we use the same yml files? Thanks

2021-05-11 20:14 UTC, nickbianco requested changes
@aymanhab Second round of reviews are done. I'll take a look at the CI. I've had issues with Mac on other unrelated PRs recently, so this might be a separate problem.

> Reviewed 12 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-:-M_S2zIG4Dl6cP5WiDZU:b-gn1o0l)* status: all files reviewed, 9 unresolved discussions (waiting on @aymanhab and @carmichaelong)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-M_S0BPe7fJdpdvWovAK:b-yhwuxu) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

felt like too much to build into the test case when the function may be removed anyway.
</blockquote></details>

That makes sense. Even if we're not using that function, it would be good to check that the adjusted accelerations are being computed correctly in these tests.
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 373 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_RxkfL9Q5Wn-YetJdA:-M_RxkfL9Q5Wn-YetJdB:b-v6hu1) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/Applications/Analyze/test/testAnalyzeTool.cpp#L373)):*
> ```cpp
>     Joint& joint = pendulum.updJointSet()[0];
>     auto& qi = joint.updCoordinate();
>     qi.setValue(s, SimTK::Pi / 2.); // static
> ```

Could you add a comment here that the pendulum is the lowest-point hanging condition? (I accidentally resolved the previous thread).
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 396 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_RxtTx1ckf2yGFCIMh:-M_RxtTx1ckf2yGFCIMi:b-bwomf3) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/Applications/Analyze/test/testAnalyzeTool.cpp#L396)):*
> ```cpp
>     // Now allow pendulum to drop under gravity from horizontal
>     bodyKinematics->getPositionStorage()->purge();
>     qi.setValue(s, 0.); // Horisontal position
> ```

"Horizontal"
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 274 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-96C3_jtBrzNq0iL:-M_S-96C3_jtBrzNq0iM:b3da4mj) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Analyses/IMUDataReporter.cpp#L274)):*
> ```cpp
>             auto& angVelTable = _angularVelocityReporter.getTable();
>             STOFileAdapter_<SimTK::Vec3>::write(
>                     angVelTable, aBaseName + "_" + "angular_veolcity.sto");
> ```

"angular_velocity.sto"
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 4 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_31LlW8TiMZiGLj5XZ:-M_Ry_Oo4IMq-QnveXwz:b6ol83m) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L4)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

1. IMU is not a frame it's like a probe attached to a Frame to report what quantities would be reported by an IMU attached to this frame, possibly modifying quantities based on noise etc. not precluded by the design but not implemented either.
2. Agreed, removed it. 
</blockquote></details>

Sounds like we're converging here. I `IMUDataReporter` and `IMU` as the class names. 
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_S0THKDVuavOvivtc_:b5tsch5) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

The "all", "center_of_mass" choices in BodyKinematics were error prone hacks as far as I can tell (e.g. case sensitive, how about mixing "all" with additional Bodies? Body names are looked up in BodySet rather than iteration, will we support COM?).  May start as easier for users who used BodyKinematics but will end up building more hacks in new code when we can cleanup. It's a good point, leaning not to change but open to counter arguments
</blockquote></details>

My perspective here is that if users want kinematic information for all bodies/frames in the model, they should just use BodyKinematics. Similiar to OutputReporter, I envisioned users provide a specific list of paths (in this case, paths to model frames designated as IMUs) and only reported information specific to those paths. I don't think this type of implementation makes the reporter significantly harder/more time-consuming to use. In addition, similar to Carmichael's comment above, if we're adding options for IMU noise and visualization for Frames added to this reporter, I don't think we want an option to grab all Frames in the model.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 72 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-PhV7l9ZmI9QysfK:-M_S-PhV7l9ZmI9QysfL:b-kv0ahb) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L72)):*
> ```objc
>         return get_frame().getLinearAccelerationInGround(s);
>     }
>     SimTK::Vec3 calcLocalLinearAccelerationNoGravity(
> ```

Why not just do these calculations in `calcLinearAcceleration()`, since users could get the regular linear accelerations from the `Frame`? Either way, we'd need to make sure the `IMUDataReporter` is reporting the expected accelerations in the linear accelerations table.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 80 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S2L01Dt0bwqZKNTMS:-M_S2L020Udz2K6iiy-q:bx189iw) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L80)):*
> ```objc
>                 s, calcLinearAcceleration(s) - gravity, get_frame());
>     }
>     void generateDecorations(bool fixed, const ModelDisplayHints& hints,
> ```

Great! I hadn't thought of using generateDecorations like this before.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 88 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S2Sc5A3O1uEl2-AZF:-M_S2Sc5A3O1uEl2-AZG:b-xzhaiu) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L88)):*
> ```objc
>         // @TODO default color, size, shape should be obtained from hints
>         const OpenSim::PhysicalFrame& physFrame = this->get_frame();
>        appendToThis.push_back(
> ```

Needs indent.
___
*[OpenSim/Simulation/OpenSense/SyntheticIMU.h, line 4 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_3B-M-Cj2MTS73_cUa:-M_S-0-p88QkZPrkesng:b-gqiaup) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Simulation/OpenSense/SyntheticIMU.h#L4)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

If users have IMUs in place they can use regular output reporter.
</blockquote></details>

Ah right, sounds good. 


<!-- Sent from Reviewable.io -->

2021-05-11 22:31 UTC, nickbianco requested changes
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: all files reviewed, 10 unresolved discussions (waiting on @aymanhab and @carmichaelong)

___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 290 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_SY6j0E9hcOCzXxFlv:-M_SY6j12QGapmQnsFBw:bxq3qx4) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Analyses/IMUDataReporter.cpp#L290)):*
> ```cpp
>     ComponentList <T> frameComponents =
>             _modelLocal->getComponentList<T>();
>     // Add SyntheticIMUs to the model if needed
> ```

"SyntheticIMUs" --> "IMUs"


<!-- Sent from Reviewable.io -->

2021-05-14 17:18 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: 9 of 15 files reviewed, 10 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 373 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_RxkfL9Q5Wn-YetJdA:-M_freBw4hMb43u5fXj3:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/Applications/Analyze/test/testAnalyzeTool.cpp#L373)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Could you add a comment here that the pendulum is the lowest-point hanging condition? (I accidentally resolved the previous thread).
</blockquote></details>

Done.
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 396 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_RxtTx1ckf2yGFCIMh:-M_frfyj1awy291H3QcF:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/Applications/Analyze/test/testAnalyzeTool.cpp#L396)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

"Horizontal"
</blockquote></details>

Done.
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 274 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-96C3_jtBrzNq0iL:-M_frwxbAV3VCrtDIoKF:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Analyses/IMUDataReporter.cpp#L274)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

"angular_velocity.sto"
</blockquote></details>

Done.
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 290 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_SY6j0E9hcOCzXxFlv:-M_fryeaAlDlGU3rYHAv:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Analyses/IMUDataReporter.cpp#L290)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

"SyntheticIMUs" --> "IMUs"
</blockquote></details>

Done.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 4 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_31LlW8TiMZiGLj5XZ:-M_frmQQE7dGdD4sHrBK:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L4)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Sounds like we're converging here. I `IMUDataReporter` and `IMU` as the class names. 
</blockquote></details>

Done.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 72 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-PhV7l9ZmI9QysfK:-M_fs4g9-MLPZ2_G5ChG:b-pt5eyl) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L72)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Why not just do these calculations in `calcLinearAcceleration()`, since users could get the regular linear accelerations from the `Frame`? Either way, we'd need to make sure the `IMUDataReporter` is reporting the expected accelerations in the linear accelerations table.
</blockquote></details>

We can do it there but having similarly named functions return different results would be confusing, we can remove the linear_acceleration output/function altogether if you believe it is unnecessary.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 80 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S2L01Dt0bwqZKNTMS:-M_fsTfL2zcZHS4WMLIb:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L80)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Great! I hadn't thought of using generateDecorations like this before.
</blockquote></details>

Done.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 88 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S2Sc5A3O1uEl2-AZF:-M_fs_pR5vAi2tE4PjcA:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L88)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Needs indent.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-14 17:49 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: 9 of 15 files reviewed, 10 unresolved discussions (waiting on @carmichaelong and @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-M_fy7-3DGIYLps11aq0:b6fxkox) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

That makes sense. Even if we're not using that function, it would be good to check that the adjusted accelerations are being computed correctly in these tests.
</blockquote></details>

@nickbianco Can you point me to what utilities you have to create the empty controls table so we can compare results? Thank you
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_fyPQX1k-SdapgpwKa:bd0rxlx) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

My perspective here is that if users want kinematic information for all bodies/frames in the model, they should just use BodyKinematics. Similiar to OutputReporter, I envisioned users provide a specific list of paths (in this case, paths to model frames designated as IMUs) and only reported information specific to those paths. I don't think this type of implementation makes the reporter significantly harder/more time-consuming to use. In addition, similar to Carmichael's comment above, if we're adding options for IMU noise and visualization for Frames added to this reporter, I don't think we want an option to grab all Frames in the model.
</blockquote></details>

@nickbianco @carmichaelong I ended up using one property only and it is a list of Frames as you guys suggested. The reserved/keywords are:
- IMUs (use existing IMUs)
- Bodies (attach IMUs to all Bodies in Model)
- explicit list of Frames
The first option serves the case where IMUs were added separately, for example programmatically as envisioned by @nickbianco using provided OpenSenseUtilities::addSelectModelIMUs() function, while the latter 2 are for post-hoc generation of IMUData from legacy simulations which is likely the more common use case to start and that fits with existing GUI tools.


<!-- Sent from Reviewable.io -->

2021-05-14 18:25 UTC, nickbianco requested changes
Thanks for the great updates @aymanhab. The utility is great, but I think we can simplify this even further (as long as everything will work in the GUI). I left a handful of comments on my thoughts.

> Reviewed 6 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-:-M_g6pClEpCPpsUwsRkj:b-yqssq2)* status: all files reviewed, 6 unresolved discussions (waiting on @aymanhab and @carmichaelong)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-M_g0PvR0JtSfdCYn71r:bkcvrrj) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

@nickbianco Can you point me to what utilities you have to create the empty controls table so we can compare results? Thank you
</blockquote></details>

You can just do this:
```
TimeSeriesTable emptyControls(statesTable.getIndependentColumn());
```
___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 81 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g1kO9CrPXXp8QXC9K:-M_g1kOA2Yc9JDIFwnXE:b-9tyskg) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L81)):*
> ```objc
>     /// Add IMUs to passed in model and return references to them
>     /// based on paths specification. Some special cases:
>     /// - "IMUs" no new IMUs are added to model, existing IMUs are selected.
> ```

I'm not sure if this option is necessary. I think this utility should only add IMUs to the frame paths specified. This seems to be here only for the IMUDataReporter class, but I think some changes could be made to the reporter so this option could be removed.
___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 83 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g36x9CbEohPj0qWxf:-M_g36x9CbEohPj0qWxg:b-bpy971) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L83)):*
> ```objc
>     /// - "IMUs" no new IMUs are added to model, existing IMUs are selected.
>     /// - "Bodies" one new IMU with the name "{Body}_imu" is added per Body 
>     ///     and returned in result.
> ```

I'm still not sure how I feel about selecting all the bodies in the model.  I think I'd prefer just specifying the frame paths for a specific set of frames. This would also fix another issue I have, where the `paths` argument is being used for two different inputs (frame paths and flags for the IMU and Bodies cases). 
___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 86 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g6QrM7fUhYvDv__6u:-M_g6QrM7fUhYvDv__6v:b-7bj4kl) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L86)):*
> ```objc
>     /// - If "paths" refer to user specified list of frames, then one new 
>     ///     "{Frame}_imu" is added to the model and returned in result.
>     static std::vector<OpenSim::IMU*> addSelectModelIMUs(
> ```

I think the name for this could be even simpler, e.g. `addModelIMUs`. 
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_g3syNAwjDHl5gjPev:brabn7x) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

@nickbianco @carmichaelong I ended up using one property only and it is a list of Frames as you guys suggested. The reserved/keywords are:
- IMUs (use existing IMUs)
- Bodies (attach IMUs to all Bodies in Model)
- explicit list of Frames
The first option serves the case where IMUs were added separately, for example programmatically as envisioned by @nickbianco using provided OpenSenseUtilities::addSelectModelIMUs() function, while the latter 2 are for post-hoc generation of IMUData from legacy simulations which is likely the more common use case to start and that fits with existing GUI tools.


</blockquote></details>

It's great to have the utility now, but this seems somewhat similar to the previous implementation. If we have the utility to add IMUs to the model, why not just use that to add a specific set of IMU objects to the model, and then let the IMUDataReporter automatically grab all IMUs in the model and report the outputs? Then we wouldn't even need the frame_paths property. Even if you're working with legacy data, you can still load the model and add the IMUs before running the reporter. Unless there's something about compatibility with the GUI that I'm missing here?

Even if we do keep the `frame_paths` property, I don't like that it's currently used to pass two different types of arguments: either a list of frames or a flag for a specific use case. But if we just automatically detect IMU objects then this problem gets resolved.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 72 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-PhV7l9ZmI9QysfK:-M_g61oG4TN4slRFXV3-:b-3j6v9d) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L72)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

We can do it there but having similarly named functions return different results would be confusing, we can remove the linear_acceleration output/function altogether if you believe it is unnecessary.
</blockquote></details>

I think we could just have one `calcLinearAcceleration()` function that's associated with one `linear_acceleration` output, and these accelerations would include the gravity offset and body re-expression.


<!-- Sent from Reviewable.io -->

2021-05-14 18:56 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: all files reviewed, 6 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 81 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g1kO9CrPXXp8QXC9K:-M_gCawz80a1x4zetORn:beuzkow) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L81)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I'm not sure if this option is necessary. I think this utility should only add IMUs to the frame paths specified. This seems to be here only for the IMUDataReporter class, but I think some changes could be made to the reporter so this option could be removed.
</blockquote></details>

I agree it would be clearer mentally to do Add separately from Selection, but with this still work-in-progress due to earlier discussion I wanted to separate this into one utility. Will separate once we finalize other decisions.
___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 83 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g36x9CbEohPj0qWxf:-M_gDmu6ElIEkUp7ICG3:b-qthwxi) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L83)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I'm still not sure how I feel about selecting all the bodies in the model.  I think I'd prefer just specifying the frame paths for a specific set of frames. This would also fix another issue I have, where the `paths` argument is being used for two different inputs (frame paths and flags for the IMU and Bodies cases). 
</blockquote></details>

See my comments above. You're thinking walking models with tens of Bodies, I'm thinking educational/testing/simple models that users create to understand/explore functionality (easy-things easy).
___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 86 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g6QrM7fUhYvDv__6u:-M_gE8YMAocR49DaXGP9:b5aii7a) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L86)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I think the name for this could be even simpler, e.g. `addModelIMUs`. 
</blockquote></details>

Yes, if we remove the Selection part as discussed above, then a rename is appropriate.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_gA6y_C_NCGsYnGejH:b-ntsi9q) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

It's great to have the utility now, but this seems somewhat similar to the previous implementation. If we have the utility to add IMUs to the model, why not just use that to add a specific set of IMU objects to the model, and then let the IMUDataReporter automatically grab all IMUs in the model and report the outputs? Then we wouldn't even need the frame_paths property. Even if you're working with legacy data, you can still load the model and add the IMUs before running the reporter. Unless there's something about compatibility with the GUI that I'm missing here?

Even if we do keep the `frame_paths` property, I don't like that it's currently used to pass two different types of arguments: either a list of frames or a flag for a specific use case. But if we just automatically detect IMU objects then this problem gets resolved.
</blockquote></details>

@nickbianco The workflow I'm trying to support and you may not consider important for your use case is that of a GUI user with legacy simulation results. This user would now be able to generate simulated IMU data entirely from the GUI by running an Analysis/Reporter that doesn't modify the Model. You can do the same by adding IMUs programmatically and then wire tens of outputs to an OutputReporter, but not with point and click or providing extra utilities. I thought we agreed to combine the two properties which is what I did but maybe I missed something or the name is now more confusing (which was my original reason for keeping 2 separate properties).
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 72 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-PhV7l9ZmI9QysfK:-M_gBm_6D5uoQKDs11MX:b-fnlpeh) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L72)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I think we could just have one `calcLinearAcceleration()` function that's associated with one `linear_acceleration` output, and these accelerations would include the gravity offset and body re-expression.
</blockquote></details>

Isn't that having same function/output report different quantities. Do you find this less confusing? You're the ultimate user, so I'd like to hear your thoughts. @carmichaelong feel free to chime in.


<!-- Sent from Reviewable.io -->

2021-05-14 21:03 UTC, nickbianco requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: all files reviewed, 5 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 83 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g36x9CbEohPj0qWxf:-M_gfV9N6HFaieuzHmhy:b-dqicb5) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L83)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

See my comments above. You're thinking walking models with tens of Bodies, I'm thinking educational/testing/simple models that users create to understand/explore functionality (easy-things easy).
</blockquote></details>

I think I would prefer adding in the extra step, even for simple models, to keep the interface consistent across all use cases. Especially since the input is just a list of frames, which isn't too burdensome. For the TGCS example, I will be specifying the exact frames to add IMUs to even though the model is only 3 degrees-of-freedom.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_gVsyd5TvfA-15tfIb:bkbqyot) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

@nickbianco The workflow I'm trying to support and you may not consider important for your use case is that of a GUI user with legacy simulation results. This user would now be able to generate simulated IMU data entirely from the GUI by running an Analysis/Reporter that doesn't modify the Model. You can do the same by adding IMUs programmatically and then wire tens of outputs to an OutputReporter, but not with point and click or providing extra utilities. I thought we agreed to combine the two properties which is what I did but maybe I missed something or the name is now more confusing (which was my original reason for keeping 2 separate properties).
</blockquote></details>

I guess I'm wondering if it's possible to modify the Model within the GUI can be modified using the utility before passing it to the IMUDataReporter. So the GUI tool would need to wrap both the Model update and the calls the data reporter. Then both the utility and IMUDataReporter can be kept clean and separate.

Regarding the properties, it was my impression that we weren't combining the properties, but removing the first one since the only input would the list of`frame_paths`. Now with the utility, the `frame_paths` could become `imu_paths` to point to existing IMU objects in the model, or we just have no property and report all the IMU objects.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 72 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-PhV7l9ZmI9QysfK:-M_geghDAM7fPJlNsp2v:b-6x03j6) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L72)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Isn't that having same function/output report different quantities. Do you find this less confusing? You're the ultimate user, so I'd like to hear your thoughts. @carmichaelong feel free to chime in.
</blockquote></details>

Do you mean compared to the output of `Frame`s `calcLinearAcceleration()`? I suppose it would be confusing for the IMU `calcLinearAcceleration()` to compute something different. What about replacing `calcAngularVelocity()` and `calcLinearAcceleration()` with `calcGyroscopeSignal()` and `calcAccelerometerSignal()`? That way we can make modifications to the outputs of `Frame` and not having any confusion.


<!-- Sent from Reviewable.io -->

2021-05-14 21:31 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: all files reviewed, 5 unresolved discussions (waiting on @carmichaelong and @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-M_giDkJDfvw3hP10L1E:bz5e2gt) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

You can just do this:
```
TimeSeriesTable emptyControls(statesTable.getIndependentColumn());
```
</blockquote></details>

Thanks but that didn't work because controls are actually evaluated and applied to compute forces when realizing Dynamics, that's more fundamental issue to resolve since The forces and accelerations will change depending on Controls. It's a big issue because Outputs depend on state only. How are controls accessed?  BodyKinematics accelerations would be different from what your utility reports I think.
___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 83 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g36x9CbEohPj0qWxf:-M_gmEyj1NyvaPn5wrgE:by4tbrt) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L83)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I think I would prefer adding in the extra step, even for simple models, to keep the interface consistent across all use cases. Especially since the input is just a list of frames, which isn't too burdensome. For the TGCS example, I will be specifying the exact frames to add IMUs to even though the model is only 3 degrees-of-freedom.
</blockquote></details>

Again, you're totally capable developer, experts can do the same but adding steps is not always feasible for our non-expert users.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_gjEvy7mVaEXbgrGhC:bclz66c) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I guess I'm wondering if it's possible to modify the Model within the GUI can be modified using the utility before passing it to the IMUDataReporter. So the GUI tool would need to wrap both the Model update and the calls the data reporter. Then both the utility and IMUDataReporter can be kept clean and separate.

Regarding the properties, it was my impression that we weren't combining the properties, but removing the first one since the only input would the list of`frame_paths`. Now with the utility, the `frame_paths` could become `imu_paths` to point to existing IMU objects in the model, or we just have no property and report all the IMU objects.
</blockquote></details>

I now understand. Unfortunately, providing GUI tools to support this custom workflow would be an overkill. I totally support keeping the tools as clean as possible but that's the tradeoff. The cases where we modify Models before running tools have been quite hard to maintain for the long term, so I'd avoid it if at all possible. If we split the utility to add IMUs then you can still do all you want cleanly by specifying IMUs, with no overhead. 
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 72 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-PhV7l9ZmI9QysfK:-M_gltuh0jLfONfn9T3m:b-vmb5lg) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L72)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Do you mean compared to the output of `Frame`s `calcLinearAcceleration()`? I suppose it would be confusing for the IMU `calcLinearAcceleration()` to compute something different. What about replacing `calcAngularVelocity()` and `calcLinearAcceleration()` with `calcGyroscopeSignal()` and `calcAccelerometerSignal()`? That way we can make modifications to the outputs of `Frame` and not having any confusion.
</blockquote></details>

Perfect, I love these new names :+1:  @carmichaelong please let us know what you think.


<!-- Sent from Reviewable.io -->

2021-05-17 18:51 UTC, nickbianco requested changes
> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: all files reviewed, 8 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-M_vUAq3Ave2ESJRzsKO:b-7npxpl) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Thanks but that didn't work because controls are actually evaluated and applied to compute forces when realizing Dynamics, that's more fundamental issue to resolve since The forces and accelerations will change depending on Controls. It's a big issue because Outputs depend on state only. How are controls accessed?  BodyKinematics accelerations would be different from what your utility reports I think.
</blockquote></details>

What do you mean by "how are controls accessed"? Outputs depend on state only but the Dynamics and Acceleration stages will always apply whatever controls exist in the Model. Does BodyKinematics compute accelerations by taking derivatives? I guess I wouldn't expect the accelerations to match since BodyKinematics is just that -- kinematics. 

For now, you can add zero controls to the controls table for the two coordinate actuators in the pendulum model and it should work:

```
TimeSeriesTable controlsTable(statesTable.getIndependentColumn());
Vector zeroControl(controlsTable.getNumRows(), 0.0));
controlsTable.appendColumn("/forceset/tau0", zeroControl);
controlsTable.appendColumn("/forceset/tau1", zeroControl);
```
___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 83 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g36x9CbEohPj0qWxf:-M_vdPrUE3gI7YgPGOD-:b2cyzy) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L83)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Again, you're totally capable developer, experts can do the same but adding steps is not always feasible for our non-expert users.
</blockquote></details>

Okay, if we're going to keep these convenience options, then there should be two separate arguments: one for the "mode" and one for the paths. Or, the paths argument could be optional and if no frame paths are specified by default the body frames are used for IMUs.
___
*[OpenSim/Analyses/IMUDataReporter.h, line 60 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vbo9m7PXPCVooeDWl:-M_vbo9m7PXPCVooeDWm:bciqvxc) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Analyses/IMUDataReporter.h#L60)):*
> ```objc
>     OpenSim_DECLARE_PROPERTY(report_orientations, bool,
>             "Report orientation of IMU as quaternion, default is true.");
>     OpenSim_DECLARE_PROPERTY(report_angular_velocities, bool,
> ```

This will need to be renamed to match the new output name (same for linear accelerations).
___
*[OpenSim/Analyses/IMUDataReporter.h, line 97 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vbNXKBbXtwD7b_JbO:-M_vbNXKBbXtwD7b_JbP:b-ezbhsr) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Analyses/IMUDataReporter.h#L97)):*
> ```objc
>     }
>     // In memory access to IMU data as Tables Angular Velocities)
>     const TimeSeriesTable_<SimTK::Vec3>& getAngularVelocitiesTable() const {
> ```

This will need to be renamed to match the new output name (same for the acceleration table).
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-M_vYTAq1iKntvBdBN-b:brlkvgi) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

I now understand. Unfortunately, providing GUI tools to support this custom workflow would be an overkill. I totally support keeping the tools as clean as possible but that's the tradeoff. The cases where we modify Models before running tools have been quite hard to maintain for the long term, so I'd avoid it if at all possible. If we split the utility to add IMUs then you can still do all you want cleanly by specifying IMUs, with no overhead. 
</blockquote></details>

I see. Well in that case we'll need to support both 1) detecting existing IMU objects and 2) adding IMU objects based on the frames paths listed in the property.  I think then the property name here could be more specific, something like `additional_imu_frame_paths` or something similar.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 72 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-PhV7l9ZmI9QysfK:-M_vRD8S2x9E3ETqrWsH:b-7zejdy) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L72)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Perfect, I love these new names :+1:  @carmichaelong please let us know what you think.
</blockquote></details>

Looks great! I think now we can remove the `calcLinearAcceleration()` method so that all the outputs are IMU-centric.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 55 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vRSb09OGzVLkX-Y_E:-M_vRSb09OGzVLkX-Y_F:b-fz2lmb) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Simulation/OpenSense/IMU.h#L55)):*
> ```objc
>     OpenSim_DECLARE_OUTPUT(gyro_signal, SimTK::Vec3,
>             calcGyroscopeSignal, SimTK::Stage::Velocity);
>     OpenSim_DECLARE_OUTPUT(accel_signal, SimTK::Vec3,
> ```

Could you make these outputs using full words, i.e. `gyroscope_signal` and `accelerometer_signal`.


<!-- Sent from Reviewable.io -->

2021-05-18 00:11 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: 9 of 15 files reviewed, 8 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-M_wh-HEC9rErIYpWVmz:b1yrz69) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

What do you mean by "how are controls accessed"? Outputs depend on state only but the Dynamics and Acceleration stages will always apply whatever controls exist in the Model. Does BodyKinematics compute accelerations by taking derivatives? I guess I wouldn't expect the accelerations to match since BodyKinematics is just that -- kinematics. 

For now, you can add zero controls to the controls table for the two coordinate actuators in the pendulum model and it should work:

```
TimeSeriesTable controlsTable(statesTable.getIndependentColumn());
Vector zeroControl(controlsTable.getNumRows(), 0.0));
controlsTable.appendColumn("/forceset/tau0", zeroControl);
controlsTable.appendColumn("/forceset/tau1", zeroControl);
```
</blockquote></details>

BodyKinematics also realizes Acceleration as such the results should be same as this reporter. Just not the same as when we pass in different controls to your utility function.
___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 81 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g1kO9CrPXXp8QXC9K:-M_wkyRG9TGBVyVR3Jmj:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L81)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

I agree it would be clearer mentally to do Add separately from Selection, but with this still work-in-progress due to earlier discussion I wanted to separate this into one utility. Will separate once we finalize other decisions.
</blockquote></details>

Done.
___
*[OpenSim/Analyses/IMUDataReporter.h, line 60 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vbo9m7PXPCVooeDWl:-M_wj7RhDEUowY7gUG5h:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Analyses/IMUDataReporter.h#L60)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This will need to be renamed to match the new output name (same for linear accelerations).
</blockquote></details>

Done.
___
*[OpenSim/Analyses/IMUDataReporter.h, line 97 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vbNXKBbXtwD7b_JbO:-M_wjKfE4bUiwXbT2xjO:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Analyses/IMUDataReporter.h#L97)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This will need to be renamed to match the new output name (same for the acceleration table).
</blockquote></details>

Done.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 72 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-PhV7l9ZmI9QysfK:-M_wjW_b5wLFsO_NckGi:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L72)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Looks great! I think now we can remove the `calcLinearAcceleration()` method so that all the outputs are IMU-centric.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-18 17:34 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: 9 of 15 files reviewed, 8 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-Ma-X_mZ15vI7bAZ-Nhz:b-wua92w) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

BodyKinematics also realizes Acceleration as such the results should be same as this reporter. Just not the same as when we pass in different controls to your utility function.
</blockquote></details>

Added comparison to utility which produces identical results
___
*[OpenSim/Analyses/IMUDataReporter.h, line 97 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vbNXKBbXtwD7b_JbO:-Ma-XK-F0h0I_OfyqUA_:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Analyses/IMUDataReporter.h#L97)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-Ma-WI1R3R0OL2QqvNgV:b-4ta4qs) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I see. Well in that case we'll need to support both 1) detecting existing IMU objects and 2) adding IMU objects based on the frames paths listed in the property.  I think then the property name here could be more specific, something like `additional_imu_frame_paths` or something similar.
</blockquote></details>

additional seems a bit "additional" ;) and imu_frames is confusing since these are not imu_frames but rather frames to which we connect imus  so I lean to leave frame_paths  but we can revisit if everything else is settled.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 72 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_S-PhV7l9ZmI9QysfK:-Ma-XOZkDj8qH1SS3AQm:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b5840cbebb14e431ff38c3f7512fbe49fdd09f05/OpenSim/Simulation/OpenSense/IMU.h#L72)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 55 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vRSb09OGzVLkX-Y_E:-Ma-XNRd4Q-aQPYE_KI8:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Simulation/OpenSense/IMU.h#L55)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Could you make these outputs using full words, i.e. `gyroscope_signal` and `accelerometer_signal`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-18 21:02 UTC, aymanhab commented
I believe all comments/feedback from last view has been addressed and test case beefed up. Thanks for the great feedback @nickbianco and @carmichaelong Getting  very close.

2021-05-18 21:02 UTC, aymanhab commented
Now working on the bindings to make sure ew methods are available in python/java/matlab

2021-05-19 20:08 UTC, nickbianco requested changes
Thanks for the updates @aymanhab. Agreed, it's getting very close. I have a handful of new comments (mostly clarifying previous thoughts).

> Reviewed 5 of 6 files at r11.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-:-Ma5EIz6AfYBP52tlogH:byorj93)* status: 14 of 15 files reviewed, 10 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-Ma59avF1qc0qIyX9FGU:b-lamgag) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Added comparison to utility which produces identical results
</blockquote></details>

Great! Are you thinking we keep the `createSyntheticIMUAccelerationSignals()` utility for now? Can't hurt I guess.
___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.cpp, line 277 at r11](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-Ma5DOaz68q9utWTCWz2:-Ma5DOaz68q9utWTCWz3:bs6oqil) ([raw file](https://github.com/opensim-org/opensim-core/blob/028e3972675a1e6a425f6d3c39e03b0c060eee8d/OpenSim/Simulation/OpenSense/OpenSenseUtilities.cpp#L277)):*
> ```cpp
> 
>     std::vector<OpenSim::IMU*> selectedIMUs;
>     if (paths.size() == 1 && paths[0] == "Bodies") {
> ```

Again, if we're keeping the convenience option to add IMUs to all bodies, there should be a separate argument for it. It's confusing to me to use the paths argument for the paths and this keyword. The other option (which I suggested in a previous comment) is to make the `paths` argument optional (i.e., make it an empty vector by default) and if paths are provided, grab all the bodies in the model.
___
*[OpenSim/Analyses/IMUDataReporter.h, line 60 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vbo9m7PXPCVooeDWl:-Ma58yhzC3mOuarXZz73:brmszp6) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Analyses/IMUDataReporter.h#L60)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could we use full words for these properties as well, i.e. `report_gyroscope_signals` and `report_accelerometer_signals`?
___
*[OpenSim/Analyses/IMUDataReporter.h, line 97 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vbNXKBbXtwD7b_JbO:-Ma59CU4-v_-rGXIccCv:b-p1u4e) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Analyses/IMUDataReporter.h#L97)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same as my comment above, can we use full words for these methods, i.e. `getGyroscopeSignalsTable()` and `getAccelerometerSignalsTable()`?
___
*[OpenSim/Analyses/IMUDataReporter.h, line 68 at r11](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-Ma5E3V4C8u18UbqnDqY:-Ma5E3V4C8u18UbqnDqZ:b-lypma0) ([raw file](https://github.com/opensim-org/opensim-core/blob/028e3972675a1e6a425f6d3c39e03b0c060eee8d/OpenSim/Analyses/IMUDataReporter.h#L68)):*
> ```objc
>             "ComponentPaths for frames to attach IMUs to, if 'IMUs' then the model "
>             "is assumed to have IMUs attached already otherwise IMUs are temporarily"
>             "added as needed to the specified frame_paths.");
> ```

As I comment in the cpp file, this doesn't need to be either/or. You could both detected existing IMU objects and append new IMU objects based on the frame_paths argument.
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 156 at r11](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-Ma5C5pS4cT08PS1jLJ_:-Ma5C5pS4cT08PS1jLJa:b-jkb41u) ([raw file](https://github.com/opensim-org/opensim-core/blob/028e3972675a1e6a425f6d3c39e03b0c060eee8d/OpenSim/Analyses/IMUDataReporter.cpp#L156)):*
> ```cpp
>             _modelLocal.reset(_model->clone());
>             std::vector<std::string> paths_string{get_frame_paths(0)};
>             if (paths_string[0] == "IMUs") {
> ```

I still don't think we should use the `frame_paths` property for additional arguments like this. It should only contain paths to frames for which we're adding IMUs to.
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 158 at r11](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-Ma5CiikARYQJhvMaJbH:-Ma5CiikARYQJhvMaJbI:b-nb5jxp) ([raw file](https://github.com/opensim-org/opensim-core/blob/028e3972675a1e6a425f6d3c39e03b0c060eee8d/OpenSim/Analyses/IMUDataReporter.cpp#L158)):*
> ```cpp
>             if (paths_string[0] == "IMUs") {
>                 auto compList = _model->getComponentList<const OpenSim::IMU>();
>                 for (auto imu : compList) { _imuComponents.push_back(&imu); }
> ```

Here you could remove the if-statement and keep these two lines. Then, if any frames paths are provided, add those IMUs to the model and append the new IMUs to the `_imuComponents` list.
___
*[OpenSim/Analyses/SyntheticIMUDataReporter.h, line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_34bbb2Om7mCgYMeSd:-Ma5Dt0_4U_KHGtIQqto:b-ashnhx) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/OpenSim/Analyses/SyntheticIMUDataReporter.h#L68)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

additional seems a bit "additional" ;) and imu_frames is confusing since these are not imu_frames but rather frames to which we connect imus  so I lean to leave frame_paths  but we can revisit if everything else is settled.
</blockquote></details>

That's reasonable, I think `frame_paths` is fine, as long as the behavior of the property is well documented. 
___
*[OpenSim/Simulation/OpenSense/IMU.h, line 55 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vRSb09OGzVLkX-Y_E:-Ma5A2LwE_91y4Zdiiz7:bk6l431) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Simulation/OpenSense/IMU.h#L55)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Awesome, thanks! I have similar comments for the properties and methods of IMUDataReporter.


<!-- Sent from Reviewable.io -->

2021-05-20 16:48 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: 14 of 15 files reviewed, 10 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_30vzl5_BYcVkO5Jcn:-Ma9Q8V2BSj4mPsWTqPM:b-a1waq3) ([raw file](https://github.com/opensim-org/opensim-core/blob/d3541abb58a527549c25591ee41f1e307c2fb817/Applications/Analyze/test/testAnalyzeTool.cpp#L402)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Great! Are you thinking we keep the `createSyntheticIMUAccelerationSignals()` utility for now? Can't hurt I guess.
</blockquote></details>

Yes, will keep for the short term.
___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 83 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g36x9CbEohPj0qWxf:-Ma9d6g_2aOgXRdHwrS1:b-3wo45h) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L83)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Okay, if we're going to keep these convenience options, then there should be two separate arguments: one for the "mode" and one for the paths. Or, the paths argument could be optional and if no frame paths are specified by default the body frames are used for IMUs.
</blockquote></details>

Thanks for the feedback @nickbianco so there're  two suggestions from you that we better iron out before I implement for the final revision. 
1. Have a mode property (IMU, Body, Frame, None) 
2. Have frame_list property with specific Frame paths
Alternatively, 
1. Not using a mode property altogether, have it implicit, 
2.  Have one property "additional_frame_list" 
with the behavior that IMUs are always included if on the model, and additional imus are attached to frames from additional_frame_list.

The second suggestion makes it harder though still possible to report all Bodies or all Frames but more concise XML

Your thinking on this may have evolved to prefer one over the other so let me know your final choice. 
@carmichaelong sorry to pull you in this ongoing discussion but this is more conceptual so a user perspective may be helpful. Thank you
___
*[OpenSim/Analyses/IMUDataReporter.h, line 60 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vbo9m7PXPCVooeDWl:-Ma9R8Al-0_tbzRFYYZG:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Analyses/IMUDataReporter.h#L60)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Could we use full words for these properties as well, i.e. `report_gyroscope_signals` and `report_accelerometer_signals`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-20 18:25 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: 10 of 15 files reviewed, 10 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[OpenSim/Analyses/IMUDataReporter.h, line 60 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vbo9m7PXPCVooeDWl:-MaA00x65agrBesq05mM:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Analyses/IMUDataReporter.h#L60)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[OpenSim/Analyses/IMUDataReporter.h, line 97 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_vbNXKBbXtwD7b_JbO:-MaA0-I24F30TutTtm0K:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c68497dc369c676687bc61c55152168fd49b5503/OpenSim/Analyses/IMUDataReporter.h#L97)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Same as my comment above, can we use full words for these methods, i.e. `getGyroscopeSignalsTable()` and `getAccelerometerSignalsTable()`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-20 21:20 UTC, nickbianco requested changes
> Reviewed 3 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: 10 of 15 files reviewed, 7 unresolved discussions (waiting on @aymanhab, @carmichaelong, and @nickbianco)

___
*[OpenSim/Simulation/OpenSense/OpenSenseUtilities.h, line 83 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-M_g36x9CbEohPj0qWxf:-MaAHIC96A61MibtqblT:bhxt2vy) ([raw file](https://github.com/opensim-org/opensim-core/blob/a1ce75f5510e1d80017d7d5e372ceab24b055479/OpenSim/Simulation/OpenSense/OpenSenseUtilities.h#L83)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Thanks for the feedback @nickbianco so there're  two suggestions from you that we better iron out before I implement for the final revision. 
1. Have a mode property (IMU, Body, Frame, None) 
2. Have frame_list property with specific Frame paths
Alternatively, 
1. Not using a mode property altogether, have it implicit, 
2.  Have one property "additional_frame_list" 
with the behavior that IMUs are always included if on the model, and additional imus are attached to frames from additional_frame_list.

The second suggestion makes it harder though still possible to report all Bodies or all Frames but more concise XML

Your thinking on this may have evolved to prefer one over the other so let me know your final choice. 
@carmichaelong sorry to pull you in this ongoing discussion but this is more conceptual so a user perspective may be helpful. Thank you

</blockquote></details>

For the utility here, I think just having the `paths` argument could make sense. Like I suggested, the default behavior if there's no paths provided could be to add IMUs for all the bodies. I'm not sure if XML is a huge concern here since the utility will primarily be used in scripting and by the IMUDataReporter.

For the IMUDataReporter, I imagine most users will access it through the GUI. Could there not be a "all bodies" option in the GUI that would then pass an empty `paths` argument to the utility? Similarly, the GUI could have fields for specific frames to add IMUs to.


<!-- Sent from Reviewable.io -->

2021-05-20 21:51 UTC, nickbianco requested changes
Thanks @aymanhab, looking great! Just a few final comments.

> Reviewed 5 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-:-MaAja5y19AQUwM0rmHe:b-40ayn9)* status: all files reviewed, 4 unresolved discussions (waiting on @aymanhab)

___
*[OpenSim/Analyses/IMUDataReporter.h, line 49 at r13](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-MaAj1sgBOgGl1kzB7Yt:-MaAj1sgBOgGl1kzB7Yu:bu9lviz) ([raw file](https://github.com/opensim-org/opensim-core/blob/3f1654a107336c0b5485d360dda54b0a1592ee5e/OpenSim/Analyses/IMUDataReporter.h#L49)):*
> ```objc
> /**
>  * A class for recording the readings off an IMU placed on a model
>  * during a simulation.
> ```

A few comments about how to use this class would be a good addition (especially related to the `frame_paths` property).
___
*[OpenSim/Analyses/IMUDataReporter.h, line 68 at r13](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-MaAhwu90kL-qX6qpiyr:-MaAhwu90kL-qX6qpiys:bqv78uj) ([raw file](https://github.com/opensim-org/opensim-core/blob/3f1654a107336c0b5485d360dda54b0a1592ee5e/OpenSim/Analyses/IMUDataReporter.h#L68)):*
> ```objc
>             "Additional ComponentPaths for frames to attach IMUs to. If the model "
>             "has IMUs attached already they will always be reported, for frames specified "
>             "here, IMUs are temporarily created, attached and reported.");
> ```

Consider: "Additional ComponentPaths to frames in the model to which new IMUs components are attached. IMUs added based on these paths will be appended to the list of existing IMUs in the model. Both the existing IMUs and appended IMUs from these frame paths are included in the data report."
___
*[OpenSim/Analyses/IMUDataReporter.h, line 73 at r13](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-MaAhl6kCoTE2esV6b-S:-MaAhl6kCoTE2esV6b-T:b-eqdygg) ([raw file](https://github.com/opensim-org/opensim-core/blob/3f1654a107336c0b5485d360dda54b0a1592ee5e/OpenSim/Analyses/IMUDataReporter.h#L73)):*
> ```objc
> //=============================================================================
> private:
>     std::vector<OpenSim::IMU*> _imuComponents;
> ```

Consider change this to `std::vector<SimTK::ReferencePtr>` instead (see comment below).
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 156 at r13](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-MaAh3Sp7tdWlQSeC9KK:-MaAh3Sq61qh5NI2bd2c:bszppmj) ([raw file](https://github.com/opensim-org/opensim-core/blob/3f1654a107336c0b5485d360dda54b0a1592ee5e/OpenSim/Analyses/IMUDataReporter.cpp#L156)):*
> ```cpp
>             _modelLocal.reset(_model->clone());
>             auto compList = _model->getComponentList<const OpenSim::IMU>();
>             for (IMU imu : compList) { 
> ```

Is this line (and the line above) making copies? Also, `_imuComponents` is a vector of raw pointers which probably isn't ideal.`SimTK::ReferencePtr` might be better.


<!-- Sent from Reviewable.io -->

2021-05-21 06:35 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[OpenSim/Analyses/IMUDataReporter.h, line 68 at r13](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-MaAhwu90kL-qX6qpiyr:-MaCcCP4-tbpotUWQmF_:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/3f1654a107336c0b5485d360dda54b0a1592ee5e/OpenSim/Analyses/IMUDataReporter.h#L68)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Consider: "Additional ComponentPaths to frames in the model to which new IMUs components are attached. IMUs added based on these paths will be appended to the list of existing IMUs in the model. Both the existing IMUs and appended IMUs from these frame paths are included in the data report."
</blockquote></details>

Done.
___
*[OpenSim/Analyses/IMUDataReporter.h, line 73 at r13](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-MaAhl6kCoTE2esV6b-S:-MaAntxZ5WVz6lT1Ejkv:b-v00del) ([raw file](https://github.com/opensim-org/opensim-core/blob/3f1654a107336c0b5485d360dda54b0a1592ee5e/OpenSim/Analyses/IMUDataReporter.h#L73)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Consider change this to `std::vector<SimTK::ReferencePtr>` instead (see comment below).
</blockquote></details>

It's a good point except for the fact that classes/types that live across the API (created/passed in scripting) need to be handled by swig, switching to shared_ptr. 


<!-- Sent from Reviewable.io -->

2021-05-21 18:58 UTC, nickbianco approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r14.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2997#-:-MaFHhpT7wF1RB9ZpMw-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2021-05-23 21:26 UTC, merged

2021-05-23 21:26 UTC, aymanhab commented
Thanks much for the review @nickbianco and @carmichaelong

2021-05-24 01:38 UTC, nickbianco commented
Thanks @aymanhab!