Fix errors reported by user (use osim. where needed,  true ->True)
opensim-org/opensim-core pull request #3053
Opened 2021-08-02 23:48 UTC by aymanhab

Fixes issue #3050 

### Brief summary of changes

### Testing I've completed

### Looking for feedback on...

### CHANGELOG.md (choose one)

- no need to update because bugfix

2021-08-03 08:11 UTC, aymanhab commented
Ready for quick review @carmichaelong

2021-08-03 16:31 UTC, carmichaelong requested changes

2021-08-03 16:31 UTC, carmichaelong commented on Bindings/Python/OpenSenseExample/OpenSense_CalibrateModel.py
> +import math.pi as pi
This line doesn't work for me (`No module named 'math.pi'; 'math' is not a package`). Consider `from math import pi` instead, and then `pi` will be defined too

2021-08-03 16:31 UTC, carmichaelong commented on Bindings/Python/OpenSenseExample/OpenSense_OrientationTracking.py
> +import math.pi as pi
Same here

2021-08-03 17:22 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3053)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @carmichaelong)

___
*[Bindings/Python/OpenSenseExample/OpenSense_CalibrateModel.py, line 25 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3053#-Mg8GAWLoTjYhV6oXWwQ-r1-25:-MgC0IwN9QAv4XEAhL0h:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/640e5a1c64ff168ef384f658d70415a88dd8822f/Bindings/Python/OpenSenseExample/OpenSense_CalibrateModel.py#L25)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

This line doesn't work for me (`No module named 'math.pi'; 'math' is not a package`). Consider `from math import pi` instead, and then `pi` will be defined too
</blockquote></details>

Done.
___
*[Bindings/Python/OpenSenseExample/OpenSense_OrientationTracking.py, line 29 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3053#-Mg8GAWLoTjYhV6oXWwR-r1-29:-MgC0KRmEKqI3A0vWw4W:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/640e5a1c64ff168ef384f658d70415a88dd8822f/Bindings/Python/OpenSenseExample/OpenSense_OrientationTracking.py#L29)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-03 18:17 UTC, carmichaelong approved these changes
LGTM. I will also add this to the testing doc

2021-08-04 17:33 UTC, merged

2021-08-04 17:33 UTC, aymanhab commented
Thanks @carmichaelong