Replace lowlevel Superbuild_ flags used for Moco build with two options
opensim-org/opensim-core pull request #3173
Opened 2022-03-30 19:14 UTC by aymanhab

Use same options OPENSIM_WITH_TROPTER, OPENSIM_WITH_CASADI used in opensim-core build

Fixes issue #0

### Brief summary of changes
Introduced two flags to control the Superbuild_ flags so the setting is consistent.
### Testing I've completed
Built with both flags on, off, or mixed.
### Looking for feedback on...
1. Should these new options be off by default? I chose this because otherwise the Superbuild_ options will show defeating the purpose.
2. Should the Superbuild_ options be marked as advanced?
3. 
### CHANGELOG.md (choose one)

- no need to update because not sure this is user facing, will look

2022-03-31 16:54 UTC, nickbianco requested changes
> Should these new options be off by default? I chose this because otherwise the Superbuild_ options will show defeating the purpose.

I think `OPENSIM_WITH_TROPTER` could be off by default since most users don't use Tropter, but I would leave `OPENSIM_WITH_CASADI` on. Or did you mean the Superbuild_ options?

> Should the Superbuild_ options be marked as advanced?

I think that's fine.

Just one quick comment: adolc is only used for Tropter, so it doesn't need to be built with CasADi.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3173#-:-MzVsJpI-ysnrhjTIhQe:b-zg6oje)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[dependencies/CMakeLists.txt, line 226 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3173#-MzVryFb82UysC1wFx5o:-MzVryFb82UysC1wFx5p:b5p5in4) ([raw file](https://github.com/opensim-org/opensim-core/blob/ad53fb5e714e9c7aeba5f5cc5823075ddb9d9cc6/dependencies/CMakeLists.txt#L226)):*
> ```CMake
> 
> CMAKE_DEPENDENT_OPTION(SUPERBUILD_adolc "Automatically download, configure, build and install adolc" ON
>                        "OPENSIM_WITH_TROPTER OR OPENSIM_WITH_CASADI" OFF)
> ```

adolc is only needed for Tropter


<!-- Sent from Reviewable.io -->

2022-04-04 19:43 UTC, aymanhab reviewed
I made SUPERBUILD_* flags advanced to reduce the clutter and updated dependencies for adolc. The issue with having OPENSIM_WITH_CASADI on by default is that turning it off later doesn't turn off the dependencies because the CMake function that adds dependencies uses the old/unconditional SET rather than the more modern cmake_dependent_option. May do the switch if not too messy.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3173#-:-MzpdGQf9Hv0vWzrat-Y:b-cwpf6f)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[dependencies/CMakeLists.txt, line 226 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3173#-MzVryFb82UysC1wFx5o:-MzpdC_33Lzq41D2noTX:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/ad53fb5e714e9c7aeba5f5cc5823075ddb9d9cc6/dependencies/CMakeLists.txt#L226)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

adolc is only needed for Tropter
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-04 20:32 UTC, nickbianco requested changes
If it's complicated to the current CMake configuration to have it on by default, then I'm fine having it off. It won't affect the CI builds or anything since we manually set those variables?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3173#-:-MzqG_nUBq9QUT0qO3PS:bayvq4c)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[dependencies/CMakeLists.txt, line 230 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3173#-MzqGB7zDxbOdRrxq3-F:-MzqGB7zDxbOdRrxq3-G:b-241ie9) ([raw file](https://github.com/opensim-org/opensim-core/blob/c12468e483abaa3a271a02a739284b2f461eba97/dependencies/CMakeLists.txt#L230)):*
> ```CMake
> 
> CMAKE_DEPENDENT_OPTION(SUPERBUILD_adolc "Automatically download, configure, build and install adolc" ON
>                        "OPENSIM_WITH_TROPTER" ON)
> ```

Did you mean to switch <force> here to ON?


<!-- Sent from Reviewable.io -->

2022-04-04 20:52 UTC, aymanhab reviewed
Exactly, it's all about what defaults developers get out of the box but all old customization is still the same.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3173#-:-MzqJBhO2uj04NiAypY9:bk34arf)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[dependencies/CMakeLists.txt, line 230 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3173#-MzqGB7zDxbOdRrxq3-F:-MzqL5WpCr9H32h67lrT:bpbqpnu) ([raw file](https://github.com/opensim-org/opensim-core/blob/c12468e483abaa3a271a02a739284b2f461eba97/dependencies/CMakeLists.txt#L230)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Did you mean to switch <force> here to ON?
</blockquote></details>

Thanks for the catch @nickbianco I was trying the various combinations and this was out of sync. Now fixed to be in sync with OPENSIM_WITH_TROPTER default setting i.e. OFF


<!-- Sent from Reviewable.io -->

2022-04-04 21:28 UTC, nickbianco approved these changes
Sounds good. LGTM.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3173#-:-MzqTW5E3PNmT_l5iuRf:bburnas)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2022-04-05 18:14 UTC, aymanhab commented
Thanks @nickbianco much appreciated 🥇

2022-04-05 18:14 UTC, merged