Fix coordinate order xml
opensim-org/opensim-core pull request #3196
Opened 2022-05-04 17:05 UTC by aymanhab

Fixes issue #3191

### Brief summary of changes
Changing the order of Coordinates in XML changes that actual mobilities/motions that the coordinates are attached to for a CustomJoint. This PR reorders the Coordinates to match the expectation/contract of downstream code.
### Testing I've completed
Created various combination of model files with different coordinate orderings
### Looking for feedback on...

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/opensim-org/opensim-core/3196)

2022-05-05 18:41 UTC, nickbianco requested changes
Left a few comments. Looks pretty good overall.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-:-N1KWjql5VAg6RVFiAdY:b-mebxg9)* status: all files reviewed, 3 unresolved discussions (waiting on @aymanhab)

___
*[`OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp` line 164 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-N1KRczFBqDr_hJekPbF:-N1KRczFBqDr_hJekPbG:b-ayjkko) ([raw file](https://github.com/opensim-org/opensim-core/blob/b92d9553daab64d74fb848edabdf9631117e007c/OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp#L164)):*
> ```cpp
>             coordinatesInTransformOrder = coordinatesInTransformOrder && 
>                     coordIndex == sizeAsInt;
>             coordIndices.push_back(coordIndex);
> ```

Should this line be inside the `else` branch? It seems like something could go wrong if the first branch is reached and the `coordIndices` vector isn't updated. 
___
*[`OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp` line 217 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-N1KWf5OBHw_lveZTGdV:-N1KWf5OBHw_lveZTGdW:b5ktgf9) ([raw file](https://github.com/opensim-org/opensim-core/blob/b92d9553daab64d74fb848edabdf9631117e007c/OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp#L217)):*
> ```cpp
>         // Copy back values to proper entry in Property_coordinates.
>         // Ideally this would be done using copy construction or operators
>         // unfortunately these wipe out pointers thus breaking downstream code.
> ```

What pointers are destroyed?
___
*[`OpenSim/Simulation/SimbodyEngine/Joint.cpp` line 764 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-N1KVlkl22WqpXusKDsS:-N1KVlkl22WqpXusKDsT:b-64sft8) ([raw file](https://github.com/opensim-org/opensim-core/blob/b92d9553daab64d74fb848edabdf9631117e007c/OpenSim/Simulation/SimbodyEngine/Joint.cpp#L764)):*
> ```cpp
>     for (int iq = 0; iq < numMobilities; ++iq){
>         if (j < nc){ // assign
>             //<=== This assumes coordinates as PROPERTY are in same order of mobilities
> ```

So the joint creates a list of mobilities based on the number of coordinates in the joint prior to this point? 


<!-- Sent from Reviewable.io -->

2022-05-05 18:59 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3196)* status: all files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp` line 164 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-N1KRczFBqDr_hJekPbF:-N1KYLlu3lpF4EGAepGY:b-144e0o) ([raw file](https://github.com/opensim-org/opensim-core/blob/b92d9553daab64d74fb848edabdf9631117e007c/OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp#L164)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Should this line be inside the `else` branch? It seems like something could go wrong if the first branch is reached and the `coordIndices` vector isn't updated. 
</blockquote></details>

Shouldn't matter but this is preferred for the variable to appear closest to its use (actually didn't have it initially but compilers on *nix complained about comparing int to size_t). Once declared, coordIndices.size always returns zero.  The first branch is left alone, intentionally, since it corresponds to no XML Coordinate entry.
___
*[`OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp` line 217 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-N1KWf5OBHw_lveZTGdV:-N1KZU1F3Iiho_03jEHI:bqs1yqw) ([raw file](https://github.com/opensim-org/opensim-core/blob/b92d9553daab64d74fb848edabdf9631117e007c/OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp#L217)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

What pointers are destroyed?
</blockquote></details>

Ownership pointers at the Component level and possibly Joint pointers or traversal pointers which are populated elsewhere. The first one throws Orphan component exceptions downstream.
___
*[`OpenSim/Simulation/SimbodyEngine/Joint.cpp` line 764 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-N1KVlkl22WqpXusKDsS:-N1KZyd98qt8lURQ0In5:bb77ufg) ([raw file](https://github.com/opensim-org/opensim-core/blob/b92d9553daab64d74fb848edabdf9631117e007c/OpenSim/Simulation/SimbodyEngine/Joint.cpp#L764)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

So the joint creates a list of mobilities based on the number of coordinates in the joint prior to this point? 
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2022-05-05 20:58 UTC, nickbianco requested changes
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3196)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[`OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp` line 164 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-N1KRczFBqDr_hJekPbF:-N1Ky6Oz-Y3z-U76pEJh:b-euwy7o) ([raw file](https://github.com/opensim-org/opensim-core/blob/b92d9553daab64d74fb848edabdf9631117e007c/OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp#L164)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Shouldn't matter but this is preferred for the variable to appear closest to its use (actually didn't have it initially but compilers on *nix complained about comparing int to size_t). Once declared, coordIndices.size always returns zero.  The first branch is left alone, intentionally, since it corresponds to no XML Coordinate entry.
</blockquote></details>

Ah, so during deserialization, only one side of the branch is traversed? That makes sense, since you wouldn't have only half of a joint defined in an XML file. Could you leave a quick comment noting that?

Also, I just realized, couldn't you just used the index `i` to check if the indices are in the right order if only the right branch is traversed during deserialization?


<!-- Sent from Reviewable.io -->

2022-05-05 22:07 UTC, nickbianco reviewed
Thanks @aymanhab. One last thing to clarify, then we should be good to go.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-:-N1LFtZSDDGwotnfvQUx:bq3h32x)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2022-05-05 22:15 UTC, aymanhab commented
Thanks much @nickbianco 👍 I'm building and testing after making the change you suggested before I push it for final review.

2022-05-06 05:12 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3196)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp` line 164 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-N1KRczFBqDr_hJekPbF:-N1Mm7PV9FQBKnIdhfLb:b-6sikth) ([raw file](https://github.com/opensim-org/opensim-core/blob/b92d9553daab64d74fb848edabdf9631117e007c/OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp#L164)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Ah, so during deserialization, only one side of the branch is traversed? That makes sense, since you wouldn't have only half of a joint defined in an XML file. Could you leave a quick comment noting that?

Also, I just realized, couldn't you just used the index `i` to check if the indices are in the right order if only the right branch is traversed during deserialization?
</blockquote></details>

Done. Thanks @nickbianco 


<!-- Sent from Reviewable.io -->

2022-05-06 15:16 UTC, nickbianco approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3196#-:-N1OwOa92YhwhqACA48U:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2022-05-06 16:39 UTC, merged