Update `ModelFactory::replaceMusclesWithPathActuators` and add ModelOperator
opensim-org/opensim-core pull request #3253
Opened 2022-07-12 14:40 UTC by nickbianco

### Brief summary of changes

- Include `PathWrap` objects in `ModelFactory::replaceMusclesWithPathActuators`
- Add `ModOpReplaceMusclesWithPathActuators` to ModelOperators.h

### Testing I've completed
- Tested locally.

### CHANGELOG.md (choose one)

- updated.

2022-10-18 21:33 UTC, aymanhab commented on CHANGELOG.md
> +- Added `ModOpReplaceMusclesWithPathActuators`
to the list of available model operators in ....

2022-10-18 21:59 UTC, aymanhab requested changes
LGTM, just need to clarify the changelog message, and open an issue related to mapping properties between muscles for future consideration.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3253#-:-NEh5sUY0Vv-FRtPRJzd:b-wz6nzq)* status: all files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.cpp` line 966 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3253#-NEh4bqH6_4bMuXsRu5p:-NEh4bqH6_4bMuXsRu5q:bvente4) ([raw file](https://github.com/opensim-org/opensim-core/blob/780f7f68dd9e79c17e6fdac53024fbd5635eaf27/OpenSim/Actuators/DeGrooteFregly2016Muscle.cpp#L966)):*
> ```cpp
>         // peform muscle-model-specific mappings or throw exception if muscle
>         // not supported
>         if (auto musc = dynamic_cast<Millard2012EquilibriumMuscle*>(
> ```

I understand this is just a comment change but we should consider moving this code elsewhere. As it stands DeGrooteFregly2016 needs to know/understand how all other muscle models work which doesn't scale. Just open an issue for that or let me know and I'll open one. Have you considered using a generic tool that maps property values?


<!-- Sent from Reviewable.io -->

2022-12-05 20:56 UTC, nickbianco commented
@aymanhab ready for review. I've created issue #3325 based on your request.

2022-12-05 21:02 UTC, aymanhab approved these changes
Thanks @nickbianco
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3253#-:-NIZ51W9-t8YE5J-rvg2:b-iv6vtn)* status: all files reviewed, 2 unresolved discussions (waiting on @nickbianco)



<!-- Sent from Reviewable.io -->

2022-12-06 21:48 UTC, merged

2022-12-06 21:48 UTC, nickbianco commented
Thanks @aymanhab!