[Moco] Add option to normalize tracking error in `MocoContactTrackingGoal`
opensim-org/opensim-core pull request #3270
Opened 2022-07-25 22:57 UTC by nickbianco

### Brief summary of changes
Added property `normalize_tracking_error` to `MocoContactTrackingGoal` to allow users to normalize the 3D contact tracking error based on the contact tracking data.

### Testing I've completed
Tested locally.

### CHANGELOG.md (choose one)

- updated.

2022-10-18 22:00 UTC, carmichaelong requested changes
looking good. some minor documentation or user-facing messaging

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3270#-:-NEh4YpzCI1R2krBTUf4:b-f8kj9t)* status: all files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h` line 299 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3270#-NEh4GOR-DJK-3MzAESd:-NEh4GOR-DJK-3MzAESe:b-xbkx3x) ([raw file](https://github.com/opensim-org/opensim-core/blob/f79116c213d01709ef42323e77c111834a96b0a7/OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h#L299)):*
> ```objc
>     OpenSim_DECLARE_OPTIONAL_PROPERTY(normalize_tracking_error, bool,
>             "Normalize each component of the 3-D tracking error by the peak "
>             "value of each contact force component in the tracking data. "
> ```

peak *magnitude*? or maximum magnitude?
___
*[`OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h` line 301 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3270#-NEh2qdv-_vwr8b4bsmu:-NEh2qdv-_vwr8b4bsmv:b-e94qe2) ([raw file](https://github.com/opensim-org/opensim-core/blob/f79116c213d01709ef42323e77c111834a96b0a7/OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h#L301)):*
> ```objc
>             "value of each contact force component in the tracking data. "
>             "No normalization is applied when tracking data is close to "
>             "zero (default: false).");
> ```

I wasn't sure what "close to zero" meant here (i.e., if it was a number considered to be small for forces, or if it was small in the numerical computer sense) until I saw the code. Was thinking of a way to word this here, but perhaps it could be better if we send an info or warning message to the user, and then the wording of this comment could be something like "When the maximum magnitude of the tracking data is close to zero, no normalization is applied and a (info/warning) message is provided."
___
*[`OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.cpp` line 207 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3270#-NEh4NuLD_bI5lw2M1g_:-NEh4NuLD_bI5lw2M1ga:bw20qtn) ([raw file](https://github.com/opensim-org/opensim-core/blob/f79116c213d01709ef42323e77c111834a96b0a7/OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.cpp#L207)):*
> ```cpp
>             if (factor > SimTK::SignificantReal) {
>                 groupInfo.normalizeFactors[i] = factor;
>             }
> ```

if we want an info/warning, could go here in an `else` statement


<!-- Sent from Reviewable.io -->

2022-12-05 20:29 UTC, nickbianco commented
@carmichaelong ready for review.

2022-12-06 00:17 UTC, nickbianco commented
@carmichaelong The failing test seems unrelated to the changes here.

2022-12-07 07:46 UTC, carmichaelong approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3270#-:-NIfYFzT1RGZodOEAWFj:bnfp4nl)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @nickbianco)



<!-- Sent from Reviewable.io -->

2022-12-07 21:26 UTC, merged

2022-12-07 21:27 UTC, nickbianco commented
Thanks @carmichaelong!