Removed remaining OPENSIM_HOME references.
opensim-org/opensim-core pull request #3300
Opened 2022-10-14 20:54 UTC by AlbertoCasasOrtiz

Fixes issue #2803 #3077

### Brief summary of changes

Removed remaining references to OPENSIM_HOME.

### Testing I've completed

Waiting for CI to complete.

### Looking for feedback on...

Matlab script modified, since I don't have a matlab right now.

### CHANGELOG.md (choose one)

- no need to update because it was already stated in the past that this variable was no longer maintained.

2022-10-17 17:52 UTC, aymanhab requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3300)* status: all files reviewed, 1 unresolved discussion (waiting on @AlbertoCasasOrtiz)

___
*[`Bindings/Java/Matlab/configureOpenSim.m.in` line 81 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3300#-NEb2QrnDvreBuUqTi9K:-NEb2QrnDvreBuUqTi9L:b-ybajzc) ([raw file](https://github.com/opensim-org/opensim-core/blob/ace2ad43a40740648299cd09d6c1d0fc30541ff1/Bindings/Java/Matlab/configureOpenSim.m.in#L81)):*
> ```
>         startPath = getenv('OPENSIM_HOME');
>     end
>     prompt = 'Select the OpenSim installation folder.';
> ```

If the env. var is set, could we tell the user that support for it has been dropped, in case user is mistakenly using it else where? Not sure how common is this scenario though since this goes way long ago. @carmichaelong ?


<!-- Sent from Reviewable.io -->

2022-10-17 17:53 UTC, aymanhab reviewed
LGTM, waiting on @carmichaelong who interacts with more users to see if a warning about dropping support would be justified.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3300#-:-NEb3r3l-fyH4LloryCh:b-km314g)* status: all files reviewed, 1 unresolved discussion (waiting on @AlbertoCasasOrtiz)



<!-- Sent from Reviewable.io -->

2022-10-17 18:58 UTC, carmichaelong commented
I'm also not sure how common it is to use this, but since we dropped support awhile ago, I think it's safe to remove and OK to do without a warning. I would just suggest adding a line in the CHANGELOG just in case.

2022-10-18 18:12 UTC, aymanhab commented
Thanks @carmichaelong, agreed. @AlbertoCasasOrtiz please update changlelog.md accordingly then let me know to merge. Thank you

2022-10-18 22:13 UTC, AlbertoCasasOrtiz reviewed
Changelog.md updated.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3300#-:-NEh9Bw2B5aaSf9uSs6I:b-maj1ur)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2022-10-18 22:34 UTC, aymanhab approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3300#-:-NEhDrPc-vH_Vm4TZEKI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @AlbertoCasasOrtiz)



<!-- Sent from Reviewable.io -->

2022-10-18 22:35 UTC, aymanhab commented
Thanks @AlbertoCasasOrtiz feel free to merge when tests finish (and you can verify that failures if any are unrelated)

2022-10-19 20:25 UTC, aymanhab commented
Test failure seem unrelated to the code change, merging.

2022-10-19 20:25 UTC, merged