[WIP] Fix mac libgcc problem
opensim-org/opensim-core pull request #3353
Opened 2023-01-09 22:21 UTC by AlbertoCasasOrtiz

Fixes issue #3342

### Brief summary of changes

The name of the library is now extracted using otool, instead of being hardcoded.

### Testing I've completed

- [ ] Tested locally on a Mac VM.
- [ ] Tested on CI.

### CHANGELOG.md (choose one)

- no need to update because this is a cmake problem.

2023-01-11 19:03 UTC, AlbertoCasasOrtiz commented
Tested artifact generated by CI and artifact generated in a local VM machine in two new fresh mac VMs.

2023-01-17 21:46 UTC, aymanhab commented on Vendors/tropter/cmake/CMakeLists.txt
> +
This message is helpful for debugging but could be removed since this rarely changes

2023-01-17 21:46 UTC, aymanhab commented on Vendors/tropter/cmake/tropter_install_mac_dependency_libraries.cmake.in
> +
Same comment, I'd remove debugging line from output

2023-01-17 21:47 UTC, aymanhab requested changes
LGTM, just remove debugging lines and feel free to merge once tests pass. Thank you

2023-01-19 18:20 UTC, merged