Update c3dExport.m per suggestions, fix marker data conversion
opensim-org/opensim-core pull request #3590
Opened 2023-10-27 21:04 UTC by aymanhab

Fixes issue #3501 

### Brief summary of changes
Update c3dExport per feedback from BJ Fregly, and implement marker data conversion if desired

### Testing I've completed
Tested on local files and the conversion worked as expected except that the trc file header is now incorrect
Opened issue https://github.com/opensim-org/opensim-core/issues/3589 to address units in header

### Looking for feedback on...

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

2023-10-27 21:06 UTC, aymanhab commented
@nickbianco and @bfregly for review.

2023-10-27 21:17 UTC, nickbianco requested changes
A few minor comments, otherwise looks good.

2023-10-27 21:17 UTC, nickbianco commented on Bindings/Java/Matlab/examples/c3dExport.m
> +% basename as the selcted input .c3d file.
Should the function handle and comments be below the license statement?

2023-10-27 21:17 UTC, nickbianco commented on Bindings/Java/Matlab/examples/c3dExport.m
> +%outputMomentsPoint = 0;
Consider making this a string input (e.g., 'electrical_center' and 'center_or_pressure') or rename the variable to reflect the boolean (e.g., `useCenterOfPressureAsMomentsPoint`).

2023-10-30 18:15 UTC, aymanhab reviewed
Thanks @nickbianco I addressed your feedback, also exposed a method that was lost in the bindings to multiply columndata in place which makes the code way cleaner and vastly faster.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-:-Ni0mkMN95a592PfrwPU:bgj7qlr)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`Bindings/Java/Matlab/examples/c3dExport.m` line 3 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3590#gh-1375050168:-Ni0m_t-5hBTW0Fah--u:b-1ozq64) ([raw file](https://github.com/opensim-org/opensim-core/blob/ee3085a3d4f479025b5ee1bd7d3276fc04e6184b/Bindings/Java/Matlab/examples/c3dExport.m#L3)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Consider making this a string input (e.g., 'electrical_center' and 'center_or_pressure') or rename the variable to reflect the boolean (e.g., `useCenterOfPressureAsMomentsPoint`).
</blockquote></details>

Done. Renamed, hope this is more readable
___
*[`Bindings/Java/Matlab/examples/c3dExport.m` line 13 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3590#gh-1375048980:-Ni0meFSEMcpbM0J9NtK:b-qu0ova) ([raw file](https://github.com/opensim-org/opensim-core/blob/ee3085a3d4f479025b5ee1bd7d3276fc04e6184b/Bindings/Java/Matlab/examples/c3dExport.m#L13)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Should the function handle and comments be below the license statement?
</blockquote></details>

Done. Moved


<!-- Sent from Reviewable.io -->

2023-10-30 18:24 UTC, nickbianco reviewed
@aymanhab, I don't think your latest changes have been pushed.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-:-Ni0ox295J72oA5Tu668:b-kdshmj)* status: 0 of 2 files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2023-10-30 18:40 UTC, nickbianco reviewed
@aymanhab Let's merge into this one so we don't have to start a new review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-:-Ni0sgJb1IY8AXWoKV49:b8eteer)* status: 0 of 2 files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2023-10-30 19:05 UTC, nickbianco requested changes
Thanks @aymanhab, left a handful of new comments.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-:-Ni0yLW16yCxuaeL7Kwy:b-dldgwe)* status: all files reviewed, 7 unresolved discussions (waiting on @aymanhab)

___
*[`Bindings/simbody.i` line 64 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0xKs48X4VN6zJLOL9:-Ni0xKs48X4VN6zJLOLA:b3fe0hs) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/simbody.i#L64)):*
> ```SWIG
> %rename(__deref__)            MatrixBaseVec3::operator*();
> %rename(__deref__)            MatrixBaseVec3::operator*() const;
> %rename(__div__)              MatrixBaseVec3::operator/;
> ```

Are these additions necessary for the other changes in the PR? See my other comment about method naming.
___
*[`Bindings/simbody.i` line 197 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0wmTm1tfeyHY9SDmr:-Ni0wmTm1tfeyHY9SDms:be5ac7b) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/simbody.i#L197)):*
> ```SWIG
> // multiply assign operator is useful for unit conversion of data columns
> %extend VectorView_<Vec3> {
>     VectorView_<Vec3> mul_assign(double t){
> ```

This is super useful, but I'm not sure anyone will find it (or understand it) with this signature. `MatrixBase` has similar methods like `scalarMultiplyInPlace()` (not sure if already exposed); perhaps a name like that would be more descriptive.
___
*[`Bindings/Java/Matlab/examples/c3dExport.m` line 8 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0vzTL0Li2xYwcPlI-:-Ni0vzTL0Li2xYwcPlI0:b-3fulqw) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/Java/Matlab/examples/c3dExport.m#L8)):*
> ```objc
> % R24 HD065690) and by DARPA through the Warrior Web program.             %
> %                                                                         %
> % Copyright (c) 2005-2018 Stanford University and the Authors             %
> ```

Update the copyright year?
___
*[`Bindings/Java/Matlab/examples/c3dExport.m` line 35 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0wY8q8TG8DVQspq9A:-Ni0wY8q8TG8DVQspq9B:b-qopba6) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/Java/Matlab/examples/c3dExport.m#L35)):*
> ```objc
> % Computational Neuromechanics Lab at Rice University.
> % The modified version names output .trc and .mot files with the same
> % basename as the selcted input .c3d file.
> ```

I think this paragraph could be removed.
___
*[`Bindings/Java/Matlab/examples/c3dExport.m` line 108 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0wdsm0jpgJODeQ8Fy:-Ni0wdsm0jpgJODeQ8Fz:bpy54h2) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/Java/Matlab/examples/c3dExport.m#L108)):*
> ```objc
>     c3d.writeMOT(forcesFilename);
> 
> end
> ```

Add blank EOF line.
___
*[`Bindings/Java/Matlab/Utilities/osimC3D.m` line 173 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0xxdvDJbAyXbzM4Fi:-Ni0xxdvDJbAyXbzM4Fj:b-etiiz7) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/Java/Matlab/Utilities/osimC3D.m#L173)):*
> ```objc
>                 end
>             end
>             % verify markers are in mm
> ```

Shouldn't this be "Convert markers to meters if in millimeters"?
___
*[`Bindings/Java/Matlab/Utilities/osimC3D.m` line 183 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0y0VcCQHvpw6_gR1x:-Ni0y0VcCQHvpw6_gR1y:b-7xx9ok) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/Java/Matlab/Utilities/osimC3D.m#L183)):*
> ```objc
>                 end
>                 % todo fix units in table/trc file to correspond to data
>                 % self.markers.addTableMetaDataString("units", "mm");
> ```

I know this is  commented out but shouldn't it be `self.markers.addTableMetaDataString("units", "m")`?


<!-- Sent from Reviewable.io -->

2023-10-30 19:28 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3590)* status: all files reviewed, 7 unresolved discussions (waiting on @nickbianco)

___
*[`Bindings/simbody.i` line 64 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0xKs48X4VN6zJLOL9:-Ni108jT3Or-WI960Euz:b32h74a) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/simbody.i#L64)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Are these additions necessary for the other changes in the PR? See my other comment about method naming.
</blockquote></details>

I'll remove all these renames as SWIG couldn't handle them and ended up custom adding the only method I needed. I'll address your comment on the name below
___
*[`Bindings/simbody.i` line 197 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0wmTm1tfeyHY9SDmr:-Ni10UQE1IQ23eTrVlz8:b1m6wje) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/simbody.i#L197)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This is super useful, but I'm not sure anyone will find it (or understand it) with this signature. `MatrixBase` has similar methods like `scalarMultiplyInPlace()` (not sure if already exposed); perhaps a name like that would be more descriptive.
</blockquote></details>

The issue here is that while swig is now incapable of handling the method which is NOT exposed as of now, we don't want to get in the way of it down the road. I'm open to any other name if this isn't clear enough.
___
*[`Bindings/Java/Matlab/examples/c3dExport.m` line 8 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0vzTL0Li2xYwcPlI-:-Ni1150U6X7I6hYX7Dlx:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/Java/Matlab/examples/c3dExport.m#L8)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Update the copyright year?
</blockquote></details>

Done.
___
*[`Bindings/Java/Matlab/examples/c3dExport.m` line 35 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0wY8q8TG8DVQspq9A:-Ni11EDd5V597AsdDTQ9:b34jze6) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/Java/Matlab/examples/c3dExport.m#L35)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I think this paragraph could be removed.
</blockquote></details>

Only partially since I think we should keep the convention for output file names.
___
*[`Bindings/Java/Matlab/examples/c3dExport.m` line 108 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0wdsm0jpgJODeQ8Fy:-Ni11PYT9DwCTu_2k4PA:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/Java/Matlab/examples/c3dExport.m#L108)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Add blank EOF line.
</blockquote></details>

Done.
___
*[`Bindings/Java/Matlab/Utilities/osimC3D.m` line 183 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0y0VcCQHvpw6_gR1x:-Ni11vxT-VPz_-WWApi3:b-eclffk) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/Java/Matlab/Utilities/osimC3D.m#L183)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I know this is  commented out but shouldn't it be `self.markers.addTableMetaDataString("units", "m")`?
</blockquote></details>

yes but I'll remove the line altogether until we actually have a method since otherwise users could be inclined to uncomment and assume it's working


<!-- Sent from Reviewable.io -->

2023-10-30 19:28 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3590)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @nickbianco)

___
*[`Bindings/Java/Matlab/Utilities/osimC3D.m` line 173 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0xxdvDJbAyXbzM4Fi:-Ni12rMXDJwgTncwhLnt:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/Java/Matlab/Utilities/osimC3D.m#L173)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Shouldn't this be "Convert markers to meters if in millimeters"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 19:50 UTC, nickbianco requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3590)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[`Bindings/simbody.i` line 197 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0wmTm1tfeyHY9SDmr:-Ni17Z_k-BRzdW6myObs:b-bkx5x1) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/simbody.i#L197)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

The issue here is that while swig is now incapable of handling the method which is NOT exposed as of now, we don't want to get in the way of it down the road. I'm open to any other name if this isn't clear enough.
</blockquote></details>

How about `multiplyAssign()`?


<!-- Sent from Reviewable.io -->

2023-10-30 19:50 UTC, nickbianco reviewed
One last suggestion for the method name.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-:-Ni17ilG-x41o7uWkEwe:b-tho1hh)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2023-10-30 20:01 UTC, aymanhab reviewed
Thanks for the quick turnaround @nickbianco :+1: 

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-:-Ni1ACKV1oqpBrKGkhrd:b9xidr2)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`Bindings/simbody.i` line 197 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-Ni0wmTm1tfeyHY9SDmr:-Ni1A5aC0-x1HEKabSdA:bx62e5y) ([raw file](https://github.com/opensim-org/opensim-core/blob/b3cf702da0083b8a3acef235581cc92f0e1de091/Bindings/simbody.i#L197)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

How about `multiplyAssign()`?
</blockquote></details>

Done, definitely better.


<!-- Sent from Reviewable.io -->

2023-10-30 20:02 UTC, nickbianco approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3590#-:-Ni1AdcQ6ZBO2ErBxBIM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2023-10-30 20:07 UTC, aymanhab commented
Thanks @nickbianco

2023-10-30 22:33 UTC, merged