Allow zeroth order derivative for Bezier Curve
opensim-org/opensim-core pull request #3596
Opened 2023-11-01 11:38 UTC by pepbos

This PR changes `calcValue` to be a special case of `calcDerivative` with order zero.

This allows for less if / else switches further down the line and focuses calculations to a single function body.
Otherwise does not change the output of `calcValue` or `calcDerivative`.

### Brief summary of changes

In `SmoothSegmentedFunction`
- `calcDerivative` allows order zero.
- `calcValue` calls `calcDerivative` with order zero.

Similarly, in `SegmentedQuinticBezierToolkit`:
- `calcQuinticBezierCurveDerivU` and `calcQuinticBezierCurveDYDX` allow for order zero.
- `calcQuinticBezierCurveCurveVal` calls `calcQuinticBezierCurveDerivU` with order zero.

Changed `MustThrow` unit test accordingly.

### Testing I've completed

- Unit tests are still running.
- No significant change in performance (wall clock time) when simulating Rajagopal.
- No change in simulation result of Rajagopal.

### CHANGELOG.md

Change too minor?

2023-11-01 16:24 UTC, nickbianco requested changes
One minor comment, but otherwise looks good.

@pepbos I think one reviewer for this change is fine, max two.

2023-11-01 16:24 UTC, nickbianco commented on OpenSim/Common/SegmentedQuinticBezierToolkit.cpp
> +        "Error: order must be greater than zero.");
Should be "...greater than or equal to zero."

2023-11-02 08:24 UTC, pepbos commented
@nickbianco thanks for reviewing :)

2023-11-02 16:32 UTC, nickbianco approved these changes
LGTM.

2023-11-06 11:16 UTC, merged