Check if metadata key exists and if so "Remove" before "add"
opensim-org/opensim-core pull request #3611
Opened 2023-11-16 00:39 UTC by aymanhab

Fixes issue #3589 

### Brief summary of changes
Actually it's possible to addMetaData for units but only if it doesn't exist. I modified the test case and the method in bindings to exercise this workflow. Will update the c3dExport file once we agree on what to include.

### Testing I've completed
Updated Java test case to change units to Meters
### Looking for feedback on...
Whether update the .i file considering that the name of the method starting with "add", or leave alone and update the test code/sample accordingly basically leaving door for future confusion!

### CHANGELOG.md (choose one)

- no need to update yet

2023-11-16 00:40 UTC, aymanhab commented
@nickbianco for your review/feedback

2023-11-16 05:45 UTC, nickbianco commented
@aymanhab, this change seems reasonable, but is there no way to simply update existing metadata values given a key, rather than removing then adding?

2023-11-16 05:46 UTC, nickbianco commented on Bindings/Java/tests/TestC3DFileAdapter.java
> +            markerTableInMeters.removeTableMetaDataKey("Units");
Is the logic in thsi test necessary given the changes in `common.i`?

2023-11-16 05:52 UTC, nickbianco commented
I think the ideal solution is to add a method like `setTableMetaDataForKey` to `DataTable`. It would update the table metadata object, which is a typedef'd `ValueArrayDictionary`, which already has the method [`setValueForKey`](https://github.com/opensim-org/opensim-core/blob/d349581c0d35746191e0264313495815cd1ec101/OpenSim/Common/ValueArrayDictionary.h#L66). In other words, `setTableMetaDataForKey` would be a wrapper for `setValueForKey`.

2023-11-16 06:06 UTC, aymanhab commented
Unfortunately the documentation of the method in ValueArrayDictionary.h states
/** Set the value corresponding to a given key. Value is set only if the key
does not already exist.  */

2023-11-16 17:39 UTC, nickbianco commented
Oh, weird. That's a poorly named method. Okay, I'm mostly fine with the change, it's just odd to have remove then add to just change a value. 

One more suggestion:  `ValueArrayDictionary` has `updValueForKey` which you can use to modify values. We could add a new method to `AbstractDataTable` called `setTableMetaData` (templated, in scripting it would be `setTableMetaDataString`) which modifies the meta data using `updValueForKey`. There is a mis-match in usages `set` and `upd` between the table and the meta data array here, but considering that there's already a mis-match in the current implementation (`add` versus `set`), I think this would be fine.

2023-11-20 17:05 UTC, aymanhab commented
@nickbianco I agree about the wierdness ;) 
Actually there's no updValueForKey there's only updValueArrayForKey, I was going to add the method but considering the unexpected naming (and cloning behavior underneath,) I'd lean to leave it as is and open an issue for future revamp. LEt me know what you think.

2023-11-20 18:09 UTC, nickbianco commented
@aymanhab, I see, `updValueArrayForKey` is not exactly what we want. In that case, I think your change to `common.i` is fine, especially since it's just on the bindings side. We can make a proper change sometime in the future.

2023-11-20 19:01 UTC, aymanhab commented
Sounds good, thanks @nickbianco 👍 I'll update changelog and then we can merge.

2023-11-20 19:07 UTC, nickbianco commented
@aymanhab you should update the test to remove the extra code if you're keeping the `common.i` change.s

2023-11-20 21:45 UTC, aymanhab commented
@nickbianco test failure is another intermittent Moco failure on osx.

2023-11-20 21:51 UTC, nickbianco requested changes
One quick change in the CHANGELOG, then LGTM

2023-11-20 21:51 UTC, nickbianco commented on CHANGELOG.md
> +- Added method to addTableMetaDataString through Scripting (#3589)
Consider: "Updated scripting method `addTableMetaDataString` to support overwriting metadata for an existing key (#3589)"

2023-11-21 01:31 UTC, aymanhab commented
Thanks @nickbianco

2023-11-21 01:31 UTC, merged