Component Enhancements
opensim-org/opensim-core pull request #3745
Opened 2024-03-19 22:25 UTC by fcanderson

### Introduction
This PR contributes a number of enhancements to the `OpenSim::Component` class. There are two areas of focus: 1) Bringing Modeling Options & Discrete Variables Up To Speed, and 2) Adding Low-Level State Trajectory Infrastructure.

The motivation for the enhancements originated with my efforts to wrap my `SimTK::ExponentialSpringForce` contact model in OpenSim. `SimTK::ExponentialSpringForce` makes extensive use of discrete state variables. It has four: 1) static coefficient of friction [`double`], 2) kinetic coefficient of friction [`double`], 3) elastic anchor point [`Vec3`], and 4) sliding state [`double`]. While the coefficients of friction could be handled by using OpenSim properties or a control file, the elastic anchor point (ANCHOR) and sliding state (SLIDING) could not.

Unlike other discrete states in OpenSim, ANCHOR and SLIDING are not inputs to a simulation; rather they are **outputs**. They are implemented in Simbody as auto-update discrete states. Auto-update discrete states are the same as continuous states in that they are updated every time step during numerical integration. They are different only in that their time evolution is not governed by differential equations but rather by algebraic expressions.

The central issue that arose was how to save the time histories of ANCHOR and SLIDING to file. In Simbody, the SimTK::State is compartmentalized into four categories: 1) continuous states, 2) discrete states, 3) modeling option states, and 4) data cache variables. In OpenSim, the mechanics exist only for saving the continuous states to file. Specifically, continuous states can currently be serialized to a `Storage` file or to a `TimeSeriesTable`. To my knowledge, until bringing the `SimTK::ExponentialSpringForce` contact model into OpenSim became a goal, there was not a need to serialize discrete states. A complicating factor is that, unlike continuous states which are uniformly type double, discrete states can be any `SimTK::Value<T>` type (e.g., Vec3, Vec4, Quaternion, etc.). 

At first I considered an _ad hoc_ approach for capturing the time histories of ANCHOR and SLIDING (e.g., saving them to a file with a custom format). This approach seemed inelegant and without general benefit.

After meeting with @nickbianco , we decided that the better approach **by far** would be to make good on an existing OpenSim roadmap to add the ability to comprehensively de/serialize all `SimTK::State` variables (i.e., continuous states, discrete states, and modeling options) in a single XML file. An XML format seemed best, as SimTK already possessed the ability to stream non-`double` numerical types. In addition, XML attributes would be an ideal way to identify states by name – falling in line with OpenSim’s existing Component infrastructure (i.e., finding a state via its component path).

Following through on the comprehensive de/serialization plan resulted in the enhancements in this PR.

Before summarizing the code changes, I want to mention that none of the enhancements in this PR require any of OpenSim’s existing code base to change. The enhancements are garnered either by making internal changes to a few existing methods without changes to their argument lists or by the addition of entirely new methods.

Going forward, once this PR has been merged (assuming no significant concerns arise during the review), the plan is to submit a PR for class `OpenSim::StatesDocument` (a working implementation of the state trajectory de/serialization roadmap) and then finally to submit a PR for class `OpenSim::ExponentialContact` (the wrapper for `SimTK::ExponentialSpringForce`, also currently working).

### Brief Summary of Changes

#### Focus 1: Bringing Modeling Options & Discrete Variables Up To Speed
- Methods were added to `OpenSim::Component` for generating a list of all `ModelingOption`s and `DiscreteVariable`s in an `OpenSim::Model` or other `Component`.
- All accessors for `DiscreteVariable`s and `ModelingOption`s in `OpenSim::Component`   (i.e. all `get`, `set`, and `upd` methods) now accept a relative or absolute component path.
- Prior to this PR, all discrete variables were assumed to be type `double`. Several methods were added to `OpenSim::Component` that permit discrete variables to be any `SimTK::Value<T>` type. These types include `bool`, `int`, `double`, `Vec2`, `Vec3`, …, `Vec6`, `Quaternion`, etc.
- Prior to this PR, all discrete variables were assumed to be allocated in OpenSim from `SimTK::DefaultSubsystem`. This assumption prevented externally allocated discrete variables, such as occur in `SimTK::ExponentialSpringForce`, from being brought into OpenSim. A few changes were made in `Component::addDiscreteVariable()` and in `Component::DiscreteVariableInfo` to allow such discrete variables to be listed in the discrete-variable map and accessed via the Component API.

#### Focus 2: Adding Low-Level State Trajectory Infrastructure
For computational efficiency and convenience, six low-level state trajectory methods were added to `OpenSim::Component`. They are templated to accommodate a range of numerical types. Collectively, they form the basis for performing a complete serialization and deserialization of a `SimTK::State`.
```
void getStateVariableTrajectory(const string& path, const Array_<State>& input, Array_<T>& output) const
void getDiscreteVariableTrajectory(const string& path, const Array_<State>& input, Array_<T>& output) const
void getModelingOptionTrajectory(const string& path, const Array_<State>& input, Array_<T>& output) const
void setStateVariableTrajectory(const string& path, const Array_<T>& input, Array_<State>& output) const
void setDiscreteVariableTrajectory(const string& path, const Array_<T>& input, Array_<State>& output) const
void setModelingOptionTrajectory(const string& path, const Array_<T>& input, Array_<State>& output) const
```

### Testing Completed
I added the following Catch2 test cases to ```testComponentInterface.cpp```.
```
TEST_CASE("Component Interface Component::resolveVariableNameAndOwner")
TEST_CASE("Component Interface Modeling Options")
TEST_CASE("Component Interface Discrete Variables")
TEST_CASE("Component Interface Discrete Variables Vec3")
TEST_CASE("Component Interface State Trajectories")
```
In addition, I’ve run fairly thorough tests with `OpenSim::StatesDocument` and `OpenSim::ExponentalContact`. These tests are not included with this PR, as PRs for both `OpenSim::StatesDocument` and `OpenSim::ExponentalContact` will be submitted subsequent to the successful merger of this PR.

All existing test cases and all new test cases in OpenSim pass for `Release` and `RelWithDbgInfo` builds.

### CHANGELOG.md
- Updated.

2024-03-21 22:19 UTC, nickbianco commented
@fcanderson, great to see these changes coming in! Did you want a review now?

2024-03-22 00:18 UTC, fcanderson commented
Hi @nickbianco!  Yes -- the code is ready (I think). A review would be great.

2024-03-25 05:01 UTC, nickbianco requested changes
About halfway through, I'll finish my review in the next couple of days.

One general comment so far: you can leave authorship comments for the license header at the top of the file (I'll stop leaving comments on them for the remainder of the review). We can use `git blame` if we need to bring the pitchforks out on you later ;)

> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-:-NtnxNFR5uw35L_NH_ny:b-uiahte)* status: 1 of 6 files reviewed, 13 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Common/Component.h` line 69 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtngAjG4OneMybbiTFP:-NtngAjG4OneMybbiTFQ:btbkmjk) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L69)):*
> ```objc
>     EmptyComponentPath(const std::string& file,
>         size_t line,
>         const std::string& func,
> ```

nit: consider `funcName` or `methodName` to match other arguments (for this exception class, and the others below).
___
*[`OpenSim/Common/Component.h` line 930 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnhWSt6V6RE10WDW8v:-NtnhWSt6V6RE10WDW8w:b-3rnpkt) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L930)):*
> ```objc
> 
>     // F. C. Anderson ---------------------------------------------------------
>     // Added support for Discrete Variables and Modeling Options.
> ```

Authorship credit would be suited for the author list in license header at the top of the file (we don't typically do this for individual added methods).
___
*[`OpenSim/Common/Component.h` line 950 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtniiFhEjr6tPbO1Lx0:-NtniiFhEjr6tPbO1Lx1:be8wej9) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L950)):*
> ```objc
>     Array<std::string> getModelingOptionNames() const;
> 
>     // F. C. Anderson ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

Can remove.
___
*[`OpenSim/Common/Component.h` line 1437 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnjLVi2bpM0dlJ7MBs:-NtnjLVi2bpM0dlJ7MBt:b1jay3w) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1437)):*
> ```objc
> 
>     // F. C. Anderson ---------------------------------------------------------
>     // Enhanced support for Discrete Variables and Modeling Options.
> ```

Remove (after moving authorship credit to header).
___
*[`OpenSim/Common/Component.h` line 1469 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Ntnk6Ds5hZqSMgjes-y:-Ntnk6Ds5hZqSMgjes-z:b-7dpvox) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1469)):*
> ```objc
>      * 
>      * Note that successfully setting the value of the modeling option will
>      * revert the realization stage back to SimTK::Stage::Instance.
> ```

Consider using the Doxygen macro `@note` here.
___
*[`OpenSim/Common/Component.h` line 1486 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnjYB4CjOMlxsu_3v9:-NtnjYB5ASaf86sveoA7:ba3dfmt) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1486)):*
> ```objc
>         int flag) const;
> 
>     // F. C. Anderson ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

Remove.
___
*[`OpenSim/Common/Component.h` line 1622 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnkPXO5-FfJ_3zhIvC:-NtnkPXO5-FfJ_3zhIvD:b1jay3w) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1622)):*
> ```objc
> 
>     // F. C. Anderson ---------------------------------------------------------
>     // Added support for Discrete Variables and Modeling Options.
> ```

Remove (after moving authorship credit to header).
___
*[`OpenSim/Common/Component.h` line 1626 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnnKVkD-R5L7_9M1n9:-NtnnKVl266yLv6wjT1q:bvup4np) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1626)):*
> ```objc
>     /**
>     * Based on a specified path, resolve the name of a discrete variable or
>     * modeling option and the component that owns it (i.e., its parent).
> ```

nit: the method name suggests that this could be used for any variable, but its only for discrete variables and modeling options. I'm not sure how you would rename it without making it overly long though. (Unless this could also apply to continuous variables, etc.)

One option could be to have separate methods: `resolveDiscreteVariableNameAndOwner` and `resolveModelingOptionNameAndOwner` (if it makes sense and doesn't require too much duplication). 
___
*[`OpenSim/Common/Component.h` line 1636 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnqYeI-coM5PoB80gy:-NtnqYeI-coM5PoB80gz:b-27jv5j) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1636)):*
> ```objc
>     * 
>     * A need for this method arises because discrete variables and modeling
>     * options are not themselves Components. Although the usual traversal
> ```

nit: `StateVariable`s are also not `Component`s, but `Component` provides methods to traverse to them (e.g., `traverseToStateVariable`).
___
*[`OpenSim/Common/Component.h` line 1749 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnuOz10VSySTJnrSGd:-NtnuOz10VSySTJnrSGe:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1749)):*
> ```objc
>     *          const SimTK::Value<Vec3>& valVec3 =
>     *              SimTK::Value<Vec3>::downcast(valAbstract);
>     *          Vec3 x = valDbl + Vec3(0.4);
> ```





_Suggestion:_
```objc
    *          Vec3 x = valVec3 + Vec3(0.4);
```
___
*[`OpenSim/Common/Component.h` line 1854 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Ntnw9e74mNpZuG3Ihon:-Ntnw9e81dJfPRrCsU4D:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1854)):*
> ```objc
>     *          SimTK::Value<Vec3>& valVec3 =
>     *              SimTK::Value<Vec3>::updDowncast(valAbstract);
>     *          valDbl = Vec3(0.4);
> ```





_Suggestion:_
```objc
    *          valVec3 = Vec3(0.4);
```
___
*[`OpenSim/Common/Component.h` line 1858 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnwId-3ClEkL7JGKYY:-NtnwId-3ClEkL7JGKYZ:bp3qs07) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1858)):*
> ```objc
>     * ```
>     * For convenience, a templated method that implements basic downcasting
>     * internally is available. See setDiscreteVariableValue<T>().
> ```

If it exists:



_Suggestion:_
```objc
    * internally is available. See updDiscreteVariableValue<T>().
    
```
___
*[`OpenSim/Common/Component.h` line 1874 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Ntnwk51CBbsS1ydh-Yz:-Ntnwk51CBbsS1ydh-Z-:ba3dfmt) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1874)):*
> ```objc
>         SimTK::State& state, const std::string& path) const;
> 
>     // F. C. Anderson ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

Remove.


<!-- Sent from Reviewable.io -->

2024-03-25 18:53 UTC, fcanderson commented
Thank you for the review, Nick. I'll start making the revisions.





<!-- Sent from Reviewable.io -->

2024-03-25 19:11 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 69 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtngAjG4OneMybbiTFP:-Ntr-_7C6oplsjrUkBLQ:bmihct6) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L69)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: consider `funcName` or `methodName` to match other arguments (for this exception class, and the others below).
</blockquote></details>

done 
I changed all instances of the `func` argument in the Component Exceptions to `methodName`. 


<!-- Sent from Reviewable.io -->

2024-03-25 19:50 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 950 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtniiFhEjr6tPbO1Lx0:-Ntr9RIh-2d9GC8Yv-_1:bb7f2mf) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L950)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Can remove.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-03-25 19:52 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1486 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnjYB4CjOMlxsu_3v9:-Ntr9vsx47plvBtqH9ii:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1486)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 19:52 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1469 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Ntnk6Ds5hZqSMgjes-y:-NtrA-xWBeU07u49lmb-:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1469)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Consider using the Doxygen macro `@note` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 19:53 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1622 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnkPXO5-FfJ_3zhIvC:-NtrA4cs0iAvvWj3FZ3a:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1622)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove (after moving authorship credit to header).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 20:09 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1749 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnuOz10VSySTJnrSGd:-NtrDwaC8UIFf3mkJ28n:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1749)):*
> ```objc
>     *          const SimTK::Value<Vec3>& valVec3 =
>     *              SimTK::Value<Vec3>::downcast(valAbstract);
>     *          Vec3 x = valDbl + Vec3(0.4);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 20:10 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1854 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Ntnw9e74mNpZuG3Ihon:-NtrDxyr2Cmmn5cxdtqz:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1854)):*
> ```objc
>     *          SimTK::Value<Vec3>& valVec3 =
>     *              SimTK::Value<Vec3>::updDowncast(valAbstract);
>     *          valDbl = Vec3(0.4);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 20:11 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1874 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Ntnwk51CBbsS1ydh-Yz:-NtrEOpQ1tErSvjq-TqN:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1874)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 20:16 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1858 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnwId-3ClEkL7JGKYY:-NtrER3p0hjcSLvVhykQ:brfpxtn) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1858)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

If it exists:
</blockquote></details>

This "See" is intended to be `setDiscreteVariableValue<T>`.  Using `updDiscreteVariableValue<T>` requires that the caller handle the downcasting. `setDiscreteVariableValue<T>` takes care of the basic downcasting.

Perhaps I need to work on the comments to make the distinction between the `upd` and `set` clearer?


<!-- Sent from Reviewable.io -->

2024-03-25 20:48 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1626 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnnKVkD-R5L7_9M1n9:-NtrK_DD3_ofgjYWodbi:bi9zcoq) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1626)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: the method name suggests that this could be used for any variable, but its only for discrete variables and modeling options. I'm not sure how you would rename it without making it overly long though. (Unless this could also apply to continuous variables, etc.)

One option could be to have separate methods: `resolveDiscreteVariableNameAndOwner` and `resolveModelingOptionNameAndOwner` (if it makes sense and doesn't require too much duplication).
</blockquote></details>

Good point.

Looking at the code, I think `resolveVariableNameAndOwner()` will actually work for `StateVariable`s. I just haven't teste it.

I will see if I can insert some tests in `testComponentInterface.cpp` to see if `resolveVariableNameAndOwner()` will work for `StateVariable`s.  If so, I will update the documentation to clarify that `resolveVariableNameAndOwner()` can be used for `StateVariable`s, `DiscreteVariable`s, and `ModelingOption`s.

If one method works for all three, seems like we can leave the name as is?


<!-- Sent from Reviewable.io -->

2024-03-25 20:51 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1636 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnqYeI-coM5PoB80gy:-NtrFwhGC5A0YkcqDf23:bb4wrsd) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1636)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: `StateVariable`s are also not `Component`s, but `Component` provides methods to traverse to them (e.g., `traverseToStateVariable`).
</blockquote></details>

Right.  In the comments, I don't actually say that `StateVariables` are `Component`s. What I mean to say is...

"Like `StateVariable`s, the usual component traversal methods cannot be used on `ModelingOption`s or `DiscreteVariable`s, and therefore require a dedicated traversal method is needed for`ModelingOption`s or `DiscreteVariable`s."

The method `traverseToStateVariable()` won't work for `ModelingOption`s and `DiscreteVariable`s because a different call signature is needed.  `traverseToStateVariable()` returns a pointer the `StateVariable` itself. On the other hand, `resolveVariableNameAndOwner()` returns a pointer to the Component owner AND the name of the variable (whether for a discrete variable or modeling option).

As I mentioned in the previous comment, I believe `resolveVariableNameAndOwner()` will work for all three variable types.


<!-- Sent from Reviewable.io -->

2024-03-25 20:56 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 1 of 6 files reviewed, 12 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.h` line 1437 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnjLVi2bpM0dlJ7MBs:-Ntr9VXi-3IrU6vavO8K:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1437)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove (after moving authorship credit to header).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-26 15:29 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1626 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnnKVkD-R5L7_9M1n9:-NtvGzz8D1F2yNS4q-Sx:b-21g7ce) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1626)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Good point.

Looking at the code, I think `resolveVariableNameAndOwner()` will actually work for `StateVariable`s. I just haven't teste it.

I will see if I can insert some tests in `testComponentInterface.cpp` to see if `resolveVariableNameAndOwner()` will work for `StateVariable`s.  If so, I will update the documentation to clarify that `resolveVariableNameAndOwner()` can be used for `StateVariable`s, `DiscreteVariable`s, and `ModelingOption`s.

If one method works for all three, seems like we can leave the name as is?
</blockquote></details>

I added a fairly comprehensive set of checks in
```
TEST_CASE("Component Interface Component::resolveVariableNameAndOwner")
```
and verified that `resolveVariableNameAndOwner()` works for `StateVariable`s too.

I revised the doxygen comment block for `resolveVariableNameAndOwner()` to reflect this.

Is it reasonable to leave the method name as is?  Or, do you think something like
```
resolveVariableOrOptionNameAndOwner()
```
would be better?

Under the covers, modeling options are actually discrete variables. It's just that they are a special case in that their realization stage is always `Stage::Model`.


<!-- Sent from Reviewable.io -->

2024-03-28 04:58 UTC, nickbianco requested changes
Next round of comments are in, just need to review the test cases now.

One main suggestion I have is to consider replacing the raw pointer to `SimTK::Subsystem` in `DiscreteVariableInfo` with a `SimTK::SubsystemIndex` and use that to access the subsystem when needed.

> Reviewed 2 of 6 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-:-Nu2OkBHCXtBmjzrjzcM:b-tbupwt)* status: 5 of 6 files reviewed, 22 unresolved discussions (waiting on @fcanderson)

___
*[`CHANGELOG.md` line 39 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2K1FXExLI-gMctyTy:-Nu2K1FXExLI-gMctyTz:bb6n6vm) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/CHANGELOG.md#L39)):*
> ```Markdown
>   `PrescribedController`s are now excluded from the optimization problem.
> - Methods are now available in `OpenSim::Component` for generating a list of all `ModelingOption`s and `DiscreteVariable`s in an `OpenSim::Model` or other `Component`.
> - `OpenSim::Component` accessor methods for `ModelingOption`s and `DiscreteVariables`s now accept both absolute and relative component paths.
> ```

It would be good to note that these methods now _require_ a path, rather than a name.
___
*[`OpenSim/Common/Component.h` line 1626 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnnKVkD-R5L7_9M1n9:-Nu-u9Ij4vq-BV7EPkEK:b-9q4d3z) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1626)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

I added a fairly comprehensive set of checks in
```
TEST_CASE("Component Interface Component::resolveVariableNameAndOwner")
```
and verified that `resolveVariableNameAndOwner()` works for `StateVariable`s too.

I revised the doxygen comment block for `resolveVariableNameAndOwner()` to reflect this.

Is it reasonable to leave the method name as is?  Or, do you think something like
```
resolveVariableOrOptionNameAndOwner()
```
would be better?

Under the covers, modeling options are actually discrete variables. It's just that they are a special case in that their realization stage is always `Stage::Model`.
</blockquote></details>

Nice test addition and great that it works for `StateVariable`s. I think we can keep the name as-is then.
___
*[`OpenSim/Common/Component.h` line 1636 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnqYeI-coM5PoB80gy:-Nu-uwuj5od7vLTWR06Q:b-v1mlds) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1636)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Right.  In the comments, I don't actually say that `StateVariables` are `Component`s. What I mean to say is...

"Like `StateVariable`s, the usual component traversal methods cannot be used on `ModelingOption`s or `DiscreteVariable`s, and therefore require a dedicated traversal method is needed for`ModelingOption`s or `DiscreteVariable`s."

The method `traverseToStateVariable()` won't work for `ModelingOption`s and `DiscreteVariable`s because a different call signature is needed.  `traverseToStateVariable()` returns a pointer the `StateVariable` itself. On the other hand, `resolveVariableNameAndOwner()` returns a pointer to the Component owner AND the name of the variable (whether for a discrete variable or modeling option).

As I mentioned in the previous comment, I believe `resolveVariableNameAndOwner()` will work for all three variable types.
</blockquote></details>

Thanks for clarifying. It could be helpful now to comment somewhere here that if you just need a `StateVariable` that `traverseToStateVariable` is available, so users don't use this to retrieve one in a roundabout way. 
___
*[`OpenSim/Common/Component.h` line 1858 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnwId-3ClEkL7JGKYY:-Nu-vzgv-d8vqFT0jZCT:b-re71zp) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1858)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

This "See" is intended to be `setDiscreteVariableValue<T>`.  Using `updDiscreteVariableValue<T>` requires that the caller handle the downcasting. `setDiscreteVariableValue<T>` takes care of the basic downcasting.

Perhaps I need to work on the comments to make the distinction between the `upd` and `set` clearer?
</blockquote></details>

Ah. No, this is fine, I see what is happening now.
___
*[`OpenSim/Common/Component.h` line 2385 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-y2p_3pzdgkbNecK4:-Nu-y2p_3pzdgkbNecK5:b-juaar8) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2385)):*
> ```objc
>     //@{
> 
>     // GET TRAJECTORIES -------------------------
> ```

nit: To separate code sections, consider using the following style commonly used elsewhere in the codebase:

```
//==============================================================================
/// GET TRAJECTORIES
//==============================================================================
```
___
*[`OpenSim/Common/Component.h` line 2387 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-yOOX8LdPyh9ntuON:-Nu-yOOYEWgyCPTrus3K:b1nfzd0) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2387)):*
> ```objc
>     // GET TRAJECTORIES -------------------------
> 
>     //_________________________________________________________________________
> ```

nit: more of a personal preference thing, but extra lines separating functions to me are unnecessary (and sometimes add visual clutter if used excessively).
___
*[`OpenSim/Common/Component.h` line 2421 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-z1crBfwCSWcMUtc0:-Nu-z1crBfwCSWcMUtc1:b4q7ogb) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2421)):*
> ```objc
>     The word "trajectory" connotes that the State and variable values are
>     expected to be time-ordered, which will most commonly be the case.
>     To be clear, however, this charicteristic is not essential here and is not
> ```

Something like "...this characteristic is not generaly true for discrete varaibles and therefore is not checked..." might be a bit clearer.
___
*[`OpenSim/Common/Component.h` line 2476 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu23Tju9bMvqZB3hNLR:-Nu23Tju9bMvqZB3hNLS:benpsw9) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2476)):*
> ```objc
>     The word "trajectory" connotes that the State and option values are
>     expected to be time-ordered, which will most commonly be the case.
>     To be clear, however, this charicteristic is not essential here and is not
> ```

Same comment as above.
___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-Nu25hSj3TuGr1DPBoxZ:bo4gj5v) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
> ```objc
> 
>         // Found. Loop over the input and set the output.
>         // TODO: account for a non-default subsystem. This might occur
> ```

Why is the subsystem not available from the `Component` in this case?
___
*[`OpenSim/Common/Component.h` line 2535 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu241AA3Lxh1cdRIsvx:-Nu241AA3Lxh1cdRIsvy:b-i1grux) ([raw file](https://githu [...]

2024-03-28 16:06 UTC, fcanderson commented
*[`CHANGELOG.md` line 39 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2K1FXExLI-gMctyTy:-Nu4kwIbA_U8jHrOoBQM:bgzl08i) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/CHANGELOG.md#L39)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

It would be good to note that these methods now _require_ a path, rather than a name.
</blockquote></details>

A path is not required actually. More than the name is only needed if the calling component is not the owner of the option or variable. When called with just the name, the calling `Component` is assumed to be the owner (just as was the case for accessors before this PR).

I will try to clarify in the Doxygen comments that calling the accessors with just the name is fine.


<!-- Sent from Reviewable.io -->

2024-03-28 16:09 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1626 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnnKVkD-R5L7_9M1n9:-Nu4oD5g4NXMbegiRYUV:bdgd7uw) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1626)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Nice test addition and great that it works for `StateVariable`s. I think we can keep the name as-is then.
</blockquote></details>

super. I'll leave the name as is then.
Done.


<!-- Sent from Reviewable.io -->

2024-03-28 16:11 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 1636 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NtnqYeI-coM5PoB80gy:-Nu4omsz6uSycHh1kvyg:b-lvcbo7) ([raw file](https://github.com/opensim-org/opensim-core/blob/672f9d44e20a4bd16da52d9584834cf7bb15ac66/OpenSim/Common/Component.h#L1636)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Thanks for clarifying. It could be helpful now to comment somewhere here that if you just need a `StateVariable` that `traverseToStateVariable` is available, so users don't use this to retrieve one in a roundabout way.
</blockquote></details>

Good idea. On it.


<!-- Sent from Reviewable.io -->

2024-03-28 17:20 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 4 of 6 files reviewed, 22 unresolved discussions (waiting on @nickbianco)

___
*[`CHANGELOG.md` line 39 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2K1FXExLI-gMctyTy:-Nu4sruV8ytdBh_JeVmd:b-beyojf) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/CHANGELOG.md#L39)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

A path is not required actually. More than the name is only needed if the calling component is not the owner of the option or variable. When called with just the name, the calling `Component` is assumed to be the owner (just as was the case for accessors before this PR).

I will try to clarify in the Doxygen comments that calling the accessors with just the name is fine.
</blockquote></details>

I took a look at the current Doxygen comments. That the accessors can be called with the path parameter assigned to just the name is already fairly clear. I tweaked the comments to try to highlight this a little better.  I also clarified that an `EmptyComponentPath` exception is thrown only when path is an empty string (i.e., `path == ""`).

What do you think? Does this aspect of the accessors need to be clarified / emphasized further in the documentation? 


<!-- Sent from Reviewable.io -->

2024-03-28 17:21 UTC, nickbianco requested changes
Finished my review, looks great overall! I mostly added minor comments related to documentation a few suggestions for the tests. 

> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-:-Nu53uV7Et5WyOoEnvws:b-nr9xvn)* status: 5 of 6 files reviewed, 36 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 395 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu4yXrx9fPuUY8WZm2y:-Nu4yXryEqgrqPAPxpJy:b-q2g1ha) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L395)):*
> ```cpp
>         // is allocated in class Bar's override of extendRealizeTopology().
>         // See below.
>         addDiscreteVariable("point", Stage::Position, false);
> ```

For clarity:



_Suggestion:_
```cpp
        bool allocate = false;
        addDiscreteVariable("point", Stage::Position, allocate);
```
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 420 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu4zH8SBXnbuAIOM9T9:-Nu4zH8SBXnbuAIOM9TA:b-lt27q) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L420)):*
> ```cpp
>         // addDiscreteVariable() and was not from the default subsystem.
>         // ?? Using a pointer to a generic Subsystem -may- be necessary.
>         // If this works I'll try to simplify and see if it still works.
> ```

As suggested above, using `SimTK::SubsystemIndex` would be cleaner, if possible.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1548 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu509InEzXPEjhOfw7w:-Nu509InEzXPEjhOfw7x:bea9yi8) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1548)):*
> ```cpp
>     const Component& internSub = top.getComponent("/internalSub");
> 
>     // ----- State Variables
> ```

You could put everything under this comment in a Catch2 section: `SECTION("State Variables") { }`
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1622 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu50l_l2GTGpWik_Ehz:-Nu50l_l2GTGpWik_Ei-:b-9j3rhf) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1622)):*
> ```cpp
>         ComponentPath("../../internalSub/subState"), svName);
>     CHECK(svName == svNameCorrect);
>     CHECK(owner == &internSub);
> ```

nit: there is a lot of repitition here. Not sure if a helper function would reduce the number of lines needed, but something to consider. 
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1624 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu50XFH-44pW5uGatwi:-Nu50XFH-44pW5uGatwj:b7amtql) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1624)):*
> ```cpp
>     CHECK(owner == &internSub);
> 
>     // ----- Discrete Variables
> ```

`SECTION("Discrete Variables") { }`
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1700 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu51XNh665eyjKIdL5l:-Nu51XNh665eyjKIdL5m:b95rolb) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1700)):*
> ```cpp
>     CHECK(owner == &internSub);
> 
>     // Verify that exceptions are thrown appropriately
> ```

`SECTION("Exceptions are thrown appropriately") { }`
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1736 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu527hz8dD6l0CukGZC:-Nu527hz8dD6l0CukGZD:bgfcf4p) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1736)):*
> ```cpp
>     State s = system.realizeTopology();
> 
>     // Get the paths of all discrete variables under "top"
> ```

`SECTION("Paths are correct") { }`
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1747 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu51q6834OoG5PYWtDi:-Nu51q6834OoG5PYWtDj:br9dw6p) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1747)):*
> ```cpp
>     // traversal methods need to be used.
>     // See Component::resolveVariableNameAndOwner().
>     // Set
> ```

`SECTION("Setters") { }`
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1754 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52---CHAHu6Xim50A:-Nu52---CHAHu6Xim50B:b-egvpdv) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1754)):*
> ```cpp
>         ModelingOptionMaxExceeded);
> 
>     // Get
> ```

`SECTION("Getters") { }`
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1795 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52B0A-xLWScHrsjvU:-Nu52B0BEr-lmnrTiNvG:bgfcf4p) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1795)):*
> ```cpp
>     State s = system.realizeTopology();
> 
>     // Get the paths of all discrete variables under "top"
> ```

`SECTION("Paths are correct") { }`
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1806 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52Dv2-O6iT0nCfYWc:-Nu52Dv2-O6iT0nCfYWd:br9dw6p) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1806)):*
> ```cpp
>     // traversal methods need to be used.
>     // See Component::resolveVariableNameAndOwner().
>     // Set
> ```

`SECTION("Setters") { }`
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1811 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52F7V50z-yg_9DVFC:-Nu52F7V50z-yg_9DVFD:b-egvpdv) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1811)):*
> ```cpp
>     top.setDiscreteVariableValue(s, dvPaths[2], 20.0);
> 
>     // Get
> ```

`SECTION("Getters") { }`
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1885 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52Tc_BHHyhBz9jVxr:-Nu52Tc_BHHyhBz9jVxs:b-pq83zw) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1885)):*
> ```cpp
> 
>     // Get the starting value of point
>     // The starting value should be (0.0, 0.1, 0.2). See ~line 403.
> ```

This line number could change in the future. Consider referring directly to`extendRealizeTopology` for the component instead.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1934 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52x7rC033Jvuzh-Rc:-Nu52x7rC033Jvuzh-Rd:b-25y0ji) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1934)):*
> ```cpp
>     // Form the q and u vectors
>     const Array<std::string>& svPaths = wrld.getStateVariableNames();
>     cout << "svPaths = " << svPaths << endl;
> ```

Remove if no longer needed (e.g., from debugging).
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1952 at r2](https://reviewable.io/reviews/opensim-org/o [...]

2024-03-28 17:25 UTC, fcanderson commented
Great! Thanks for the time you've spent on this, Nick!
I'm responding to your comments now. In a few cases, I have questions for you, but for the most part I'm following through on your suggestions.





<!-- Sent from Reviewable.io -->

2024-03-28 17:35 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 2387 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-yOOX8LdPyh9ntuON:-Nu56xPO17FzwMbT72mI:b-jkagfl) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2387)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: more of a personal preference thing, but extra lines separating functions to me are unnecessary (and sometimes add visual clutter if used excessively).
</blockquote></details>

Clarification:  Do you mean the lines with "//__________________________________________________" preceding the methods?


<!-- Sent from Reviewable.io -->

2024-03-28 17:50 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 2385 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-y2p_3pzdgkbNecK4:-Nu57TM26DR1cfOtpHO1:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2385)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: To separate code sections, consider using the following style commonly used elsewhere in the codebase:

```
//==============================================================================
/// GET TRAJECTORIES
//==============================================================================
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 18:19 UTC, nickbianco reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 35 unresolved discussions (waiting on @fcanderson)

___
*[`CHANGELOG.md` line 39 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2K1FXExLI-gMctyTy:-Nu5GbHZ8JsiD7S4LqQE:br06dg7) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/CHANGELOG.md#L39)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

I took a look at the current Doxygen comments. That the accessors can be called with the path parameter assigned to just the name is already fairly clear. I tweaked the comments to try to highlight this a little better.  I also clarified that an `EmptyComponentPath` exception is thrown only when path is an empty string (i.e., `path == ""`).

What do you think? Does this aspect of the accessors need to be clarified / emphasized further in the documentation?
</blockquote></details>

Apologies, I reviewed this over several days and forgot about the comments regarding name vs path in the Doxgyen comments. I agree that it is clear in the current documentation. The additional changes are good additions too.
___
*[`OpenSim/Common/Component.h` line 2387 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-yOOX8LdPyh9ntuON:-Nu5HMwQ9BwABeJBnSjo:beifx4z) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2387)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Clarification:  Do you mean the lines with "//__________________________________________________" preceding the methods?
</blockquote></details>

Yes, this is what I was referring to.


<!-- Sent from Reviewable.io -->

2024-03-28 18:41 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 2387 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-yOOX8LdPyh9ntuON:-Nu5MNHXDNOLuPOAFYFl:b-rzpclf) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2387)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Yes, this is what I was referring to.
</blockquote></details>

Done.
removed


<!-- Sent from Reviewable.io -->

2024-03-28 19:04 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 2421 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-z1crBfwCSWcMUtc0:-Nu5Mo3q4iis976uboEc:b-b2qqiy) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2421)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Something like "...this characteristic is not generaly true for discrete varaibles and therefore is not checked..." might be a bit clearer.
</blockquote></details>

Why would discrete variables not generally be time ordered?

All the Component trajectory methods take a state trajectory in the form of `Array_<SimTK::State>`, which are generally gathered by a reporter during a simulation.  Any Array_<SimTK::State> gathered during a simulation would be time ordered. Since discrete variables are part of the SimTK::State, just like the continuous states, the discrete variables would be time ordered too.

I can see how there may be quite a few discrete variables that are constant, but being constant doesn't mean that the values are not time-ordered.  A continuous state could be constant (e.g., perhaps a coordinate that is locked) for a portion of a simulation, for example, but would still be time-ordered.

How are you seeing discrete states and modeling options as being different from continuous states?


<!-- Sent from Reviewable.io -->

2024-03-28 20:00 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 2421 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-z1crBfwCSWcMUtc0:-Nu5adq18XdjIzIzBnxY:b-5csr9s) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2421)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Why would discrete variables not generally be time ordered?

All the Component trajectory methods take a state trajectory in the form of `Array_<SimTK::State>`, which are generally gathered by a reporter during a simulation.  Any Array_<SimTK::State> gathered during a simulation would be time ordered. Since discrete variables are part of the SimTK::State, just like the continuous states, the discrete variables would be time ordered too.

I can see how there may be quite a few discrete variables that are constant, but being constant doesn't mean that the values are not time-ordered.  A continuous state could be constant (e.g., perhaps a coordinate that is locked) for a portion of a simulation, for example, but would still be time-ordered.

How are you seeing discrete states and modeling options as being different from continuous states?
</blockquote></details>

I've had time to think about your comment  a bit more. Maybe you just mean "constant" as opposed to time-varying?

It seems like there are a enough examples of time-varying discrete variables (e.g., control inputs [muscle excitations, motor throttle, etc.], coefficients of friction for a surface that has slippery patches in defined locations, the elastic anchor point for my contact model, etc.) that not checking on the grounds that discrete variables or modeling options are typically constant doesn't seem like a solid rational for not checking the time-ordered-ness.

I feel more comfortable saying:  it is the user's responsibility to check time-order-ness if that is important for the particular use-case.


<!-- Sent from Reviewable.io -->

2024-03-28 20:15 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-Nu5e4yb0pYNBo-z5wR-:boh3h96) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Why is the subsystem not available from the `Component` in this case?
</blockquote></details>

Only the allocator of the modeling option knows from which subsystem an option was allocated.  Currently, there's no mechanism to import externally-allocated modeling options into OpenSim.

Right now, OpenSim assumes that all modeling options listed in its `std::map` for modeling options (see line 2521) are allocated from the `SimTK::DefaultSubsystem`. This may not be the case if modeling option was allocated externally by a Simbody class, for example.

This is the same issue I encountered for discrete variables.  For discrete variables, I needed to implement a mechanism to 1) prevent double allocation, 2) initialize the discrete variable index, and 3) initialize the associated subsystem.

To handle modeling options more generally in OpenSim, the same or similar thing would need to be done for modeling options as I did for discrete variables.


<!-- Sent from Reviewable.io -->

2024-03-28 20:17 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 2535 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu241AA3Lxh1cdRIsvx:-Nu5hKHg7lJeX8WEi7T6:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2535)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Use section header style suggested above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 20:24 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 3233 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu26o8m7UcQ6Nl26aMC:-Nu5iuhIBVRWPJiYQH7v:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L3233)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Trying to suggest something more descriptive, rather than indicating that a change occured:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 20:42 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 3286 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu28_3WBPzjoOTyzaPR:-Nu5jHSOBrE0bZmPM8Y8:b-d9u9xv) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L3286)):*
> ```objc
>     * the subsystem from which it was allocated. The initialization should be
>     * done by implementing an overridding extendRealizeTopology() method in the
>     * wrapper code and, in that method, calling this method. See class
> ```

Done.
I added the word "overriding" to emphasis that this call cannot be made from the base `Component::extendRealizeTopology()`. This would be apparent to an experienced programmer, but I'm not sure it will be understood immediately by a less experienced programmer.


<!-- Sent from Reviewable.io -->

2024-03-28 20:48 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 3791 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2Ap4GEkMKhnoDo4D2:-Nu5oUUS-WWUl-yHLZ95:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L3791)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Rather than saying "Added to support..." at the top at the comment, consider adding something to end of the comment along the lines of "This may be useful when de/serializing discrete variables...".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 20:48 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 3801 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2Bvxn4eN7mf-dDB_V:-Nu5oW8d6H9jM-9O_mR7:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L3801)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Same comment as above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 20:54 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 4067 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2Dy3pCcwA32uzIBHg:-Nu5pqQJ5_JYGJuCGyLa:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L4067)):*
> ```objc
> 
>         // Introduced two data members: 'subsystem' and 'allocate'.
>         // These data members allow OpenSim::Component to expose a discrete
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 22:01 UTC, nickbianco requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 28 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Common/Component.h` line 2421 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-z1crBfwCSWcMUtc0:-Nu61lCsDP__L9twWbir:b-jqxcgh) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2421)):*
> Maybe you just mean "constant" as opposed to time-varying?

Ah, yes, I read this as "discrete variables do not need to be changing at all time steps", not orderedness. Thanks for clarifying, no changes are needed here.
___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-Nu63Ei_0MvkSavhs9YT:bido0vm) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Only the allocator of the modeling option knows from which subsystem an option was allocated.  Currently, there's no mechanism to import externally-allocated modeling options into OpenSim.

Right now, OpenSim assumes that all modeling options listed in its `std::map` for modeling options (see line 2521) are allocated from the `SimTK::DefaultSubsystem`. This may not be the case if modeling option was allocated externally by a Simbody class, for example.

This is the same issue I encountered for discrete variables.  For discrete variables, I needed to implement a mechanism to 1) prevent double allocation, 2) initialize the discrete variable index, and 3) initialize the associated subsystem.

To handle modeling options more generally in OpenSim, the same or similar thing would need to be done for modeling options as I did for discrete variables.
</blockquote></details>

I see now, for discrete variables, the subsystem is stored in the `DiscreteVariableInfo`. So my actual question is, why not store the subsystem for modeling options in `ModelingOptionInfo` as well?  I would advocate for this change to keep things consistent (unless there something that makes this difficult).


<!-- Sent from Reviewable.io -->

2024-03-28 23:54 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-Nu6SULg5j2EDz89GWn2:b-bw2i48) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I see now, for discrete variables, the subsystem is stored in the `DiscreteVariableInfo`. So my actual question is, why not store the subsystem for modeling options in `ModelingOptionInfo` as well?  I would advocate for this change to keep things consistent (unless there something that makes this difficult).
</blockquote></details>

Nothing makes this difficult. I just didn't want to make any more changes than necessary.

I'm on the same page as you.  It would be best to implement the same mechanic for modeling options as for discrete variables. Doing so would allow the "TODO" to be removed.  And then, the way would be clear for a Simbody class that allocates modeling options externally to be wrapped in OpenSim as well.

I will go ahead and implement the same mechanic for modeling options as for discrete variables.


<!-- Sent from Reviewable.io -->

2024-03-28 23:55 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 28 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.h` line 2421 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu-z1crBfwCSWcMUtc0:-Nu6SJuL-icsDiT-RRL1:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2421)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

> Maybe you just mean "constant" as opposed to time-varying?

Ah, yes, I read this as "discrete variables do not need to be changing at all time steps", not orderedness. Thanks for clarifying, no changes are needed here.
</blockquote></details>

Done.
___
*[`OpenSim/Common/Component.h` line 2476 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu23Tju9bMvqZB3hNLR:-Nu6SMsd9YkfjEz4Dtwj:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2476)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Same comment as above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-29 00:07 UTC, nickbianco reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 25 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-Nu6Wwo4-qim_ccciPvY:brxp9sd) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Nothing makes this difficult. I just didn't want to make any more changes than necessary.

I'm on the same page as you.  It would be best to implement the same mechanic for modeling options as for discrete variables. Doing so would allow the "TODO" to be removed.  And then, the way would be clear for a Simbody class that allocates modeling options externally to be wrapped in OpenSim as well.

I will go ahead and implement the same mechanic for modeling options as for discrete variables.
</blockquote></details>

Sounds good!


<!-- Sent from Reviewable.io -->

2024-03-29 00:49 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 4074 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2MlJp0cy7C-6u-GLU:-Nu6e5ZZ278HZ89NtE2R:b4h9ddi) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L4074)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Consider using`SimTK::SubsystemIndex` and accessing the subsystem when needed instead of carrying a pointer to the subsytem around in this struct.
</blockquote></details>

What are the advantages of using the `SimTK::SubsytemIndex` instead of the pointer to the subsystem?

Having the wrong `SubsystemIndex` would be just as catastrophic as the wrong subsytem pointer.  It might be worse actually.  Nothing would crash, you'd just get wrong numbers if you had the wrong `SubsystemIndex`.

Storing the SubsystemIndex would require a few lines of code every time you needed to acquire the pointer to the subsystem. In addition, we couldn't use `nullptr` as a clear signal that the `SimTK::DefaultSubsystem` should be used.

Just want to get this part straight before implementing the mechanic for modeling options.


<!-- Sent from Reviewable.io -->

2024-03-29 06:35 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 25 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.h` line 4074 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2MlJp0cy7C-6u-GLU:-Nu7silK0k4ZB2cJ3wt9:bwo2x2v) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L4074)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

What are the advantages of using the `SimTK::SubsytemIndex` instead of the pointer to the subsystem?

Having the wrong `SubsystemIndex` would be just as catastrophic as the wrong subsytem pointer.  It might be worse actually.  Nothing would crash, you'd just get wrong numbers if you had the wrong `SubsystemIndex`.

Storing the SubsystemIndex would require a few lines of code every time you needed to acquire the pointer to the subsystem. In addition, we couldn't use `nullptr` as a clear signal that the `SimTK::DefaultSubsystem` should be used.

Just want to get this part straight before implementing the mechanic for modeling options.
</blockquote></details>

I've messed around with the idea of using the subsystem index instead of the pointer. It's looking like the code could be quite simple. I just have to iron out one wrinkle.

Ideally, it would be good to initialize the subsystem index in `DiscreteVariableInfo` to the index for the SimTK::DefaultSubsystem.  This is not possible in the definition of `DiscreteVariableInfo`, but it would be possible to set the subsystem index in`addDiscreteVariable()`.

This would mean a more invasive changes to the original code, but I do think the changes would be good.


<!-- Sent from Reviewable.io -->

2024-03-29 10:54 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 4084 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2D4DB1vvjntt0BWrx:-Nu8q4522OnKMl4ExEHU:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L4084)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Consider my suggestion above to rephrase this sentence.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-29 11:03 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 4074 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2MlJp0cy7C-6u-GLU:-Nu8q7oO3j2C47t1YkMO:bbt451z) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L4074)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

I've messed around with the idea of using the subsystem index instead of the pointer. It's looking like the code could be quite simple. I just have to iron out one wrinkle.

Ideally, it would be good to initialize the subsystem index in `DiscreteVariableInfo` to the index for the SimTK::DefaultSubsystem.  This is not possible in the definition of `DiscreteVariableInfo`, but it would be possible to set the subsystem index in`addDiscreteVariable()`.

This would mean a more invasive changes to the original code, but I do think the changes would be good.
</blockquote></details>

I successfully switched to using the subsystem index instead of using the subsystem pointer. The code turned out to be simpler and is working fine. So, good recommendation on your part! I believe I've adjusted the comments to go along with this switch.

Before I bring the `ModelingOptionInfo` struct up to speed with the `DisctreteVariableInfo` struct, I'd like to make sure you are good with the changes I made.


<!-- Sent from Reviewable.io -->

2024-03-29 18:30 UTC, fcanderson commented
*[`OpenSim/Common/Component.cpp` line 601 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2F9mM1k0CJkUA9IW-:-NuAT4yy8lqb7okH5HHQ:b6ydn8j) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.cpp#L601)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Comments like these in the .cpp file won't appear in Doxygen, and ff they don't add anything new to the comments in the header file, then I would suggest removing them. (Same goes for the other comments below).
</blockquote></details>

Done.
I removed this comment and others like it. Pretty much all the comments just repeated what is explained by comments in the .h file.


<!-- Sent from Reviewable.io -->

2024-03-29 18:42 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 2 of 6 files reviewed, 25 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.cpp` line 601 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2F9mM1k0CJkUA9IW-:-NuAVsNyCveVYDxno55A:bk7c72v) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.cpp#L601)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Done.
I removed this comment and others like it. Pretty much all the comments just repeated what is explained by comments in the .h file.
</blockquote></details>

I also got rid of the lines marking the beginning of methods (i.e., "//_______________________ ...").
___
*[`OpenSim/Common/Component.cpp` line 625 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2LJhT3r9DXxScH5ai:-NuATaLt-Rd-xVwMZEkY:b-eazmz3) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.cpp#L625)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think the shorter comments like these could be removed too, if they are redundant with the header.
</blockquote></details>

Done.
Removed.
___
*[`OpenSim/Common/Component.cpp` line 639 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2HJ_--sHvFifFuzCW:-NuAU0WU9QU5xPTs5Jkh:b-ro1386) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.cpp#L639)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

// *this); ?
</blockquote></details>

Not sure what this is. It looks like very old code that just wasn't deleted.
Deleted.
___
*[`OpenSim/Common/Component.cpp` line 663 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2IJfW2Aq1_gyzr9ML:-NuAVXsg5qw97kEm8J7p:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.cpp#L663)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Pre-increment in these two lines.
</blockquote></details>

Done.
___
*[`OpenSim/Common/Component.cpp` line 670 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2JH1JBQaNhVP9RNr8:-NuAV7FD7dAGXqjFLG1H:bvhyz1z) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.cpp#L670)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Note this change in the `CHANGELOG.md`.
</blockquote></details>

I deleted this whole comment.
___
*[`OpenSim/Common/Component.cpp` line 1098 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2KPvIELMarvihsRRA:-NuAV-YT2siNC2D0Hq80:b-k7mx7q) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.cpp#L1098)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

// *this); ?
</blockquote></details>

Deleted.
___
*[`OpenSim/Common/Component.cpp` line 1121 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2L-YZ7e17fsSxxRLM:-NuAVhIc6hlZMBU-dnxO:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.cpp#L1121)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Pre-increment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-29 18:47 UTC, fcanderson commented
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 420 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu4zH8SBXnbuAIOM9T9:-NuAXNx-5IoWVYi-n4fZ:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L420)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

As suggested above, using `SimTK::SubsystemIndex` would be cleaner, if possible.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-29 19:04 UTC, nickbianco requested changes
@fcanderson, thanks for taking the time to swap to `SimTK::SubsystemIndex`. I think this solution is better overall. Most of the related change look good, I just have one suggestion about adding a new method to avoid changing the existing `DiscreteVariable` API.  

> Reviewed 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-:-NuAa4eP9JR2UVzl5cpT:b-s5sf64)* status: all files reviewed, 20 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Common/Component.h` line 4074 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2MlJp0cy7C-6u-GLU:-NuAZOIz7VjKahQ4vDFi:bpw73ko) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L4074)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

I successfully switched to using the subsystem index instead of using the subsystem pointer. The code turned out to be simpler and is working fine. So, good recommendation on your part! I believe I've adjusted the comments to go along with this switch.

Before I bring the `ModelingOptionInfo` struct up to speed with the `DisctreteVariableInfo` struct, I'd like to make sure you are good with the changes I made.
</blockquote></details>

While I wasn't 100% sure, I had a feeling that storing the `SimTK::SubsystemIndex` would be simpler. Stylistically it's cleaner, and I'm generally in favor of not passing around raw pointer whenever possible. My guess is that this was the intention of having type-specific indexes in Simbody in the first place. Glad that beared out to be true!
___
*[`OpenSim/Common/Component.h` line 3295 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuAWbyb9yHuZjDmECHD:-NuAWbyb9yHuZjDmECHE:bty4u10) ([raw file](https://github.com/opensim-org/opensim-core/blob/7167062ebd91d9715a9b443a0147ce47700c5326/OpenSim/Common/Component.h#L3295)):*
> ```objc
>      */
>     const std::pair<SimTK::SubsystemIndex, SimTK::DiscreteVariableIndex>
>     getDiscreteVariableIndices(const std::string& name) const;
> ```

To avoid changing the API, it would be better to add a new method that returns only the `SimTK::SubsystemIndex`, especially since you're just using the `DiscreteVariableInfo`s internally anyway. (Another option is to have a method that returns the `DiscreteVariableInfo` which has both pieces of information, but I'm not sure that's the best solution and maybe not scripting-friendly).
___
*[`OpenSim/Common/Component.h` line 3319 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuAYoPG0vsnGJpjs_Cq:-NuAYoPG0vsnGJpjs_Cr:b-jvzehf) ([raw file](https://github.com/opensim-org/opensim-core/blob/858cb5fef219793c953206a2d9f1d9003b4d1901/OpenSim/Common/Component.h#L3319)):*
> ```objc
>     * this Component.
>     */
>     void initializeDiscreteVariableIndices(const std::string& name,
> ```

Based on a suggestion from Sherm, I've started to adopt "indexes" to pluralize "index" instead of "indices". Both are grammatically valid, but "indexes" has the advantage of containing the original root word, which can make searching (e.g., in Doxygen) easier.
___
*[`OpenSim/Common/Component.h` line 4086 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuA_ec0EowBPjjvl1Wa:-NuA_ec0EowBPjjvl1Wb:bh4i4mp) ([raw file](https://github.com/opensim-org/opensim-core/blob/858cb5fef219793c953206a2d9f1d9003b4d1901/OpenSim/Common/Component.h#L4086)):*
> ```objc
> 
>         // Index of the discrete variable
>         SimTK::DiscreteVariableIndex dvIndex{-1};
> ```

The struct variables were right-aligned before this change.
___
*[`OpenSim/Common/Component.h` line 4097 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuA_kDN8eDfnKxwviPo:-NuA_kDN8eDfnKxwviPp:b-zfg5oh) ([raw file](https://github.com/opensim-org/opensim-core/blob/858cb5fef219793c953206a2d9f1d9003b4d1901/OpenSim/Common/Component.h#L4097)):*
> ```objc
>         // initializeDiscreteVariableIndices() in the most derived
>         // implementation of extendRealizeTopology().
>         SimTK::SubsystemIndex ssIndex{-1};
> ```

Right-align.
___
*[`OpenSim/Common/Component.cpp` line 1172 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuAWBWIDd56N6zPdfzD:-NuAWBWIDd56N6zPdfzE:b-83sjoh) ([raw file](https://github.com/opensim-org/opensim-core/blob/7167062ebd91d9715a9b443a0147ce47700c5326/OpenSim/Common/Component.cpp#L1172)):*
> ```cpp
> 
>     if (it != owner->_namedDiscreteVariableInfo.end()) {
>         return s.getDiscreteVariable(it->second.ssIndex, it->second.dvIndex);
> ```

Nice!


<!-- Sent from Reviewable.io -->

2024-03-29 19:23 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 3295 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuAWbyb9yHuZjDmECHD:-NuAbEmg1IYCDhhxO95g:bf21e1f) ([raw file](https://github.com/opensim-org/opensim-core/blob/7167062ebd91d9715a9b443a0147ce47700c5326/OpenSim/Common/Component.h#L3295)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

To avoid changing the API, it would be better to add a new method that returns only the `SimTK::SubsystemIndex`, especially since you're just using the `DiscreteVariableInfo`s internally anyway. (Another option is to have a method that returns the `DiscreteVariableInfo` which has both pieces of information, but I'm not sure that's the best solution and maybe not scripting-friendly).
</blockquote></details>

I weighed changing the API. A search revealed that this method is not used -anywhere- in OpenSim, not even in Component.h or Component.cpp.  And, all opensim-core code compiled and all tests passed after this API change.

The issue with making two methods is that the string-based map search would be done twice when it only needs to be done once to get both indexes. For computational reasons, at this low level especially, it seems important to reduce the number string-based searches.

Returning the DiscreteVariableInfo struct I think is a better solution than having to methods, but still represents an API change.

How about ...
Keep the original method as it was and label it deprecated.  And add `getDiscreteVariableIndexes()` as the recommended API?


<!-- Sent from Reviewable.io -->

2024-03-29 19:30 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 20 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.cpp` line 1172 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuAWBWIDd56N6zPdfzD:-NuAgHT01XRI-bnOxTAG:bos905v) ([raw file](https://github.com/opensim-org/opensim-core/blob/7167062ebd91d9715a9b443a0147ce47700c5326/OpenSim/Common/Component.cpp#L1172)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Always good when the code gets shorter.


<!-- Sent from Reviewable.io -->

2024-03-29 19:35 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 20 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.h` line 3319 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuAYoPG0vsnGJpjs_Cq:-NuAgZHKEHzoBqtuK1JL:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/858cb5fef219793c953206a2d9f1d9003b4d1901/OpenSim/Common/Component.h#L3319)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Based on a suggestion from Sherm, I've started to adopt "indexes" to pluralize "index" instead of "indices". Both are grammatically valid, but "indexes" has the advantage of containing the original root word, which can make searching (e.g., in Doxygen) easier.
</blockquote></details>

Done.
___
*[`OpenSim/Common/Component.h` line 4086 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuA_ec0EowBPjjvl1Wa:-NuAguTrAlW_BrCuHvpC:b6lwhyu) ([raw file](https://github.com/opensim-org/opensim-core/blob/858cb5fef219793c953206a2d9f1d9003b4d1901/OpenSim/Common/Component.h#L4086)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

The struct variables were right-aligned before this change.
</blockquote></details>

Are you saying that the member variable should be tabbed over?


<!-- Sent from Reviewable.io -->

2024-03-29 20:12 UTC, fcanderson commented
*[`OpenSim/Common/Component.h` line 3295 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuAWbyb9yHuZjDmECHD:-NuApbmW7hpZ0XwZ2M6W:b-q75v8l) ([raw file](https://github.com/opensim-org/opensim-core/blob/7167062ebd91d9715a9b443a0147ce47700c5326/OpenSim/Common/Component.h#L3295)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

To avoid returning an std::pair, the signature of the new method could instead be
```
void getDiscreteVariableIndexes(const std::string& name, SimTK::SubsystemIndex& ssIndex, SimTK::DiscreteVariableIndex& dvIndex);
```

</blockquote></details>

This would probably easier for someone to use.


<!-- Sent from Reviewable.io -->

2024-03-29 20:29 UTC, nickbianco requested changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 19 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Common/Component.h` line 3295 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuAWbyb9yHuZjDmECHD:-NuArqhJBHslTLAuJq8T:bpti3ul) ([raw file](https://github.com/opensim-org/opensim-core/blob/7167062ebd91d9715a9b443a0147ce47700c5326/OpenSim/Common/Component.h#L3295)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

This would probably easier for someone to use.
</blockquote></details>

I see, if it's not used anywhere (not surprising) then I agree that we should prioritize performance over reducing API changes. I think we could keep the original method without deprecating it, since it may be still useful if only the `DiscreteVariableIndex` is needed. 

And I agree that the signature for `getDiscreteVariableIndexes` with modifiable reference arguments seems better than using `std::pair`.
___
*[`OpenSim/Common/Component.h` line 4086 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuA_ec0EowBPjjvl1Wa:-NuArkQQ72V0cKpIA9g_:bye2jus) ([raw file](https://github.com/opensim-org/opensim-core/blob/858cb5fef219793c953206a2d9f1d9003b4d1901/OpenSim/Common/Component.h#L4086)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Are you saying that the member variable should be tabbed over?
</blockquote></details>

Yes, to be aligned with `invalidatesStage`.


<!-- Sent from Reviewable.io -->

2024-03-29 21:28 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 4 of 6 files reviewed, 19 unresolved discussions (waiting on @deprecated and @nickbianco)

___
*[`OpenSim/Common/Component.h` line 3295 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuAWbyb9yHuZjDmECHD:-NuB5TXjAGgYLkk4ZAUJ:bqy4nhr) ([raw file](https://github.com/opensim-org/opensim-core/blob/7167062ebd91d9715a9b443a0147ce47700c5326/OpenSim/Common/Component.h#L3295)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I see, if it's not used anywhere (not surprising) then I agree that we should prioritize performance over reducing API changes. I think we could keep the original method without deprecating it, since it may be still useful if only the `DiscreteVariableIndex` is needed. 

And I agree that the signature for `getDiscreteVariableIndexes` with modifiable reference arguments seems better than using `std::pair`.
</blockquote></details>

Done.
As you suggest, I removed the deprecated language from the Doxygen comments for `getDiscreteVariableIndex()`, and I changed the signature of `getDiscreteVariableIndexes()` to the one with modifiable index references.


<!-- Sent from Reviewable.io -->

2024-03-29 21:33 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 4 of 6 files reviewed, 19 unresolved discussions (waiting on @deprecated and @nickbianco)

___
*[`OpenSim/Common/Component.h` line 4086 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuA_ec0EowBPjjvl1Wa:-NuB7O3yDexCu4v7gUra:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/858cb5fef219793c953206a2d9f1d9003b4d1901/OpenSim/Common/Component.h#L4086)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Yes, to be aligned with `invalidatesStage`.
</blockquote></details>

Done.
___
*[`OpenSim/Common/Component.h` line 4097 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuA_kDN8eDfnKxwviPo:-NuB7SENAD_kscE2scV8:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/858cb5fef219793c953206a2d9f1d9003b4d1901/OpenSim/Common/Component.h#L4097)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Right-align.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-29 21:36 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 4 of 6 files reviewed, 19 unresolved discussions (waiting on @deprecated and @nickbianco)

___
*[`OpenSim/Common/Component.h` line 4074 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2MlJp0cy7C-6u-GLU:-NuB7Z1YBoX9f2RO7PaX:b-ba3s9f) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L4074)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

While I wasn't 100% sure, I had a feeling that storing the `SimTK::SubsystemIndex` would be simpler. Stylistically it's cleaner, and I'm generally in favor of not passing around raw pointer whenever possible. My guess is that this was the intention of having type-specific indexes in Simbody in the first place. Glad that beared out to be true!
</blockquote></details>

It looks like we are on good footing for `DiscreteVariableInfo` and related methods. I will now turn to making the same modifications for `ModelingOption`s.


<!-- Sent from Reviewable.io -->

2024-03-29 22:01 UTC, nickbianco reviewed
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 16 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Common/Component.h` line 3310 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuBDgPk8cfpohqJ-Ej6:-NuBDgPk8cfpohqJ-Ej7:b-c5ayhw) ([raw file](https://github.com/opensim-org/opensim-core/blob/26c8f372c978b30171c01186716acc9763111edc/OpenSim/Common/Component.h#L3310)):*
> ```objc
>      * which the discrete variable belongs.
>      * @param dvIndex Reference that returns the index of the discrete
>      * variable.
> ```

nit: Use `[in]` and `[out]` for input and output params.


<!-- Sent from Reviewable.io -->

2024-03-29 22:39 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 5 of 6 files reviewed, 15 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.h` line 3310 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuBDgPk8cfpohqJ-Ej6:-NuBM1fqB4QxIjYy2z-h:b-u596fa) ([raw file](https://github.com/opensim-org/opensim-core/blob/26c8f372c978b30171c01186716acc9763111edc/OpenSim/Common/Component.h#L3310)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: Use `[in]` and `[out]` for input and output params.
</blockquote></details>

Done.
Nice. Not something I've used before.


<!-- Sent from Reviewable.io -->

2024-03-29 22:48 UTC, fcanderson commented
*[`OpenSim/Tools/CMC.cpp` line 1101 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2EQ_ZCToikmUNkmzT:-NuBN6PyAyS2z7i7YOLU:bqf0cgt) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Tools/CMC.cpp#L1101)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I recently changed how `Controller`s manage their list of `Actuator`s (now uses a list `Socket`). If you think this assert is failing because of that, let me know and I can investigate.
</blockquote></details>

Yes. I believe the compile error is related.  In the `SimTK_ASSERT()` there is a call to `getActuatorSet()`, which appears is no longer available.
If the `getSize()` check is still important to do, it seems like `getActuatorSet()` should be replaced with the newer approach.

By the way, there are many asserts that fail when a `Debug` compile is performed. I imagine that folks know about this.


<!-- Sent from Reviewable.io -->

2024-03-29 23:51 UTC, nickbianco reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 15 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Tools/CMC.cpp` line 1101 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2EQ_ZCToikmUNkmzT:-NuBb0cI-hM_iocy3EDG:b-7knebq) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Tools/CMC.cpp#L1101)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Yes. I believe the compile error is related.  In the `SimTK_ASSERT()` there is a call to `getActuatorSet()`, which appears is no longer available.
If the `getSize()` check is still important to do, it seems like `getActuatorSet()` should be replaced with the newer approach.

By the way, there are many asserts that fail when a `Debug` compile is performed. I imagine that folks know about this.
</blockquote></details>

Replace `getActuatorSet().getSize()` with `getNumActuators()` should solve the issue here. I'm not aware of these failing asserts (I should get in the habit of creating debug builds more often!) -- are any others related to the `Controller` changes?


<!-- Sent from Reviewable.io -->

2024-03-30 00:15 UTC, fcanderson commented
*[`OpenSim/Tools/CMC.cpp` line 1101 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2EQ_ZCToikmUNkmzT:-NuBgmDiBcG_5YnTehyC:b-bfboxy) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Tools/CMC.cpp#L1101)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Replace `getActuatorSet().getSize()` with `getNumActuators()` should solve the issue here. I'm not aware of these failing asserts (I should get in the habit of creating debug builds more often!) -- are any others related to the `Controller` changes?
</blockquote></details>

Done.
Using getNumActuators() fixed the problem.

Once we finish this PR, I'll have another look at the assert failures and let you know what I see. There are maybe 6 to 10 unit tests that fail for a Debug build, if my memory serves me right. I didn't pay attention to which ones could be related to the `Controller` changes.


<!-- Sent from Reviewable.io -->

2024-03-30 00:22 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 4 of 6 files reviewed, 15 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1885 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52Tc_BHHyhBz9jVxr:-NuBeW89-IlK6XW8bUme:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1885)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

This line number could change in the future. Consider referring directly to`extendRealizeTopology` for the component instead.
</blockquote></details>

Done.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1934 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52x7rC033Jvuzh-Rc:-NuBdpCM4_PD25Ndk2eE:bkv5z0z) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1934)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove if no longer needed (e.g., from debugging).
</blockquote></details>

Done.
Good catch.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1952 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu531SY4OVxqqjqhHPL:-NuBf82h8itE3Llco14K:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1952)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Same as above, consider referring to `extendRealizeTopology` instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-30 00:44 UTC, nickbianco reviewed
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 12 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Tools/CMC.cpp` line 1101 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu2EQ_ZCToikmUNkmzT:-NuBo9Rf5AUbLpFLNJfB:bxve1dq) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Tools/CMC.cpp#L1101)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Done.
Using getNumActuators() fixed the problem.

Once we finish this PR, I'll have another look at the assert failures and let you know what I see. There are maybe 6 to 10 unit tests that fail for a Debug build, if my memory serves me right. I didn't pay attention to which ones could be related to the `Controller` changes.
</blockquote></details>

Sounds good! I agree, let's not go too far off-topic here.


<!-- Sent from Reviewable.io -->

2024-03-30 00:48 UTC, fcanderson commented
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1622 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu50l_l2GTGpWik_Ehz:-NuBnG1TEMzkBxh-7nZT:bvi3xkq) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1622)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: there is a lot of repitition here. Not sure if a helper function would reduce the number of lines needed, but something to consider.
</blockquote></details>

A helper function would allow about 60 lines of repetitive code to be removed, but the helper function would need to be about 15 lines longer (you'd have to do some `std::string` concatenations), for a net gain of about 45 lines removed.  But the code would probably be more difficult to read. I'm inclined to leave the code as is, but could be convinced otherwise.


<!-- Sent from Reviewable.io -->

2024-03-30 01:18 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 12 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 395 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu4yXrx9fPuUY8WZm2y:-NuBjcQlEQKDgsxCA-7s:bb6un1j) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L395)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

For clarity:
</blockquote></details>

Done
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1548 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu509InEzXPEjhOfw7w:-NuBpJdE4QYoK5eDDuHt:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1548)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

You could put everything under this comment in a Catch2 section: `SECTION("State Variables") { }`
</blockquote></details>

Done.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1624 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu50XFH-44pW5uGatwi:-NuBpMX7Clqrw3I4S2ku:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1624)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

`SECTION("Discrete Variables") { }`
</blockquote></details>

Done.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1700 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu51XNh665eyjKIdL5l:-NuBpOPL1papv23AWTto:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1700)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

`SECTION("Exceptions are thrown appropriately") { }`
</blockquote></details>

Done.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1736 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu527hz8dD6l0CukGZC:-NuBraNAE6pi2k2ENf04:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1736)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

`SECTION("Paths are correct") { }`
</blockquote></details>

Done.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1747 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu51q6834OoG5PYWtDi:-NuBrap8BFT0VzIi9SS8:b-tldau1) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1747)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

`SECTION("Setters") { }`
</blockquote></details>

The "sets" that are performed here are relied on by the "Getters", so it doesn't work to place them in a SECTION. 
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1754 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52---CHAHu6Xim50A:-NuBrbEsBpIrZk518-MM:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1754)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

`SECTION("Getters") { }`
</blockquote></details>

Done.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1795 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52B0A-xLWScHrsjvU:-NuBsG6B6YjLz96i6UAD:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1795)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

`SECTION("Paths are correct") { }`
</blockquote></details>

Done.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1806 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52Dv2-O6iT0nCfYWc:-NuBsGWp775HUiDac7fJ:b-tldau1) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1806)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

`SECTION("Setters") { }`
</blockquote></details>

The "sets" that are performed here are relied on by the "Getters", so it doesn't work to place them in a SECTION. 
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1811 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu52F7V50z-yg_9DVFC:-NuBsH2o2a7pZLsTsGTP:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1811)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

`SECTION("Getters") { }`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-30 01:45 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 5 of 6 files reviewed, 12 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1978 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu53W894ZohEM3-W1_n:-NuC0Jz4Cx7Kanh3KKRp:bin3v8q) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1978)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Consider changing the modeling option too (e.g., `false` when `i` is odd, `true` when even).
</blockquote></details>

Done.
Nice idea!


<!-- Sent from Reviewable.io -->

2024-03-30 01:56 UTC, fcanderson reviewed
@nickbianco, the code has really improved because of your thorough review. Thank you again!

I think I just have one large item left on my plate:
Now that `struct DiscreteVariableInfo` is on firm footing, I will migrate the analogous modifications over to `struct ModelingOptionInfo` so that it is possible for externally allocated `ModelingOption`s to be brought into OpenSim as well.

I plan on doing that tomorrow.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-:-NuC1O1fBc0zalWlQjjM:b-2c4mxq)* status: 5 of 6 files reviewed, 12 unresolved discussions (waiting on @nickbianco)



<!-- Sent from Reviewable.io -->

2024-03-30 03:29 UTC, nickbianco reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fcanderson)

___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 1622 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu50l_l2GTGpWik_Ehz:-NuCOaOlCHcZqZW4KO_8:bpdva2l) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Test/testComponentInterface.cpp#L1622)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

A helper function would allow about 60 lines of repetitive code to be removed, but the helper function would need to be about 15 lines longer (you'd have to do some `std::string` concatenations), for a net gain of about 45 lines removed.  But the code would probably be more difficult to read. I'm inclined to leave the code as is, but could be convinced otherwise.
</blockquote></details>

In that case, you can leave it as-is.


<!-- Sent from Reviewable.io -->

2024-03-30 17:34 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-NuFNNFb2AGJZk0M_Jn1:bvdiy0x) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Sounds good!
</blockquote></details>

Ok -  Externally allocated `ModelingOptions`s, like `DiscreteVariable`s, can be accommodated in OpenSim. There were a fair number of changes (sorry for the time it will take to review!), but a good portion of the changes were to make variable names more consistent and to polish the documentation for both `ModelingOption`s and `DiscreteVariable`s.

All tests are passing.

However, given that new methods and capabilities have been added, I really should now enhance the test cases in testComponentInterface.cpp. In particular, I should add a modeling option that is not allocated from the `SimTK::DefaultSubsystem` and test `initializeModelingOptionIndexes()`, `getModelingOptionIndexes()`, and `getDiscreteVariableIndexes()`. (`initializeDiscreteVariableIndexes()` is already being tested.)


<!-- Sent from Reviewable.io -->

2024-03-30 21:20 UTC, nickbianco requested changes
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 5 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-NuGDzas5qF9nqlgorCU:bvwpsst) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Ok -  Externally allocated `ModelingOptions`s, like `DiscreteVariable`s, can be accommodated in OpenSim. There were a fair number of changes (sorry for the time it will take to review!), but a good portion of the changes were to make variable names more consistent and to polish the documentation for both `ModelingOptions`s and `DiscreteVariable`s.

All tests are passing.

However, given that new methods and capabilities have been added, I really should now enhance the test cases in testComponentInterface.cpp. In particular, I should add a modeling option that is not allocated from the `SimTK::DefaultSubsystem` and test `initializeModelingOptionIndexes()`, `getModelingOptionIndexes()`, and `getDiscreteVariableIndexes()`. (`initializeDiscreteVariableIndexes()` is already being tested.)
</blockquote></details>

The new changes look great! Just a few minor comments. After the test updates we should be almost ready to merge.
___
*[`OpenSim/Common/Component.h` line 3201 at r14](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuGCH141Iq2uNb9UH9e:-NuGCH152L4qBHdKAxQu:b-mbdbf2) ([raw file](https://github.com/opensim-org/opensim-core/blob/63b530f0b8ebdd57dcb3a658aa1126b5317b434d/OpenSim/Common/Component.h#L3201)):*
> ```objc
>     allocated externally, in which case the derived Component (i.e., the
>     wrapping Component) is responsible for initializing the subsystem index
>     and discrete variable index in its own overriding implementation of
> ```

nit: Clarify that`discrete variable index` here refers to `SimTK::DiscreteVariableIndex` since a modeling option is just a special type of`DiscreteVariable`. 
___
*[`OpenSim/Common/Component.h` line 3398 at r14](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuGCi9p4GTurBNjCb2_:-NuGCi9p4GTurBNjCb2a:b-aozlzk) ([raw file](https://github.com/opensim-org/opensim-core/blob/63b530f0b8ebdd57dcb3a658aa1126b5317b434d/OpenSim/Common/Component.h#L3398)):*
> ```objc
>     * overriding method.
>     *
>     * See OpenSim::ExponentialContact::extendRealizedTopology() for an
> ```

I know that we will directly follow this PR with the `ExponentialContact` component addition, but since this is technically not merged yet, we should remove all references to `OpenSim::ExponentialContact` for now. Sorry for just noticing this!
___
*[`OpenSim/Common/Component.h` line 4192 at r14](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuGDI1Q7DK6ZWkBa45J:-NuGDI1Q7DK6ZWkBa45K:bpfimt1) ([raw file](https://github.com/opensim-org/opensim-core/blob/63b530f0b8ebdd57dcb3a658aa1126b5317b434d/OpenSim/Common/Component.h#L4192)):*
> ```objc
>         // Index of the SimTK::Subsystem to which this discrete variable
>         // belongs
>         SimTK::SubsystemIndex       ssIndex{-1};
> ```

nit: maybe it's the Reviewable diff formatting, but `ssIndex` doesn't look aligned with `dvIndex` below.
___
*[`OpenSim/Common/Component.cpp` line 659 at r14](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuGD_5g4wg71ZYUDvRA:-NuGD_5g4wg71ZYUDvRB:ba3dfna) ([raw file](https://github.com/opensim-org/opensim-core/blob/63b530f0b8ebdd57dcb3a658aa1126b5317b434d/OpenSim/Common/Component.cpp#L659)):*
> ```cpp
> 
>     if(it != _namedModelingOptionInfo.end()) {
>         //SimTK::DiscreteVariableIndex moIndex = it->second.moIndex;
> ```

Remove?
___
*[`OpenSim/Common/Component.cpp` line 679 at r14](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuGDaLe2AfKnEISCu1p:-NuGDaLe2AfKnEISCu1q:ba3dfna) ([raw file](https://github.com/opensim-org/opensim-core/blob/63b530f0b8ebdd57dcb3a658aa1126b5317b434d/OpenSim/Common/Component.cpp#L679)):*
> ```cpp
> 
>     if(it != _namedModelingOptionInfo.end()) {
>         //SimTK::DiscreteVariableIndex moIndex = it->second.moIndex;
> ```

Remove?


<!-- Sent from Reviewable.io -->

2024-03-30 22:30 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 5 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.h` line 3201 at r14](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuGCH141Iq2uNb9UH9e:-NuGQdggAXCbDVsrpaGg:byad17t) ([raw file](https://github.com/opensim-org/opensim-core/blob/63b530f0b8ebdd57dcb3a658aa1126b5317b434d/OpenSim/Common/Component.h#L3201)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: Clarify that`discrete variable index` here refers to `SimTK::DiscreteVariableIndex` since a modeling option is just a special type of`DiscreteVariable`.
</blockquote></details>

I meant to change the phrase "discrete variable index" to "modeling option index" here.  I don't think readers will be confused if the text here reads "modeling option index".  You bring up a good point though.  I do think readers might be confused when they see the signature of `initializeModelingOptionIndexes()`. So there, I have added a clarification about the index type.  See lines 3254-3255. 
___
*[`OpenSim/Common/Component.h` line 3398 at r14](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuGCi9p4GTurBNjCb2_:-NuGSgIAA4rUKZdOkSM8:b-dow81) ([raw file](https://github.com/opensim-org/opensim-core/blob/63b530f0b8ebdd57dcb3a658aa1126b5317b434d/OpenSim/Common/Component.h#L3398)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I know that we will directly follow this PR with the `ExponentialContact` component addition, but since this is technically not merged yet, we should remove all references to `OpenSim::ExponentialContact` for now. Sorry for just noticing this!
</blockquote></details>

Agreed.  Removed.
___
*[`OpenSim/Common/Component.h` line 4192 at r14](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuGDI1Q7DK6ZWkBa45J:-NuGTNrE4ezz2iCOKs4u:b-x9zmz0) ([raw file](https://github.com/opensim-org/opensim-core/blob/63b530f0b8ebdd57dcb3a658aa1126b5317b434d/OpenSim/Common/Component.h#L4192)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: maybe it's the Reviewable diff formatting, but `ssIndex` doesn't look aligned with `dvIndex` below.
</blockquote></details>

Nope. You're right. They weren't aligned.  I inserted an extra tab in front of all member variables. They should be aligned now.
___
*[`OpenSim/Common/Component.cpp` line 659 at r14](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuGD_5g4wg71ZYUDvRA:-NuGTvuh4i6eA5j-dzaR:bobclp9) ([raw file](https://github.com/opensim-org/opensim-core/blob/63b530f0b8ebdd57dcb3a658aa1126b5317b434d/OpenSim/Common/Component.cpp#L659)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Good catch. Removed.
___
*[`OpenSim/Common/Component.cpp` line 679 at r14](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuGDaLe2AfKnEISCu1p:-NuGTr6Y-EDuc_8VtP2t:bss4a2b) ([raw file](https://github.com/opensim-org/opensim-core/blob/63b530f0b8ebdd57dcb3a658aa1126b5317b434d/OpenSim/Common/Component.cpp#L679)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2024-03-30 22:37 UTC, nickbianco reviewed
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fcanderson)



<!-- Sent from Reviewable.io -->

2024-03-31 17:29 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-NuKTIY2EHqdLtJg-0h2:b-73q1dq) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

The new changes look great! Just a few minor comments. After the test updates we should be almost ready to merge.
</blockquote></details>

The new tests are in.

In the process of writing the new tests, I discovered that the `get*****Indexes()` methods were not catching cases when the specified variable was not found (in those cases garbage was being returned!).  So I inserted some `OPENSIM_THROW(VariableNotFound, ...)` statements. I updated the Doxygen comments.

I also realized that the `get*****Indexes()` methods are `protected`. They can only be called in derived `Component`s. That's a reason that `getDiscreteVariableIndex()` is not being called elsewhere!  Ha ha. And, actually, I think that I added `getDiscreteVariableIndex()` because I needed the index in class `ExponentialContact`.  `DiscreteVariableInfo` is `private`, so I couldn't do something like `info.index` to access the index directly.

Now that `Subsystem` can vary, it's probably a good idea to get rid of `getDiscreteVariableIndex()`. Using the index without having the correct `SubsystemIndex` would not necessarily cause an error; it would just give wrong results, which would be difficult to diagnose.

Only Component developers are ever going to use the `get*****Indexes()` methods.


<!-- Sent from Reviewable.io -->

2024-04-01 01:18 UTC, nickbianco requested changes
> Reviewed 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 2 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-NuMDXSa3dh7r1fXdTSf:b-wnlwr5) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

The new tests are in.

In the process of writing the new tests, I discovered that the `get*****Indexes()` methods were not catching cases when the specified variable was not found (in those cases garbage was being returned!).  So I inserted some `OPENSIM_THROW(VariableNotFound, ...)` statements. I updated the Doxygen comments.

I also realized that the `get*****Indexes()` methods are `protected`. They can only be called in derived `Component`s. That's a reason that `getDiscreteVariableIndex()` is not being called elsewhere!  Ha ha. And, actually, I think that I added `getDiscreteVariableIndex()` because I needed the index in class `ExponentialContact`.  `DiscreteVariableInfo` is `private`, so I couldn't do something like `info.index` to access the index directly.

Now that `Subsystem` can vary, it's probably a good idea to get rid of `getDiscreteVariableIndex()`. Using the index without having the correct `SubsystemIndex` would not necessarily cause an error; it would just give wrong results, which would be difficult to diagnose.

Only Component developers are ever going to use the `get*****Indexes()` methods.
</blockquote></details>

The changes to the tests look good! Just a few minor suggestions.

While only `Component` developer are likely to `getDiscreteVariableIndex()`, I think we should keep it since it has been in the API for a long time. You could add a note warning users that `getDiscreteVariableIndex` assumes the default Subsystem and to use `getDiscreteVariableIndexes` if they're not sure what Subsystem the variable comes from. 
___
*[`OpenSim/Common/Component.cpp` line 1505 at r16](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuMCQkh4jlyG_NNeCge:-NuMCQkh4jlyG_NNeCgf:b7ptda7) ([raw file](https://github.com/opensim-org/opensim-core/blob/4e37469a71375b558191854101839b871dd64158/OpenSim/Common/Component.cpp#L1505)):*
> ```cpp
>     it = _namedModelingOptionInfo.find(moName);
>     if (it == _namedModelingOptionInfo.end()) {
>         OPENSIM_THROW(VariableNotFound, getName(), moName);
> ```

nit: You could use the macro `OPENSIM_THROW_IF` for the check in this file to save a few lines. 
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 401 at r16](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuMChVBE_DeaVa2t4bI:-NuMChVBE_DeaVa2t4bJ:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/4e37469a71375b558191854101839b871dd64158/OpenSim/Common/Test/testComponentInterface.cpp#L401)):*
> ```cpp
>     }
> 
>     // Manually allocate and update the index and subsystem for any
> ```





_Suggestion:_
```cpp
    // Manually allocate and update the index and subsystem for
```


<!-- Sent from Reviewable.io -->

2024-04-01 03:12 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-NuMVMUs5wjq6sRigGNd:b-etvloe) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

The changes to the tests look good! Just a few minor suggestions.

While only `Component` developer are likely to `getDiscreteVariableIndex()`, I think we should keep it since it has been in the API for a long time. You could add a note warning users that `getDiscreteVariableIndex` assumes the default Subsystem and to use `getDiscreteVariableIndexes` if they're not sure what Subsystem the variable comes from.
</blockquote></details>

Since there is no code that I can find in opensim-core that calls `getDiscreteVariableIndex()` it seems like an ideal opportunity to remove it. Note also that there is no `getModelingOptionIndex()` method.

Do you think there could be Component code outside of opensim-core (plugins or something) that uses `getDiscreteVariableIndex()`?

Long-term, I think it's asking for more trouble to leave it in than remove it.

I left it in and revised the comment to emphasize the importance of getting the subsystem right. But if you change your mind on this, I'm happy to take it out.  :-)
___
*[`OpenSim/Common/Component.cpp` line 1505 at r16](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuMCQkh4jlyG_NNeCge:-NuMaQmLD6xMB8tbepSX:bk17bo2) ([raw file](https://github.com/opensim-org/opensim-core/blob/4e37469a71375b558191854101839b871dd64158/OpenSim/Common/Component.cpp#L1505)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: You could use the macro `OPENSIM_THROW_IF` for the check in this file to save a few lines.
</blockquote></details>

Nice. I replaced OPENSIM_THROW with OPENSIM_THROW_IF in several places.
___
*[`OpenSim/Common/Test/testComponentInterface.cpp` line 401 at r16](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-NuMChVBE_DeaVa2t4bI:-NuMatH005qki9M-mRQL:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4e37469a71375b558191854101839b871dd64158/OpenSim/Common/Test/testComponentInterface.cpp#L401)):*
> ```cpp
>     }
> 
>     // Manually allocate and update the index and subsystem for any
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-04-01 16:26 UTC, nickbianco reviewed
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fcanderson)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-NuPRPqw3TzYYF_QO5so:b-5130bj) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Since there is no code that I can find in opensim-core that calls `getDiscreteVariableIndex()` it seems like an ideal opportunity to remove it. Note also that there is no `getModelingOptionIndex()` method.

Do you think there could be Component code outside of opensim-core (plugins or something) that uses `getDiscreteVariableIndex()`?

Long-term, I think it's asking for more trouble to leave it in than remove it.

I left it in and revised the comment to emphasize the importance of getting the subsystem right. But if you change your mind on this, I'm happy to take it out.  :-)
</blockquote></details>

I do agree with your concerns, perhaps I'm being a bit too conservative here. I doubt much external code uses `getDiscreteVariableIndex` and wouldn't be surprised if there is none, but I couldn't say with full certainty that no external code uses it.

What would happen if someone used `getDiscreteVariableIndex` but the variable belonged to a different Subsystem than the default? Would that lead to an exception? If so, then I'm more inclined to leave it in. But if not, and that would allow for some unintended behavior, then I'd reconsider changing the API.


<!-- Sent from Reviewable.io -->

2024-04-01 17:39 UTC, nickbianco reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-NuPiuix3RwOomMTx-I8:bt5zaqf) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

If the wrong subsystem or subsystem index was used internally in `get` and `set` methods, which is where one would need the indexes, there are two possible outcomes, the first more likely than the second:

1) The value that was acquired or set would simply be the value for a different state in the System than intended. For example, I might be trying to set the value of a coefficient of friction in my contact model, but what I would be setting instead might be the fiber length of some muscle, the value of a continuous state derivative, or whether a coordinate is locked or unlocked.

2) The memory might not be owned by OpenSim and access violation might occur (a segmentation fault, out of bounds, etc) causing OpenSim to crash. It is possible the the SimTK::State does bounds checking, in which case an exception would likely be thrown, but in a release build I think most bounds checking is disabled for speed.

This is like setting an element in an array, but doing it in the wrong array. It may be allowed, just wrong.  Or, if the access is beyond the end of the array, a memory fault might occur. 

Because you don't know whether (1) or (2) would happen, you would not be able to count on an exception being thrown even if bounds checking is happening in SimTK::State.  Most of the time, you'd just be getting or setting wrong numbers.  This kind of thing would cause havoc in a simulation and may be quite difficult to track down. The wrong numbers might be reasonable looking.
</blockquote></details>

Based on these possible outcomes, I'm now more in favor of removing `getDiscreteVariableIndex`, but I think I'd still like a second reviewer input here.

@aymanhab, could you provide some input here? The short story: we are considering removing `getDiscreteVariableIndex` in favor of the new `getDiscreteVariableIndexes`, since discrete variables after this PR could be from a different `SimTK::Subsystem` than the default. This would mean changing the `Component` API, but would most likely would be safer going forward, since you would need to query `getDiscreteVariableIndexes` which returns both the correct `DiscreteVariableIndex` and the `SimTK::SubsystemIndex`. 


<!-- Sent from Reviewable.io -->

2024-04-01 20:56 UTC, fcanderson commented
Thanks @nickbianco for the excellent short story. I agree it would be good to get @aymanhab's take on this.

I would add ...
-  It doesn't look like any code in opensim-core calls `getDiscreteVariableIndex()` .
- There isn't a corresponding `getModelingOptionIndex()`, only a corresponding `getModelingOptionIndexes()`.

2024-04-02 07:15 UTC, aymanhab reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 1 unresolved discussion (waiting on @fcanderson and @nickbianco)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-NuSd_T713ioWDnwCmA_:b-iwlva9) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Based on these possible outcomes, I'm now more in favor of removing `getDiscreteVariableIndex`, but I think I'd still like a second reviewer input here.

@aymanhab, could you provide some input here? The short story: we are considering removing `getDiscreteVariableIndex` in favor of the new `getDiscreteVariableIndexes`, since discrete variables after this PR could be from a different `SimTK::Subsystem` than the default. This would mean changing the `Component` API, but would most likely would be safer going forward, since you would need to query `getDiscreteVariableIndexes` which returns both the correct `DiscreteVariableIndex` and the `SimTK::SubsystemIndex`.
</blockquote></details>

Thanks for the summary @nickbianco and @fcanderson I'd remove it. It's highly unlikely considering that we don't use it that others would, but more importantly the potential for a silent wrong return and/or side-effect would not be acceptable. 


<!-- Sent from Reviewable.io -->

2024-04-02 16:36 UTC, nickbianco reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab and @fcanderson)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-NuUeFOg7XQF69w3QZSe:boht0f7) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Thanks for the summary @nickbianco and @fcanderson I'd remove it. It's highly unlikely considering that we don't use it that others would, but more importantly the potential for a silent wrong return and/or side-effect would not be acceptable.
</blockquote></details>

Thanks for the input @aymanhab! Okay @fcanderson, let's go ahead and remove it.


<!-- Sent from Reviewable.io -->

2024-04-03 00:24 UTC, fcanderson reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @aymanhab and @nickbianco)

___
*[`OpenSim/Common/Component.h` line 2516 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-Nu25hSi6DnykH_M-mmf:-NuWJlCu9qpLxRUciGjQ:bpbt3xz) ([raw file](https://github.com/opensim-org/opensim-core/blob/1bf6a4bf931d2fa4b709a697ff4d2b6f47962bca/OpenSim/Common/Component.h#L2516)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Thanks for the input @aymanhab! Okay @fcanderson, let's go ahead and remove it.
</blockquote></details>

Yes, thank you @aymanhab for weighing in on the decision.

I removed `getDiscreteVariableIndex()` and noted its replacement by `getDiscreteVariableIndexes()`l in the CHANGELOG.md. I wasn't sure if something as down in the weeds as this small change should be noted in the CHANGELOG.md, but I reasoned that removal of a method from the API should be documented somewhere notable.


<!-- Sent from Reviewable.io -->

2024-04-03 19:38 UTC, fcanderson reviewed
No, no, no... Thank you @nickbianco! OpenSim has benefitted from your diligence and care.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3745#-:-Nu_S6gYBdMASzkgu8Ex:b-u2720l)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2024-04-04 17:59 UTC, merged

2024-04-04 18:01 UTC, fcanderson commented
Woo hoo! It has taken some time. It is good to see this code merged!