Added exceptions for when CasOCSolver solve() fails in MocoCasADiSolver
opensim-org/opensim-core pull request #3834
Opened 2024-07-02 18:00 UTC by AllisonJohn

Fixes issue #3730

### Brief summary of changes
Instead of continuing on, MocoCasADiSolver will throw exceptions when the solver doesn't fails so that the next lines don't cause more errors.

### Testing I've completed
Tested putting opensim, casadi, and std errors in the try section to see the error messages when running the sliding mass problem. Without the added errors it works normally.

### Looking for feedback on...

### CHANGELOG.md (choose one)

- to be updated.

2024-07-02 18:43 UTC, nickbianco requested changes
Great @AllisonJohn! I have mostly style suggestions.

In addition to the requested changes, could you provide screenshots of what each individual error message looks like when printed to the console?

2024-07-02 18:58 UTC, AllisonJohn commented on OpenSim/Moco/MocoCasADiSolver/MocoCasADiSolver.cpp
> +        OPENSIM_THROW_FRMOBJ(Exception, fmt::format("MocoCasADiSolver failed internally "
It fits without the , ex.getMessage())); part

2024-07-02 19:03 UTC, nickbianco commented on OpenSim/Moco/MocoCasADiSolver/MocoCasADiSolver.cpp
> +        OPENSIM_THROW_FRMOBJ(Exception, fmt::format("MocoCasADiSolver failed internally "
Gotcha. Then I'd go with:

```c++
OPENSIM_THROW_FRMOBJ(Exception, 
        fmt::format("MocoCasADiSolver failed internally with message: {}" , 
                ex.getMessage()));
```

2024-07-02 22:25 UTC, AllisonJohn commented
Here is what happens when adding each of these lines to the catch:

OPENSIM_THROW(Exception, "test opensim exception"); -> 
![image](https://github.com/opensim-org/opensim-core/assets/55262350/ac1152f7-c716-4350-b9b3-4ca3e5381198)

casadi_error("test casadi exception"); ->
![image](https://github.com/opensim-org/opensim-core/assets/55262350/984e62dc-eac0-4656-934e-7565d205c7e3)
"libc++abi: terminating due to uncaught exception of type OpenSim::Exception: MocoCasADiSolver failed internally with message: /Users/allisonjohn/Documents/opensim-core/OpenSim/Moco/MocoCasADiSolver/MocoCasADiSolver.cpp:388: test casadi exception
	In Object '<no-name>' of type MocoCasADiSolver.
	Thrown at MocoCasADiSolver.cpp:396 in solveImpl()."

throw std::invalid_argument("test exception"); ->
![image](https://github.com/opensim-org/opensim-core/assets/55262350/bbea71b4-ce61-4f0e-9e0c-483a6a960a14)

2024-07-03 17:54 UTC, nickbianco approved these changes
LGTM.

2024-07-03 17:54 UTC, merged