Add 'MocoCompositeOutputGoal' class
opensim-org/opensim-core pull request #3851
Opened 2024-07-16 23:54 UTC by AllisonJohn

Fixes issue #3848

### Brief summary of changes
New OutputGoal class that can add, subtract, multiply, divide two Outputs to create a new goal

### Testing I've completed
Added new tests to testMocoGoals.cpp

### Looking for feedback on...
- Should I put the string for the operator/combo in the enum to use for the print, or just store the string as I am doing now?
- Should I move anything from private to protected or vice versa in the composite class?
- Need to add any more tests?
- createSlidingMassModel() and createDoubleSlidingMassModel(), my new function, share a lot of code so I could decompose adding one sliding mass 

### CHANGELOG.md (choose one)

- to be updated

2024-07-17 16:49 UTC, AllisonJohn commented on OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp
> +    } else if (get_combo().compare("division") == 0) {
whoops I meant to change all of them to just == instead of compare

2024-07-17 16:55 UTC, AllisonJohn commented on OpenSim/Moco/MocoGoal/MocoOutputGoal.h
> +    OpenSim_DECLARE_PROPERTY(combo, std::string, "The operator to combine the "
I had to call it combo bc operator is unfortunately a keyword

2024-07-17 17:54 UTC, nickbianco reviewed
Great work @AllisonJohn! There are lots of comments and suggestions, but the bones of this new goal look really good. We just need to tidy things up a bit.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-:-O20osim5oAO4phgUp1D:b-i4bqh)* status: all files reviewed, 36 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 115 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20dXzvCjFf17fj5sEN:-O20dXzw2P0dBWYJfjaq:bmxkaxc) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L115)):*
> ```objc
>     }
> 
>     template <typename T>
> ```

Add doc comments here and for the accessors below. 
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 131 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20dgLNBL3VLNpVNHLV:-O20dgLNBL3VLNpVNHLW:bd24f0j) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L131)):*
> ```objc
>     }
> 
>     enum DataType {
> ```

Why did `DataType` need to be more to `protected`?
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 207 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20eKUj5JjshQDA-KNt:-O20eKUj5JjshQDA-KNu:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L207)):*
> ```objc
> SimTK::SpatialVec in the integrand of a goal. The first Output path is set using
> `setOutputPath()` and the second with `setSecondOutputPath()`. The two outputs can
> be combined by addition, subtraction, multiplication, or divison operators. The
> ```





_Suggestion:_
```objc
be combined by addition, subtraction, multiplication, or division operations. The
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 208 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20euHO6s-TVioq1hL-:-O20euHO6s-TVioq1hL0:b-70fgnn) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L208)):*
> ```objc
> `setOutputPath()` and the second with `setSecondOutputPath()`. The two outputs can
> be combined by addition, subtraction, multiplication, or divison operators. The
> first Output always on the left side of the operator and the second Output on
> ```

If we change the property to `operation`, we should use "operation" over "operator" everywhere in the documentation



_Suggestion:_
```objc
first Output always on the left side of the operation and the second Output on
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 214 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20f2AQDXMyE5L9vv8b:-O20f2AR9HaHHc28bvjr:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L214)):*
> ```objc
> 
> The two Outputs must be the same type. If the Outputs are SimTK::Vec3 or
> SimTK::Spatialvecan and an index is provided, the index will be applied to both
> ```





_Suggestion:_
```objc
SimTK::SpatialVec and an index is provided, the index will be applied to both
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 239 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20mDL-6PMmWpyT2Uw0:-O20mDL-6PMmWpyT2Uw1:baiyjao) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L239)):*
> ```objc
>     /** Set the operand to combine the outputs. It can be "addition",
>      * "subtraction", "multiplication", or "division". */
>     void setOperator(std::string combo) { set_combo(combo); }
> ```

We usually try to match the method name to the property name, whenever possible. See my comment below about changing the property to `operation`, which would then let us change this to `setOperation`.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 254 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20h7OF-PGxoo18q8u6:-O20h7OF-PGxoo18q8u7:bdtz1be) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L254)):*
> ```objc
> 
>     /** overrides base class calc method to combine the two outputs for any of
>      *  the three types and the chosen operator */
> ```

nit: Use sentence case for all Doxygen comments, even for protected and private members.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 255 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20hDs47hWYgxX8NL-9:-O20hDs47hWYgxX8NL-A:bxim3to) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L255)):*
> ```objc
>     /** overrides base class calc method to combine the two outputs for any of
>      *  the three types and the chosen operator */
>     double calcOutputValue(const SimTK::State&) const;
> ```

Rather than override `calcOutputValue`, I would just make this a new helper method for `MocoCompositeOutputGoal` (i.e., `calcOperationValue`.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 262 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#gh-1681385671:-O20dN1F4Bd147EZlqW3:b-2bulwc) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L262)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

I had to call it combo bc operator is unfortunately a keyword 
</blockquote></details>

I think `operation` would be a good alternative.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 267 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20gSrB0HQ93Y5gRROS:-O20gSrB0HQ93Y5gRROT:ba3dfmt) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L267)):*
> ```objc
> 
>     void constructProperties();
>     //double helpCalc(const SimTK::State&) const;
> ```

Remove.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 269 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20hXlq8QrV9Qro0GjJ:-O20hXlrEZUPmuyytpTm:bfu9so6) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L269)):*
> ```objc
>     //double helpCalc(const SimTK::State&) const;
> 
>     /** combine the two output values using the operator **/
> ```

Sentence case.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 270 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20jwePCduUeEZQDmn2:-O20jwePCduUeEZQDmn3:b8de2lg) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L270)):*
> ```objc
> 
>     /** combine the two output values using the operator **/
>     double combine(double value1, double value2) const {
> ```

Consider a method name that more clearly reflects the method, e.g., `applyOperation`.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 275 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20ha-v2xyfQU81yGyj:-O20ha-v2xyfQU81yGyk:brcne2i) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L275)):*
> ```objc
>             case subtraction    : return value1 - value2;
>             case multiplication : return value1 * value2;
>             default             : return value1 / value2;
> ```

nit: have this case use the division enum rather than `default`. It wouldn't hurt to raise an exception in the defaul [...]

2024-07-17 22:10 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: all files reviewed, 25 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 115 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20dXzvCjFf17fj5sEN:-O20u9xHDAslcsWLeUEq:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L115)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Add doc comments here and for the accessors below.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 131 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20dgLNBL3VLNpVNHLV:-O20tW2LByCm4OdTnYKg:b6w4kle) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L131)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Why did `DataType` need to be more to `protected`?
</blockquote></details>

MocoCompositeOutputGoal::calcOutputValue also uses the types
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 207 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20eKUj5JjshQDA-KNt:-O20udXa7rimBHlgwB7K:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L207)):*
> ```objc
> SimTK::SpatialVec in the integrand of a goal. The first Output path is set using
> `setOutputPath()` and the second with `setSecondOutputPath()`. The two outputs can
> be combined by addition, subtraction, multiplication, or divison operators. The
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 208 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20euHO6s-TVioq1hL-:-O20vDn8Anq_Bkt9vrR9:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L208)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

If we change the property to `operation`, we should use "operation" over "operator" everywhere in the documentation
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 214 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20f2AQDXMyE5L9vv8b:-O20vEQE3ZMTXuutH_DX:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L214)):*
> ```objc
> 
> The two Outputs must be the same type. If the Outputs are SimTK::Vec3 or
> SimTK::Spatialvecan and an index is provided, the index will be applied to both
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 239 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20mDL-6PMmWpyT2Uw0:-O20vHK_5sCR9necUU9B:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L239)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

We usually try to match the method name to the property name, whenever possible. See my comment below about changing the property to `operation`, which would then let us change this to `setOperation`.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 255 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20hDs47hWYgxX8NL-9:-O20xVRm17sCPCm0RdKC:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L255)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Rather than override `calcOutputValue`, I would just make this a new helper method for `MocoCompositeOutputGoal` (i.e., `calcOperationValue`.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 267 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20gSrB0HQ93Y5gRROS:-O20xyI59SQWYzZSVz48:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L267)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 269 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20hXlq8QrV9Qro0GjJ:-O20zx1f39FIf9RI-xRi:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L269)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Sentence case.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 270 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20jwePCduUeEZQDmn2:-O20zwL34oZG-M_VAHHK:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L270)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Consider a method name that more clearly reflects the method, e.g., `applyOperation`.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 280 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20hZnr3jHXn2RTEoZd:-O213dVQ9XcKxNzpJdrB:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L280)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Sentence case.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 195 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20j-P6C1qjf_Z_BoYJ:-O215-6ACFMUUG0rZwXB:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L195)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Either remove, or move to the if-else block where the error checking actually happens.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 204 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20jM6C3nJx-gBqx5bV:-O215E_SD2lhOvg_jddQ:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L204)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

+1 for these checks!
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 215 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20hqKc48yF_qP7jfO5:-O21N87q9Xn9zA6i1B1B:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L215)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Check that you are within the 80 column limit everywhere in this file.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 224 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20jVgH6mqErolVCykp:-O21NMVI8f_6ryk6ZbyH:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L224)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I don't t [...]

2024-07-17 22:16 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: 0 of 3 files reviewed, 26 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 293 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O21kgf7DHhlq3PsHLAR:-O21kgf7DHhlq3PsHLAS:b-vnvlgd) ([raw file](https://github.com/opensim-org/opensim-core/blob/f3d2dc2cf87448d7d8065c1d4694bffe78528db0/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L293)):*
> ```objc
>     /** Applies the operation to two Vec valuee. If the operation is addition or
>     subtraction, it will take the norm after the operator has been applied, and
>     if the operation is multiplication or division, the norm of both values will
> ```

valueS


<!-- Sent from Reviewable.io -->

2024-07-17 22:47 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: 0 of 3 files reviewed, 26 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 58 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O20obgk5CM9_EUrxGuB:-O21s-dc4yyNJXSTSoaR:b-297pb6) ([raw file](https://github.com/opensim-org/opensim-core/blob/4a7a4b667b4c7fcf69b5b4c27f5ee744d84a7edc/OpenSim/Moco/Test/testMocoGoals.cpp#L58)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

I tried this and it seemed to work but the result was not the same as the original version, it had a larger final distance. I left the original for now and the commented out new version. I'll look more into it
</blockquote></details>

Oh it was because the "createSlidingMass" body had mass 10 and the "createDoubleSlidingMass" bodies had mass 1


<!-- Sent from Reviewable.io -->

2024-07-17 23:42 UTC, nickbianco requested changes
Looking good! A few more formatting and typos fixes needed.

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-:-O223bKm2jyINtLbDWmd:b-svm783)* status: all files reviewed, 13 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 221 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O223JYd6ppqY7QGlEms:-O223JYd6ppqY7QGlEmt:b-3hu9bu) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L221)):*
> ```objc
> because this will cause divide by zero errors.
> 
> The two Outputs must be the same type. If the Outputs are SimTK::Vec3 or
> ```

Minor suggestion:



_Suggestion:_
```objc
The two Outputs can be different quantities, but they must be the same type. If the Outputs are SimTK::Vec3 or
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 264 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O21zRmT-7EJtWriTRPe:-O21zRmT-7EJtWriTRPf:bb7lc5i) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L264)):*
> ```objc
>     void printDescriptionImpl() const override;
> 
>     /** Gets the values of the two outputs at the given state and applies the
> ```

nit:



_Suggestion:_
```objc
    /** Calculates the values of the two outputs at the given state and applies the
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 274 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O21zOLL7aUxt2KIHgcl:-O21zOLL7aUxt2KIHgcm:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L274)):*
> ```objc
>             "integrand for this goal.");
>     OpenSim_DECLARE_PROPERTY(operation, std::string, "The operation to combine "
>             "the two outputs: 'additon', 'subtraction', 'multiplication', or "
> ```





_Suggestion:_
```objc
            "the two outputs: 'addition', 'subtraction', 'multiplication', or "
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 279 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O22-DlAAV08vghfwnIa:-O22-DlAAV08vghfwnIb:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L279)):*
> ```objc
>     void constructProperties();
> 
>     /** Applies the operation to two double values. **/
> ```





_Suggestion:_
```objc
    /** Apply the operation to two double values. **/
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 291 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O21zmyOCLLZRdcwAv8a:-O21zmyOCLLZRdcwAv8b:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L291)):*
> ```objc
>     }
> 
>     /** Applies the operation to two Vec valuee. If the operation is addition or
> ```





_Suggestion:_
```objc
    /** Apply the operation to two SimTK::Vec3 or SimTK::SpatialVec values. If the operation is addition or
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 198 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O222NxT5HnEMt32_0vr:-O222NxT5HnEMt32_0vs:b-1e0ak7) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L198)):*
> ```cpp
>     std::string componentPath, outputName, channelName, alias;
>     AbstractInput::parseConnecteePath(get_second_output_path(), componentPath,
>                                         outputName, channelName, alias);
> ```

Either only use two indents here, or align to the first argument:



_Suggestion:_
```cpp
    AbstractInput::parseConnecteePath(get_second_output_path(), componentPath,
                                      outputName, channelName, alias);
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 235 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2231Bd2ZBBE_3w-AV3:-O2231Be29IBGLkEe4wI:bhoh44b) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L235)):*
> ```cpp
>     if (getDataType() == Type_double) {
>         double value1 = getOutput<double>().getValue(state);
>         double value2 = static_cast<const Output<double>*>(m_second_output.get())
> ```

Consider adding a `setSecondOutput<T>`, to avoid a lot of the awkward indents here.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 258 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O222eoL8llwdWcVOl4Y:-O222eoL8llwdWcVOl4Z:b-25dc9u) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L258)):*
> ```cpp
>         } else {
>             double value1 = getOutput<SimTK::SpatialVec>().getValue(state)
>                                                 [getIndex1()][getIndex2()];
> ```

Does this fit in 80 columns? I like to break at the equal sign, if possible, in these cases.



_Suggestion:_
```cpp
            double value1 = 
                    getOutput<SimTK::SpatialVec>().getValue(state)[getIndex1()][getIndex2()];
```
___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 36 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O220BVmAukpFheGM8CR:-O220BVmAukpFheGM8CS:b-hlt5o) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/Test/testMocoGoals.cpp#L36)):*
> ```cpp
> 
> /// creates a mass on a slider and adds it to the model
> void addSlidingMass(Model& model, std::string name, double mass) {
> ```

Rather than adding this helper that only two other functions use, I would just revert `createSlidingMassModel` to what it original was, and in `createDoubleSlidingMass` just use a mass of 10 for the second mass.
___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 907 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O22011z4yRyW7MCs3ZQ:-O22011z4yRyW7MCs3ZR:b-1x2tb1) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/Test/testMocoGoals.cpp#L907)):*
> ```cpp
>             MocoInitialBounds(2), MocoFinalBounds(-5, 5));
> 
>         problem.setTimeBounds(0, 5);
> ```

nit: To be consistent with other Moco examples, set the time bounds before state and control bounds.


<!-- Sent from Reviewable.io -->

2024-07-18 17:21 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 274 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O21zOLL7aUxt2KIHgcl:-O25gqxv4cLIIk3qTkXi:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L274)):*
> ```objc
>             "integrand for this goal.");
>     OpenSim_DECLARE_PROPERTY(operation, std::string, "The operation to combine "
>             "the two outputs: 'additon', 'subtraction', 'multiplication', or "
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 279 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O22-DlAAV08vghfwnIa:-O25gxBf1n_daS1gOE9o:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L279)):*
> ```objc
>     void constructProperties();
> 
>     /** Applies the operation to two double values. **/
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 291 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O21zmyOCLLZRdcwAv8a:-O25h-2y99K3RrGA-qX9:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L291)):*
> ```objc
>     }
> 
>     /** Applies the operation to two Vec valuee. If the operation is addition or
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 198 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O222NxT5HnEMt32_0vr:-O25hA_k1XN2TBhipVc0:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L198)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Either only use two indents here, or align to the first argument:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 235 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2231Bd2ZBBE_3w-AV3:-O25oQioDI68xTJuk4_e:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L235)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Consider adding a `setSecondOutput<T>`, to avoid a lot of the awkward indents here.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 258 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O222eoL8llwdWcVOl4Y:-O25oTlZ2xye381C2ClP:betofa9) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L258)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Does this fit in 80 columns? I like to break at the equal sign, if possible, in these cases.
</blockquote></details>

it does not fit :(
___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 36 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O220BVmAukpFheGM8CR:-O25noM26iqZ1p0JFUec:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/81a9361dad3a3340f3203648fc4537ae386aac2e/OpenSim/Moco/Test/testMocoGoals.cpp#L36)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Rather than adding this helper that only two other functions use, I would just revert `createSlidingMassModel` to what it original was, and in `createDoubleSlidingMass` just use a mass of 10 for the second mass.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-18 23:27 UTC, nickbianco requested changes
@AllisonJohn great work with this refactor! I left the next round of comments.

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-:-O279xGiArCl4qh7kmKB:bhrepmm)* status: all files reviewed, 36 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 38 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26olvzCJ7E7u3RGPdF:-O26olvzCJ7E7u3RGPdG:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L38)):*
> ```objc
> 
> Goals can be composed of one or two Outputs. The optional second Output is included
> by using the methods 'setSecondOutputPath()' and 'setOperator()'. The Outputs
> ```





_Suggestion:_
```objc
Goals can be composed of one or two Outputs. The optional second Output can be 
included using the methods 'setSecondOutputPath()' and 'setOperator()'. The Output values
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 41 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26owFC4bUUGVGkocpi:-O26owFC4bUUGVGkocpj:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L41)):*
> ```objc
> can be combined by addition, subtraction, multiplication, or division. The first
> Output is always on the left side of the operation and the second Output on the
> right side. The two Outputs can be different quantities, but they must be the
> ```





_Suggestion:_
```objc
Output is always on the left hand side of the operation and the second Output on the
right hand side. The two Outputs can be different quantities, but they must be the
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 42 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O27-ZmQ04_vaQwGksM2:-O27-ZmQ04_vaQwGksM3:btmloni) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L42)):*
> ```objc
> Output is always on the left side of the operation and the second Output on the
> right side. The two Outputs can be different quantities, but they must be the
> same type.
> ```

Add another sentence here describing how vector types are handled.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 69 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O272ifY6j9AKIOD8cO9:-O272ifY6j9AKIOD8cOA:b-5mq2zv) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L69)):*
> ```objc
> 
>     /** Set the absolute path to the output in the model to use as the integrand
>     for this goal. The format is "/path/to/component|output_name". */
> ```

Update this based on my comment on the property below:



_Suggestion:_
```objc
    /** Set the absolute path to the Output in the model. The format is 
    "/path/to/component|output_name". */
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 76 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2733x-EYuFfXhtTccM:-O2733x-EYuFfXhtTccN:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L76)):*
> ```objc
>     format is "/path/to/component|output_name". This Output should have the same
>     type as the first Output. If providing a second Output, the user should also
>     set an operation. */
> ```





_Suggestion:_
```objc
    type as the first Output. If providing a second Output, the user must also
    provide an operation via `setOperation()`. */
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 86 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O271W3aDHPmYM1sQmcp:-O271W3aDHPmYM1sQmcq:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L86)):*
> ```objc
>     /** Set the operation to combine the outputs. It can be "addition",
>     "subtraction", "multiplication", or "division". If providing an operation,
>     the user should also set a second output path. */
> ```





_Suggestion:_
```objc
    /** Set the operation that combines Output values where two Outputs are 
    provided. The supported operations include "addition", "subtraction", 
    "multiplication", or "division". If providing an operation, the user 
    must also provide a second Output path. */
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 87 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26puDNEMwxKi5SAdMm:-O26puDNEMwxKi5SAdMn:b8a2kq9) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L87)):*
> ```objc
>     "subtraction", "multiplication", or "division". If providing an operation,
>     the user should also set a second output path. */
>     void setOperation(std::string operation) { set_operation(operation); }
> ```

Need `std::move` here, otherwise we make an unnecessary copy:



_Suggestion:_
```objc
    void setOperation(std::string operation) { set_operation(std::move(operation)); }
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 138 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O271yEvCx4zFOIChJuJ:-O271yEvCx4zFOIChJuK:b-ic48yt) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L138)):*
> ```objc
>     OpenSim_DECLARE_PROPERTY(output_path, std::string,
>             "The absolute path to the output in the model to use as the "
>             "integrand for this goal.");
> ```

I think we should rephrase this property string, since not all Output goals use the value in the integrand.



_Suggestion:_
```objc
            "The absolute path to the Output in the model (i.e., 
            "'/path/to/component|output_name'");
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 139 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26szGB7qFQ6Q6hPSg6:-O26szGB7qFQ6Q6hPSg7:bxgwop6) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L139)):*
> ```objc
>             "The absolute path to the output in the model to use as the "
>             "integrand for this goal.");
>     OpenSim_DECLARE_PROPERTY(second_output_path, std::string,
> ```

We can make these optional properties now. Note that after making this change, you should check to see if the property is empty rather than checking for an empty string: `!getProperty_second_output_path().empty()`



_Suggestion:_
```objc
    OpenSim_DECLARE_OPTIONAL_PROPERTY(second_output_path, std::string,
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 141 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O273zobDDQs92x3OPYx:-O273zobDDQs92x3OPYy:b-leulbg) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L141)):*
> ```objc
>     OpenSim_DECLARE_PROPERTY(second_output_path, std::string,
>             "The absolute path to the second output in the model to use as the "
>             "integrand for this goal.");
> ```

Update this property string based on the suggestion for "output_path" above.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 142 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26tZovCrZanvqAxG8G:-O26tZovCrZanvqAxG8H:b-3rzkch) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L142)):*
> ```objc
>             "The absolute path to the second output in the model to use as  [...]

2024-07-19 19:07 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: 0 of 3 files reviewed, 34 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 38 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26olvzCJ7E7u3RGPdF:-O2Aq__P7eP3mkF1eoLb:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L38)):*
> ```objc
> 
> Goals can be composed of one or two Outputs. The optional second Output is included
> by using the methods 'setSecondOutputPath()' and 'setOperator()'. The Outputs
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 41 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26owFC4bUUGVGkocpi:-O2AqgU04AdqY5j7dfOV:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L41)):*
> ```objc
> can be combined by addition, subtraction, multiplication, or division. The first
> Output is always on the left side of the operation and the second Output on the
> right side. The two Outputs can be different quantities, but they must be the
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 42 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O27-ZmQ04_vaQwGksM2:-O2ArikvEZ0E2MsINULd:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L42)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Add another sentence here describing how vector types are handled.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 69 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O272ifY6j9AKIOD8cO9:-O2AryDn37rQQaKKiScE:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L69)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Update this based on my comment on the property below:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 76 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2733x-EYuFfXhtTccM:-O2As9nE6xKa2Auv9r0j:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L76)):*
> ```objc
>     format is "/path/to/component|output_name". This Output should have the same
>     type as the first Output. If providing a second Output, the user should also
>     set an operation. */
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 86 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O271W3aDHPmYM1sQmcp:-O2AsWrY0jgOHqejsR-e:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L86)):*
> ```objc
>     /** Set the operation to combine the outputs. It can be "addition",
>     "subtraction", "multiplication", or "division". If providing an operation,
>     the user should also set a second output path. */
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 87 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26puDNEMwxKi5SAdMm:-O2AsXCP6GqgrKo6Nia2:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L87)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Need `std::move` here, otherwise we make an unnecessary copy:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 138 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O271yEvCx4zFOIChJuJ:-O2AsmPAAYZhMK0GdBZW:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L138)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think we should rephrase this property string, since not all Output goals use the value in the integrand.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 139 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26szGB7qFQ6Q6hPSg6:-O2Awbep6bTHJygqVwMF:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L139)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

We can make these optional properties now. Note that after making this change, you should check to see if the property is empty rather than checking for an empty string: `!getProperty_second_output_path().empty()`
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 141 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O273zobDDQs92x3OPYx:-O2Awjoy0C-lZgnkGvB_:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L141)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Update this property string based on the suggestion for "output_path" above.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 142 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26tZovCrZanvqAxG8G:-O2Awlq74qpMM9lyZkcR:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L142)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Make an optional property.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 170 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O274Tpr0RegSDlc_yGr:-O2Ax-Gn9LPKR1M7TwxI:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L170)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Keep the same tense:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 175 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O274Z4aBUF8IHwOmL1r:-O2Ax-m76F5QnWFQ7bxt:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L175)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Keep the same tense:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 193 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26v2s-AULkbhaAOV2c:-O2AxAi44YsPfcvkorO2:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L193)):*
> ```objc
>     }
> 
>     /** Apply the operation to two Vec valuee. If the operation is addition or
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 198 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O26y3U75lKTrbNfLz2p:-O2AxPRwEzBDM2oOIRhC:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b95ce9b78c866154007d88c8a9bdf2d795eadd3c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L198)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Based on my comments below, I think these arguments should be const references:
</blockquote></details [...]

2024-07-19 21:25 UTC, nickbianco requested changes
@AllisonJohn just a few more minor changes and then we'll be good to go.

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-:-O2Bsa0f7rjrvTwtW98z:b-vppwly)* status: all files reviewed, 2 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 55 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2Bocnx0W_5GX_GWD5W:-O2Bocnx0W_5GX_GWD5X:b-erijag) ([raw file](https://github.com/opensim-org/opensim-core/blob/7f20ceaec11fc48878885a3ae624d55cff97f8a8/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L55)):*
> ```objc
> @Note For two Outputs of Vec type without an index, the norm will be applied *after*
> the element-wise operation. However, for multiplication and division of SpatialVec
> Outputs, an index *must* be supplied.
> ```

I think this addition could be combined with the above paragraph, rather than being made a note. Also, this is the first place that we mention that multiplication and division are applied elementwise for vector types, so I think this could be rephrasing to make that clearer.

"If two Outputs of SimTK::Vec3 type are provided and no index is specified, the operation will be applied elementwise before computing the norm. Elementwise multiplication and division operations are not supported when using two SimTK::SpatialVec Outputs (i.e., an index must be provided)." 
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 158 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2Br2YP5IXuZiszw5nK:-O2Br2YP5IXuZiszw5nL:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/7f20ceaec11fc48878885a3ae624d55cff97f8a8/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L158)):*
> ```cpp
>                 (m_operation == Multiplication || m_operation == Division),
>                 Exception, "Multiplication and division operations are not "
>                 "allowed with Output type SimTK::SpatialVec without an index.")
> ```





_Suggestion:_
```cpp
                "supported with Output type SimTK::SpatialVec without an index.")
```


<!-- Sent from Reviewable.io -->

2024-07-19 22:16 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 55 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2Bocnx0W_5GX_GWD5W:-O2C3J0y5FYn908WJeIH:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/7f20ceaec11fc48878885a3ae624d55cff97f8a8/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L55)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think this addition could be combined with the above paragraph, rather than being made a note. Also, this is the first place that we mention that multiplication and division are applied elementwise for vector types, so I think this could be rephrasing to make that clearer.

"If two Outputs of SimTK::Vec3 type are provided and no index is specified, the operation will be applied elementwise before computing the norm. Elementwise multiplication and division operations are not supported when using two SimTK::SpatialVec Outputs (i.e., an index must be provided)."
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 158 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2Br2YP5IXuZiszw5nK:-O2C-uqC7JvONdCNjYCr:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/7f20ceaec11fc48878885a3ae624d55cff97f8a8/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L158)):*
> ```cpp
>                 (m_operation == Multiplication || m_operation == Division),
>                 Exception, "Multiplication and division operations are not "
>                 "allowed with Output type SimTK::SpatialVec without an index.")
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-19 22:38 UTC, nickbianco requested changes
@AllisonJohn, a few more nit-picky changes for clarity and then I think we're done for real.

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-:-O2C8HliEKvcPSGONy2J:b78ex98)* status: all files reviewed, 3 unresolved discussions (waiting on @AllisonJohn)

___
*[`CHANGELOG_MOCO.md` line 7 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2C4_zU1qfFVPvkg_oL:-O2C4_zU1qfFVPvkg_oM:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/eda545bdf48c61a85ab2df755d3c55eae6aaee48/CHANGELOG_MOCO.md#L7)):*
> ```Markdown
> -----
> - 2024-07-19: Added support for `MocoOutputGoal`s that are composed of two `Output`s. This applies
>               to all types of Output goals (initial, final, etc.). The two `Output`s can be 
> ```





_Suggestion:_
```Markdown
              to all types of Output goals (`MocoInitialOutputGoal`, `MocoFinalOutputGoal`, etc.). The two `Output`s can be
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 53 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2C7AsRCXC0RCEl9fdH:-O2C7AsRCXC0RCEl9fdI:b6sq5ib) ([raw file](https://github.com/opensim-org/opensim-core/blob/eda545bdf48c61a85ab2df755d3c55eae6aaee48/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L53)):*
> ```objc
> norm of the vector will be used when calling 'calcOutputValue()'.
> 
> If using two Outputs, the same index will be applied to both before the operation.
> ```

Tried to improve clarity a bit more here.



_Suggestion:_
```objc
If using two Outputs, the Output index will be used to select the same element from both Outputs before the operation is applied.
```
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 54 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2C63Re7aeWDe_3ndeR:-O2C63Re7aeWDe_3ndeS:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/eda545bdf48c61a85ab2df755d3c55eae6aaee48/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L54)):*
> ```objc
> 
> If using two Outputs, the same index will be applied to both before the operation.
> If two Outputs of vector type are provided and no index is specified, the
> ```





_Suggestion:_
```objc
If two Outputs of type SimTK::Vec3 or SimTK::SpatialVec are provided and no index is specified, the
```


<!-- Sent from Reviewable.io -->

2024-07-19 22:50 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[`CHANGELOG_MOCO.md` line 7 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2C4_zU1qfFVPvkg_oL:-O2C9djy7kOQFh74NceR:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/eda545bdf48c61a85ab2df755d3c55eae6aaee48/CHANGELOG_MOCO.md#L7)):*
> ```Markdown
> -----
> - 2024-07-19: Added support for `MocoOutputGoal`s that are composed of two `Output`s. This applies
>               to all types of Output goals (initial, final, etc.). The two `Output`s can be 
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 53 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2C7AsRCXC0RCEl9fdH:-O2CA0nl14VDhkDGPlq5:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/eda545bdf48c61a85ab2df755d3c55eae6aaee48/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L53)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Tried to improve clarity a bit more here.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 54 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2C63Re7aeWDe_3ndeR:-O2CABf95_oClpKR1YLc:b-gis0cj) ([raw file](https://github.com/opensim-org/opensim-core/blob/eda545bdf48c61a85ab2df755d3c55eae6aaee48/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L54)):*
> ```objc
> 
> If using two Outputs, the same index will be applied to both before the operation.
> If two Outputs of vector type are provided and no index is specified, the
> ```

the previous paragraph said "vector types" so I was following that but I could change that one to be more specific too


<!-- Sent from Reviewable.io -->

2024-07-19 23:16 UTC, nickbianco requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 54 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2C63Re7aeWDe_3ndeR:-O2CH3aIAT4Bw8ITaOd5:biurzbo) ([raw file](https://github.com/opensim-org/opensim-core/blob/eda545bdf48c61a85ab2df755d3c55eae6aaee48/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L54)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

the previous paragraph said "vector types" so I was following that but I could change that one to be more specific too
</blockquote></details>

Yes, let's make that change too.


<!-- Sent from Reviewable.io -->

2024-07-19 23:31 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: all files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 95 at r9](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2CKL7b3HF0GYNW8eOj:-O2CKL7b3HF0GYNW8eOk:bhfznqo) ([raw file](https://github.com/opensim-org/opensim-core/blob/e29f78d4c9ede0ec56f7dd1d8014f6edff3d06e3/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L95)):*
> ```objc
>     void setOperation(std::string operation) {
>         set_operation(std::move(operation));
>     }
> ```

Should I add a getOperation()?


<!-- Sent from Reviewable.io -->

2024-07-19 23:42 UTC, nickbianco reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: all files reviewed, 2 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 95 at r9](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2CKL7b3HF0GYNW8eOj:-O2CN5ul2yYkQ0ST2SMM:buu1ztu) ([raw file](https://github.com/opensim-org/opensim-core/blob/e29f78d4c9ede0ec56f7dd1d8014f6edff3d06e3/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L95)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Should I add a getOperation()?
</blockquote></details>

Ah yes, good catch!


<!-- Sent from Reviewable.io -->

2024-07-20 00:15 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: all files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 54 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2C63Re7aeWDe_3ndeR:-O2COAeB0IltuC8_B7X6:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/eda545bdf48c61a85ab2df755d3c55eae6aaee48/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L54)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Yes, let's make that change too.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 95 at r9](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2CKL7b3HF0GYNW8eOj:-O2COeOi6E8W_tk-KPvG:bj6iix7) ([raw file](https://github.com/opensim-org/opensim-core/blob/e29f78d4c9ede0ec56f7dd1d8014f6edff3d06e3/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L95)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Ah yes, good catch!
</blockquote></details>

at first I thought it should error if they try to get it before setting it, but then the behavior would be different from the other properties which just return the default value, so I made it also return the empty string.


<!-- Sent from Reviewable.io -->

2024-07-22 16:37 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 95 at r9](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2CKL7b3HF0GYNW8eOj:-O2QEL0F6qY8Kf5aZFpM:be6rdve) ([raw file](https://github.com/opensim-org/opensim-core/blob/e29f78d4c9ede0ec56f7dd1d8014f6edff3d06e3/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L95)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

at first I thought it should error if they try to get it before setting it, but then the behavior would be different from the other properties which just return the default value, so I made it also return the empty string.
</blockquote></details>

actually since there were errors with const reference I un-optionaled the operator and second output path properties. But I could put them back as optionals and throw the error in the getter


<!-- Sent from Reviewable.io -->

2024-07-22 17:02 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 51 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2QO4DK8ki7q9YMqMjY:-O2QO4DK8ki7q9YMqMjZ:bg7lnvc) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8b3620586f095d38ea3b252552a0781b56d39f8/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L51)):*
> ```objc
> When using SimTK::Vec3 or SimTK::SpatialVec types, 'setOutputIndex()' may be
> used to select a specific element of the Output vector. If no index is specified
> specified, the norm of the vector will be used when calling 'calcOutputValue()'.
> ```

wrote specified twice


<!-- Sent from Reviewable.io -->

2024-07-22 20:17 UTC, nickbianco requested changes
@AllisonJohn, one more small typo to fix, then I think we're good to merge.

> Reviewed 1 of 3 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-:-O2R4lSS8FFTLaOhBld6:b-eqw174)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 127 at r11](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2R4_Uy7cNG850sEJTQ:-O2R4_Uy7cNG850sEJTR:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/a460de6b204ce83faee44c65054e750939c9318b/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L127)):*
> ```cpp
>                 "provide an operation"));
>     } else {
>         OPENSIM_THROW_FRMOBJ(Exception, fmt::format("Invalid operator: '{}', must "
> ```





_Suggestion:_
```cpp
        OPENSIM_THROW_FRMOBJ(Exception, fmt::format("Invalid operation: '{}', must "
```


<!-- Sent from Reviewable.io -->

2024-07-22 20:36 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 127 at r11](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2R4_Uy7cNG850sEJTQ:-O2R9Dw4Dqv6dTVXMtQL:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/a460de6b204ce83faee44c65054e750939c9318b/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L127)):*
> ```cpp
>                 "provide an operation"));
>     } else {
>         OPENSIM_THROW_FRMOBJ(Exception, fmt::format("Invalid operator: '{}', must "
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-22 20:56 UTC, nickbianco approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 27 at r12](https://reviewable.io/reviews/opensim-org/opensim-core/3851#-O2RDjtwB-foLULjYHa6:-O2RDjtwB-foLULjYHa7:b6zrrk4) ([raw file](https://github.com/opensim-org/opensim-core/blob/7ac6ac305cfee24cf643d284bbe694a57102dba5/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L27)):*
> ```objc
> /** This abstract base class provides convenience methods and common interfaces
> for all Output-related MocoGoal's. All MocoGoal's deriving from this class
> include the 'setOutputPath()', 'setSecondOutputPath()', 'setOperation()',
> ```

Good catch!


<!-- Sent from Reviewable.io -->

2024-07-22 20:57 UTC, nickbianco commented
Great work @AllisonJohn! I'll merge after tests are passing.

2024-07-22 22:56 UTC, nickbianco approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3851)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)



<!-- Sent from Reviewable.io -->

2024-07-22 23:36 UTC, merged