Drop std::iterator from ComponentListIterator
opensim-org/opensim-core pull request #3852
Opened 2024-07-17 14:39 UTC by adamkewley

Drop std::iterator from ComponentListIterator and make ComponentList (+iter) more algorithm-compatible

This is related to `opensim-creator`, which is compiled using `/W4` on MSVC.

One warning that's emitted by high-warning-levels is the deprecation of `std::iterator`.  The compiler will throw a tantrum when compiling with OpenSim's headers because `ComponentListIterator` uses the deprecated pattern. I currently disable this warning with `/wd4996` ([explanation(https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-170)) but that also disables other deprecation warnings.

The more modern way of achieving the same goal is to implement typedefs on `ComponentListIterator` such that `std::iterator_traits` will work with it. I did that (and it worked), but I also found that `ComponentListIterator` doesn't strictly abide by the iterator that it advertises via the traits (namely `std::forward_iterator_tag`). Those requirements are listed here:

- https://en.cppreference.com/w/cpp/named_req/ForwardIterator
- https://en.cppreference.com/w/cpp/named_req/InputIterator
- https://en.cppreference.com/w/cpp/named_req/Iterator

Specifically, the most important requirements are things like "can copy-construct and copy-assign the iterator". They're important because some of the algorithms in `<algorithm>` may depend on it. So I also implemented the minimum of those requirements, which required changing reference members (not copy-assignable) to pointers. This also led to an "optimization" where a `nullptr` means that the implementation can skip calling into a filter object (and skip allocating a "let everything through" filter), which is why this PR is messier than the bare-minimum of adding the necessary typedefs.

Fixes issue #<issue_number>

- N/A

### Brief summary of changes

- Added `std::iterator_traits<It>` typedefs
- Added `static_assert` tests into the test suite to verify the `ComponentListIterator` is suitable for generic algorithms (initially failed)
- Changed data members in `ComponentListIterator`  (the `static_asserts` then passed)
- Added a null check onto the `_filter` member (most common case - doing this avoids memory allocation, virtual method calling, etc.)

### Testing I've completed

- The `static_assert`s
- The remainder of the codebase is very sensitive to changes in this class's behavior, so I'm *guessing* that any faults in the logic would pop up 

### Looking for feedback on...

### CHANGELOG.md (choose one)

- no need to update because mostly internal change? (could mention it, if we want to be pedantic about dropping `std::iterator`)

2024-07-18 11:42 UTC, adamkewley commented on OpenSim/Common/Component.h
> +                                !(!_filter || _filter->isMatch(*_node)) ||
This change is to accomodate the fact that `_filter` is now optional (nullable) - it's an extra branch vs the original code but prevents the implementation from hopping into a virtual function, heap-allocating a clone of a filter object, etc.

2024-07-19 21:46 UTC, nickbianco requested changes
One minor question about possibly removing`ComponentFilterMatchAll`. Otherwise looks good.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3852#-:-O2BxKhjCvmiNhNDEBfn:b-xsmlvz)* status: all files reviewed, 2 unresolved discussions (waiting on @adamkewley)

___
*[`OpenSim/Common/ComponentList.h` line 192 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3852#-O2BwuOlDzwvLm8uhCBC:-O2BwuOlDzwvLm8uhCBD:b-s195oa) ([raw file](https://github.com/opensim-org/opensim-core/blob/f38669b70e807b140ab240ba631a7c20550bb46b/OpenSim/Common/ComponentList.h#L192)):*
> ```objc
>     // Internal method to setFilter to ComponentFilterMatchAll if no user specified
>     // filter is provided.
>     void setDefaultFilter() { setFilter(ComponentFilterMatchAll()); }
> ```

Does it make sense to remove`ComponentFilterMatchAll` now? Or is it used elsewhere?


<!-- Sent from Reviewable.io -->

2024-07-22 12:37 UTC, adamkewley commented
> Does it make sense to remove`ComponentFilterMatchAll` now? Or is it used elsewhere?

@nickbianco  I think it makes sense to drop it in this location - good spot!

I'd otherwise just keep the original class (`ComponentFilterMatchAll`) hanging around in case some downstream code happens to use it

2024-07-22 13:50 UTC, adamkewley commented
Ah sorry @nickbianco , my misunderstanding (it's already removed) - I think we should keep it around and only drop it during a breaking version change (OpenSim5 or similar)

2024-07-22 21:44 UTC, nickbianco approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3852)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-07-22 21:44 UTC, nickbianco approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3852#-:-O2ROifF-6uptjpLHyyC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-07-22 21:44 UTC, nickbianco approved these changes
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3852)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @adamkewley)



<!-- Sent from Reviewable.io -->

2024-07-22 21:45 UTC, nickbianco commented
Whoops, didn't mean to approve this three times haha. Anyway, good to merge!

2024-07-22 21:45 UTC, merged