[WIP] Add MocoStateBoundConstraint class
opensim-org/opensim-core pull request #3858
Opened 2024-07-24 19:18 UTC by AllisonJohn

Fixes issue #3857

### Brief summary of changes
Created MocoStateBoundConstraint class which is heavily based on MocoControlBoundConstraint

### Testing I've completed
added to testMocoConstraints

### Looking for feedback on...
changing the stage to realize to something with getDependsOnStage?
need any more test cases?
if the changes to the cmake file and the #includes in the test file are ok

### CHANGELOG.md (choose one)

- to be updated.

2024-07-24 22:51 UTC, nickbianco requested changes
@AllisonJohn, all looks pretty good. The only thing missing is that we should update the bindings so this new class is accessible in Python and Matlab. Let me know if you want a refresher on that.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-:-O2agEhp-hb71H6_5XqB:b-27285b)* status: all files reviewed, 13 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 2 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2ahuLh99ziMHE8_lCp:-O2ahuLh99ziMHE8_lCq:b-l6cd42) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L2)):*
> ```objc
> #ifndef MOCOSTATEBOUNDCONSTRAINT_H
> #define MOCOSTATEBOUNDCONSTRAINT_H
> ```

Match the header guard convention in other files:



_Suggestion:_
```objc
#ifndef OPENSIM_STATEBOUNDCONSTRAINT_H
#define OPENSIM_STATEBOUNDCONSTRAINT_H
```
___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 5 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2ahEBS6lv8SqWDn5WP:-O2ahEBS6lv8SqWDn5WQ:bppazdz) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L5)):*
> ```objc
> /* -------------------------------------------------------------------------- *
>  * OpenSim Moco: MocoStateBoundConstraint.cpp                               *
>  * -------------------------------------------------------------------------- *
> ```

It looks like at some point we removed "Moco" from the include file headers.



_Suggestion:_
```objc
/* -------------------------------------------------------------------------- *
 * OpenSim: MocoStateBoundConstraint.h                                        *
 * -------------------------------------------------------------------------- *
```
___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 8 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2arNPA32TZ3xlVcxhC:-O2ah1nZ16a4xL0QcbYm:bn8kyo9) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L8)):*
> ```objc
>  * Copyright (c) 2024 Stanford University and the Authors                     *
>  *                                                                            *
>  * Author(s): Christopher Dembia, Allsion John                                *
> ```

I know you borrowed a lot from the other class, but you should take sole authorship credit here :)



_Suggestion:_
```objc
 *                                                                            *
 * Author(s): Allison John                    twtwtw                                *
```
___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 26 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2ahmPLDqNSXqgXoeZz:-O2ahmPLDqNSXqgXoe_-:bfdtk7x) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L26)):*
> ```objc
> /** This path contraint allows you to bound any number of state variables
> between two time-based functions. It is possible to constrain the state variable
> to match the value from a provided function; see the equality_with_lower property.
> ```

Check 80 column limit on these two lines.
___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 108 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2ai2hi0dTUAdKZXyAB:-O2ai2hi0dTUAdKZXyAC:baz1740) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L108)):*
> ```objc
> } // OpenSim
> 
> #endif //MOCOSTATEBOUNDCONSTRAINT_H
> ```

Header guard convention:



_Suggestion:_
```objc
#endif // OPENSIM_STATEBOUNDCONSTRAINT_H
```
___
*[`OpenSim/Moco/MocoStateBoundConstraint.cpp` line 2 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2arsOWBEXdxoL1k0KT:-O2arsOWBEXdxoL1k0KU:b7en3nd) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.cpp#L2)):*
> ```cpp
> /* -------------------------------------------------------------------------- *
> * OpenSim Moco: MocoStateBoundConstraint.cpp                               *
> ```

Align asterisks:



_Suggestion:_
```cpp
/* -------------------------------------------------------------------------- *
 * OpenSim Moco: MocoStateBoundConstraint.cpp                                 *
```
___
*[`OpenSim/Moco/MocoStateBoundConstraint.cpp` line 6 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2aryu93Lex292fQui-:-O2aryu93Lex292fQui0:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.cpp#L6)):*
> ```cpp
>  * Copyright (c) 2024 Stanford University and the Authors                     *
>  *                                                                            *
>  * Author(s): Christopher Dembia, Allison John                                *
> ```





_Suggestion:_
```cpp
 *                                                                            *
 * Author(s): Allison John                                                    *
```
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 19 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2agmUw-UjiMEWOMAIk:-O2agmUw-UjiMEWOMAIl:bla65ro) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L19)):*
> ```cpp
>  * -------------------------------------------------------------------------- */
> 
> #include "OpenSim/Moco/MocoStateBoundConstraint.h"
> ```

You shouldn't need this include with `<OpenSim/Moco/osimMoco.h>` below.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 21 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2agsSr55OvP6eJOmnF:-O2agsSr55OvP6eJOmnG:bme937r) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L21)):*
> ```cpp
> #include "OpenSim/Moco/MocoStateBoundConstraint.h"
> #include "Testing.h"
> #include <catch2/catch_all.hpp>
> ```

I'd move these two includes back underneath the OpenSim library includes.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1621 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2avqi29tcVZ-qvH-Uc:-O2avqi29tcVZ-qvH-Ud:bw07ku8) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1621)):*
> ```cpp
> }
> 
> TEMPLATE_TEST_CASE("MocoStateBoundConstraint", "",
> ```

Can you add the two additional unit tests that `MocoControlBoundConstraint` has? They are labeled "Time range of bounds function is too small" and "Can omit both bounds".
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1650 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2auzP2DG7pIeZTyTLG:-O2auzP2DG7pIeZTyTLH:b-q78nb1) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1650)):*
> ```cpp
>             time[0] = times[i];
>             double max = upperBound.calcValue(time);
>             CHECK(speed < max + 1e-6);
> ```

To apply a margin to a numerical comparison, instead use [Catch2's floating point matchers](https://github.com/catchorg/Catch2/blob/devel/docs/comparing-floating-point-numbers.md).
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1692 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2avbTg5KE1WDYgkIIy:-O2avbTg5KE1WDYgkIIz:bc87v0g) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc [...]

2024-07-24 22:54 UTC, nickbianco requested changes
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858)* status: all files reviewed, 13 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 8 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2awpIH03-Rzaw6hwQG:-O2awpIH03-Rzaw6hwQH:begix3g) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L8)):*
> ```objc
>  * Copyright (c) 2024 Stanford University and the Authors                     *
>  *                                                                            *
>  * Author(s): Christopher Dembia, Allsion John                                *
> ```

(I messed up the diff on my first comment, trying again here)

I know you borrowed a lot from the other class, but you should take sole authorship credit here :)



_Suggestion:_
```objc
 *                                                                            *
 * Author(s): Allison John                                                    *
```


<!-- Sent from Reviewable.io -->

2024-07-24 22:59 UTC, nickbianco requested changes
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858)* status: all files reviewed, 13 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1692 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2avbTg5KE1WDYgkIIy:-O2axTLz-69qCGfc87Eh:b8qjzgx) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1692)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Use Catch2 matchers (see comment above).
</blockquote></details>

Is this the tightest tolerance you can meet with an equality constraint here? You might consider a smooth function (e.g., Sine or PolynomialFunction) rather than a piecewise linear function to get a better result here.


<!-- Sent from Reviewable.io -->

2024-07-25 00:08 UTC, AllisonJohn reviewed
Yeah I don't know how to do that

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-:-O2bCpGsDlpq19T93b47:b-px1ff7)* status: 2 of 6 files reviewed, 13 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 2 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2ahuLh99ziMHE8_lCp:-O2azOE42vrLYb29RkpH:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L2)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Match the header guard convention in other files:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 5 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2ahEBS6lv8SqWDn5WP:-O2azYLm-_uGT9kC2QBG:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L5)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

It looks like at some point we removed "Moco" from the include file headers.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 8 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2awpIH03-Rzaw6hwQG:-O2b-3J5EqrH81T5CX1U:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L8)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

(I messed up the diff on my first comment, trying again here)

I know you borrowed a lot from the other class, but you should take sole authorship credit here :)
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 26 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2ahmPLDqNSXqgXoeZz:-O2b-8vVA4C6kUhe4oEW:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L26)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Check 80 column limit on these two lines.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 108 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2ai2hi0dTUAdKZXyAB:-O2b-BU3Aw0IYlGFbdbC:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.h#L108)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Header guard convention:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoStateBoundConstraint.cpp` line 2 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2arsOWBEXdxoL1k0KT:-O2b-KSX5zz8Eibi8MIt:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.cpp#L2)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Align asterisks:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoStateBoundConstraint.cpp` line 6 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2aryu93Lex292fQui-:-O2b-MFv2CRSQ4hi0LVO:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/MocoStateBoundConstraint.cpp#L6)):*
> ```cpp
>  * Copyright (c) 2024 Stanford University and the Authors                     *
>  *                                                                            *
>  * Author(s): Christopher Dembia, Allison John                                *
> ```

Done.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 19 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2agmUw-UjiMEWOMAIk:-O2b1q5HC80oZY-NrjXv:b-ohtunx) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L19)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

You shouldn't need this include with `<OpenSim/Moco/osimMoco.h>` below.
</blockquote></details>

oh I needed to add it to osimMoco.h. Should I also add it to RegisterTypes_osimMoco.cpp?
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 21 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2agsSr55OvP6eJOmnF:-O2b2jx_2RDA8HTZLQZH:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L21)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I'd move these two includes back underneath the OpenSim library includes.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1621 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2avqi29tcVZ-qvH-Uc:-O2bCGlg3pycMd7zB02v:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1621)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Can you add the two additional unit tests that `MocoControlBoundConstraint` has? They are labeled "Time range of bounds function is too small" and "Can omit both bounds".
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1650 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2auzP2DG7pIeZTyTLG:-O2b4GHq2pYOrDLWyUAR:bd1qt86) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1650)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

To apply a margin to a numerical comparison, instead use [Catch2's floating point matchers](https://github.com/catchorg/Catch2/blob/devel/docs/comparing-floating-point-numbers.md).
</blockquote></details>

I think that would work for the equality bound but I'm not sure how to use matchers for an upper bound
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1692 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2avbTg5KE1WDYgkIIy:-O2b8IqB8sg0vmIuaoEI:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1692)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Is this the tightest tolerance you can meet with an equality constraint here? You might consider a smooth function (e.g., Sine or PolynomialFunction) rather than a piecewise linear function to get a better result here.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1728 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2avhV72kFM_BAAIy1c:-O2b7XY76AnWU8eZQwDr:bzfs1rs) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1728)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Use Catch2 matchers (see comment above).
</blockquote></details>

Once again since it's not really matching either the max or the min I don't think I can use it


<!-- Sent from Reviewable.io -->

2024-07-25 16:57 UTC, nickbianco requested changes
A few more minor comments. 

To update the bindings, you need to add a line to [`moco.i`](https://github.com/opensim-org/opensim-core/blob/main/Bindings/moco.i) and [`OpenSimHeaders_moco.h`](https://github.com/opensim-org/opensim-core/blob/main/Bindings/OpenSimHeaders_moco.h) for the new class.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-:-O2enpnuD8Ya6A4OifEs:b-qrnfqj)* status: all files reviewed, 5 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/CMakeLists.txt` line 114 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2eo_ahDCxQdsolEn9d:-O2eo_ahDCxQdsolEn9e:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/af697ea40bd4c3c4c7e9450b9c3be31849d911b4/OpenSim/Moco/CMakeLists.txt#L114)):*
> ```CMake
>         MocoStateBoundConstraint.cpp
>         MocoStateBoundConstraint.h
> )
> ```





_Suggestion:_
```CMake
        MocoStateBoundConstraint.h
        )
```
___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 109 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2eg5n62HeswoIG94t6:-O2eg5n62HeswoIG94t7:bhbvffb) ([raw file](https://github.com/opensim-org/opensim-core/blob/af697ea40bd4c3c4c7e9450b9c3be31849d911b4/OpenSim/Moco/MocoStateBoundConstraint.h#L109)):*
> ```objc
> } // namespace OpenSim
> 
> #endif //OPENSIM_MOCOSTATEBOUNDCONSTRAINT_H
> ```

Add a space:



_Suggestion:_
```objc
#endif // OPENSIM_MOCOSTATEBOUNDCONSTRAINT_H
```
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 19 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2agmUw-UjiMEWOMAIk:-O2egE6Q96oEiKQ36Q9C:b-z2lrf5) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L19)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

oh I needed to add it to osimMoco.h. Should I also add it to RegisterTypes_osimMoco.cpp?
</blockquote></details>

Yes, we should do that too.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1650 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2auzP2DG7pIeZTyTLG:-O2en-o24gt_gIqyqcLl:b-cioxji) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1650)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

I think that would work for the equality bound but I'm not sure how to use matchers for an upper bound
</blockquote></details>

It's technically deprecated in Catch, but you could do something like `CHECK(Catch::Approx(speed) <= max)`.  Does the test fail if you just did `CHECK(speed <= max)`?
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1674 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2egZk4DZ98OI6KXoxN:-O2egZk4DZ98OI6KXoxO:b5ilx27) ([raw file](https://github.com/opensim-org/opensim-core/blob/af697ea40bd4c3c4c7e9450b9c3be31849d911b4/OpenSim/Moco/Test/testMocoConstraints.cpp#L1674)):*
> ```cpp
>         lowerBound.addPoint(6, 0);
>         lowerBound.addPoint(7, -1);
>         lowerBound.addPoint(8, 0);*/
> ```

Remove this commented out code (if it will no longer be used).


<!-- Sent from Reviewable.io -->

2024-07-25 18:17 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858)* status: all files reviewed, 5 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/CMakeLists.txt` line 114 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2eo_ahDCxQdsolEn9d:-O2f34kH4VQzrQ8sUSuF:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/af697ea40bd4c3c4c7e9450b9c3be31849d911b4/OpenSim/Moco/CMakeLists.txt#L114)):*
> ```CMake
>         MocoStateBoundConstraint.cpp
>         MocoStateBoundConstraint.h
> )
> ```

Done.
___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 109 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2eg5n62HeswoIG94t6:-O2f3EVW7U3voEcBxUpG:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/af697ea40bd4c3c4c7e9450b9c3be31849d911b4/OpenSim/Moco/MocoStateBoundConstraint.h#L109)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Add a space:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 19 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2agmUw-UjiMEWOMAIk:-O2f3b1L-FqbKgKS-yJw:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L19)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Yes, we should do that too.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1650 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2auzP2DG7pIeZTyTLG:-O2f5agxEZiJhFq41Gxz:b-svgf7) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1650)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

It's technically deprecated in Catch, but you could do something like `CHECK(Catch::Approx(speed) <= max)`.  Does the test fail if you just did `CHECK(speed <= max)`?
</blockquote></details>

Oh it does work, I guess I only tried < before
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1674 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2egZk4DZ98OI6KXoxN:-O2f5lza-qbI9Ot6O1XQ:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/af697ea40bd4c3c4c7e9450b9c3be31849d911b4/OpenSim/Moco/Test/testMocoConstraints.cpp#L1674)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove this commented out code (if it will no longer be used).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-25 18:27 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 67 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2f7p4e0idK-vZTfeSE:-O2f7p4f7AeDwl4Db_mV:b-oiugso) ([raw file](https://github.com/opensim-org/opensim-core/blob/f1950229749901b7cd50dca98620d837691dda14/OpenSim/Moco/MocoStateBoundConstraint.h#L67)):*
> ```objc
>     void clearLowerBound() { updProperty_lower_bound().clear(); }
>     bool hasLowerBound() const { return !getProperty_lower_bound().empty(); }
>     const Function& getLowerBound() const { return get_lower_bound(); }
> ```

This throws a weird error if you call it before the bound has been set:
SimTK Exception thrown at Array.h:563:
  Index out of range in ArrayViewConst_<T>::at(): expected 0 <= size_type(i) < 0 but size_type(i)=0.

In OutputConstraint/Goal we fixed it by making the properties non-optional, but since I copied this from ControlBoundConstraint I kept it optional


<!-- Sent from Reviewable.io -->

2024-07-25 20:17 UTC, nickbianco requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858)* status: all files reviewed, 3 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 67 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2f7p4e0idK-vZTfeSE:-O2fXFUoEDxztoDL6OpA:b-wvhp3r) ([raw file](https://github.com/opensim-org/opensim-core/blob/f1950229749901b7cd50dca98620d837691dda14/OpenSim/Moco/MocoStateBoundConstraint.h#L67)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

This throws a weird error if you call it before the bound has been set:
SimTK Exception thrown at Array.h:563:
  Index out of range in ArrayViewConst_<T>::at(): expected 0 <= size_type(i) < 0 but size_type(i)=0.

In OutputConstraint/Goal we fixed it by making the properties non-optional, but since I copied this from ControlBoundConstraint I kept it optional
</blockquote></details>

If it's the same behavior as `MocoControlBoundConstraint`, then it's fine, we can keep it as-is.
___
*[`OpenSim/Moco/RegisterTypes_osimMoco.cpp` line 114 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2fXNtI34yCqVcY5o4s:-O2fXNtI34yCqVcY5o4t:blhxszu) ([raw file](https://github.com/opensim-org/opensim-core/blob/f1950229749901b7cd50dca98620d837691dda14/OpenSim/Moco/RegisterTypes_osimMoco.cpp#L114)):*
> ```cpp
>         Object::registerType(MocoTropterSolver());
> 
>         Object::registerType(MocoControlBoundConstraint());
> ```

You also need to add a line here:



_Suggestion:_
```cpp
        Object::registerType(MocoControlBoundConstraint());
        Object::registerType(MocoStateBoundConstraint());
```
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1650 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2auzP2DG7pIeZTyTLG:-O2fXdcD6uamdHvLRw_0:b-olm3q2) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1650)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Oh it does work, I guess I only tried < before
</blockquote></details>

As discussed, use `Catch::Approx` here and below to resolve the CI failure.


<!-- Sent from Reviewable.io -->

2024-07-25 20:40 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/RegisterTypes_osimMoco.cpp` line 114 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2fXNtI34yCqVcY5o4s:-O2fbvam9Wkw0U_LZXz0:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f1950229749901b7cd50dca98620d837691dda14/OpenSim/Moco/RegisterTypes_osimMoco.cpp#L114)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

You also need to add a line here:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 1650 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2auzP2DG7pIeZTyTLG:-O2fbFS21azaO31ENnP3:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/37edccdd4cc75807c94773901e3d4539693fef22/OpenSim/Moco/Test/testMocoConstraints.cpp#L1650)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

As discussed, use `Catch::Approx` here and below to resolve the CI failure.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-25 21:34 UTC, nickbianco approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)



<!-- Sent from Reviewable.io -->

2024-07-26 16:39 UTC, nickbianco requested changes
Found another typo.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-:-O2juI_m5shN19EAxnHj:bnwbnoq)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 8 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2juBwA0DkcLFhGxo6a:-O2juBwA0DkcLFhGxo6b:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/1a7fb950ab2bc89370b94dcabd8b338b47a8479d/OpenSim/Moco/MocoStateBoundConstraint.h#L8)):*
> ```objc
>  * Copyright (c) 2024 Stanford University and the Authors                     *
>  *                                                                            *
>  * Author(s): Christopher Dembia, Allsion John                                *
> ```





_Suggestion:_
```objc
/* -------------------------------------------------------------------------- *
 * OpenSim Moco: MocoStateBoundConstraint.cpp                                 *
 * -------------------------------------------------------------------------- *
 * Copyright (c) 2024 Stanford University and the Authors                     *
 *                                                                            *
 * Author(s): Allison John                                                    *
```


<!-- Sent from Reviewable.io -->

2024-07-26 17:08 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 8 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2juBwA0DkcLFhGxo6a:-O2k-ocj4f0Rbd51yajD:btl5kje) ([raw file](https://github.com/opensim-org/opensim-core/blob/1a7fb950ab2bc89370b94dcabd8b338b47a8479d/OpenSim/Moco/MocoStateBoundConstraint.h#L8)):*
> ```objc
>  * Copyright (c) 2024 Stanford University and the Authors                     *
>  *                                                                            *
>  * Author(s): Christopher Dembia, Allsion John                                *
> ```

whoops I think my other typo made me confuse which file I fixed


<!-- Sent from Reviewable.io -->

2024-07-26 17:13 UTC, nickbianco approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3858)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoStateBoundConstraint.h` line 8 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3858#-O2juBwA0DkcLFhGxo6a:-O2k10Cy7jN48-svegAH:b-cujjk0) ([raw file](https://github.com/opensim-org/opensim-core/blob/1a7fb950ab2bc89370b94dcabd8b338b47a8479d/OpenSim/Moco/MocoStateBoundConstraint.h#L8)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

whoops I think my other typo made me confuse which file I fixed
</blockquote></details>

All good!


<!-- Sent from Reviewable.io -->

2024-07-26 19:01 UTC, nickbianco commented
Great work @AllisonJohn!

2024-07-26 19:01 UTC, merged