Add `ModOpPrescribedMotion` class
opensim-org/opensim-core pull request #3862
Opened 2024-07-29 23:02 UTC by AllisonJohn

Fixes issue #3559

### Brief summary of changes
Added a type of model operator `ModOpPrescribedMotion` which can prescribe motion to a joint based on motion data from a file. 

### Testing I've completed
One test where a slider must copy the position of the slider in the previous problem.
Will add a test with more layers in the path

### Looking for feedback on...
Should the path to the coordinate in the model have to be the same as the path to the coordinate in the data?

### CHANGELOG.md (choose one)
- to be updated.

2024-07-30 00:04 UTC, AllisonJohn commented
There is an issue with the createSlidingMassModel() declaration because the current version in github has it already but my branch wasn't up to date

2024-07-30 23:20 UTC, AllisonJohn commented
Hmm I thought if I marked it ready it might let me manage the merge conflicts

2024-07-30 23:59 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`OpenSim/Actuators/ModelOperators.h` line 234 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O354IRg0FTKoliH1Ywm:-O354IRg0FTKoliH1Ywn:b-ujjqib) ([raw file](https://github.com/opensim-org/opensim-core/blob/93a1e3f411afb0d1b8c3fc71bb616ed942bb3a4a/OpenSim/Actuators/ModelOperators.h#L234)):*
> ```objc
>         model.finalizeFromProperties();
>         GCVSplineSet statesSpline(table);
>         for (std::size_t i = 0; i < getProperty_coordinate_paths().size(); ++i) {
> ```

I made this a size_t bc there was a warning about comparing int to size type, but there is still another warning 


<!-- Sent from Reviewable.io -->

2024-07-31 17:44 UTC, nickbianco requested changes
I left a few review comments based on discussion on Slack that might be helpful. 

> Hmm I thought if I marked it ready it might let me manage the merge conflicts

I'm not seeing any merge conflicts; let me know if this is still an issue.

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-:-O38swfx1Sa-KlqZ8kHp:b-ns4h3s)* status: all files reviewed, 4 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Actuators/ModelOperators.h` line 234 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O354IRg0FTKoliH1Ywm:-O38rfGi-ZUTnabJS1Cr:b-rpeuf0) ([raw file](https://github.com/opensim-org/opensim-core/blob/93a1e3f411afb0d1b8c3fc71bb616ed942bb3a4a/OpenSim/Actuators/ModelOperators.h#L234)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

I made this a size_t bc there was a warning about comparing int to size type, but there is still another warning
</blockquote></details>

This will change based on my comment above, but for future reference, you can do the following to avoid the warning:



_Suggestion:_
```objc
        for (int i = 0; i < static_cast<int>(getProperty_coordinate_paths().size()); ++i) {
```
___
*[`OpenSim/Actuators/ModelOperators.h` line 216 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38qCIb7hvcaAQSlcYc:-O38qCIb7hvcaAQSlcYd:bg787k6) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Actuators/ModelOperators.h#L216)):*
> ```objc
> /// Each path must begin with "/jointset" and end with "/value", so ensure that
> /// joints are added as Joints and not Components.
> class OSIMACTUATORS_API ModOpPrescribedMotion : public ModelOperator {
> ```

We should make the name of this ModelOperator more active. Consider something like `ModOpPrescribeCoordinateValues` to more clearly indicate what the operator is doing.
___
*[`OpenSim/Actuators/ModelOperators.h` line 220 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38rCBO04JRZatjG6bO:-O38rCBO04JRZatjG6bP:bsj0x6l) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Actuators/ModelOperators.h#L220)):*
> ```objc
>     OpenSim_DECLARE_LIST_PROPERTY(coordinate_paths, std::string,
>             "Paths to joint values in the model and table, e.g. "
>             "'/jointset/slider/position/value'.");
> ```

I think the path to the table of coordinate values should be the property here, not the list of coordinate paths. The columns of the table should be valid paths to coordinate values which are then parsed and error-checked.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 2093 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38rvLtASH1R05kOs6i:-O38rvLtASH1R05kOs6j:b-g5qhe2) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Moco/Test/testMocoConstraints.cpp#L2093)):*
> ```cpp
> }
> 
> TEMPLATE_TEST_CASE("ModOpPrescribeMotion", "", MocoCasADiSolver, MocoTropterSolver) {
> ```

We don't need Moco to test this ModelOperator. You can instead add a test to `testModelProcessor.cpp` that adds a prescribed function to a coordinate based on the new operator and then verify that, given a `SimTK::State` with a specified time, the coordinate is at the expected value based on the prescribed function.


<!-- Sent from Reviewable.io -->

2024-07-31 21:17 UTC, AllisonJohn commented
*[`OpenSim/Actuators/ModelOperators.h` line 220 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38rCBO04JRZatjG6bO:-O39d7eh1ulXcwmbTqgu:buieb1y) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Actuators/ModelOperators.h#L220)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think the path to the table of coordinate values should be the property here, not the list of coordinate paths. The columns of the table should be valid paths to coordinate values which are then parsed and error-checked.
</blockquote></details>

In that case should it prescribe motion to all the joint coordinates that are listed in the columns? (Instead of only the selected ones as I have now)


<!-- Sent from Reviewable.io -->

2024-07-31 21:41 UTC, AllisonJohn reviewed
It is still causing the ci tests to fail because there are two definitions of createSlidingMassModel even though on my computer there is only one, but that shouldn't be a problem when change the test and put it in another file

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-:-O39iskN9OWJMRNGjqND:b-xgilgj)* status: all files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/ModelOperators.h` line 216 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38qCIb7hvcaAQSlcYc:-O39bc1Z-VrTnsylKlGV:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Actuators/ModelOperators.h#L216)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

We should make the name of this ModelOperator more active. Consider something like `ModOpPrescribeCoordinateValues` to more clearly indicate what the operator is doing.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 2093 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38rvLtASH1R05kOs6i:-O39egtsAuNMmaoNi7YD:b2hmnhd) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Moco/Test/testMocoConstraints.cpp#L2093)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

We don't need Moco to test this ModelOperator. You can instead add a test to `testModelProcessor.cpp` that adds a prescribed function to a coordinate based on the new operator and then verify that, given a `SimTK::State` with a specified time, the coordinate is at the expected value based on the prescribed function.
</blockquote></details>

How do I get states from the model? The reason I was using Moco was to get a trajectory


<!-- Sent from Reviewable.io -->

2024-08-01 17:01 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862)* status: all files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 2093 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38rvLtASH1R05kOs6i:-O3DsiJ43W5UPmB-DzMS:b1yxylr) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Moco/Test/testMocoConstraints.cpp#L2093)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

How do I get states from the model? The reason I was using Moco was to get a trajectory
</blockquote></details>

Looks like I can use the Manager class to get states


<!-- Sent from Reviewable.io -->

2024-08-01 17:07 UTC, nickbianco requested changes
You might need to merge the main branch into your branch to resolve the duplicate problem. But yes, we're moving the test to `testModelProcessor` anyway, so it should resolve itself.

Also, I think you might have forgotten to push some changes.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-:-O3DtiKS1Kr4KRo_gNj7:b-yh49ne)* status: all files reviewed, 3 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Actuators/ModelOperators.h` line 216 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38qCIb7hvcaAQSlcYc:-O3DspgE-DUUUjP6d1lc:b-b6q730) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Actuators/ModelOperators.h#L216)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change. Perhaps you forgot to push some commits?
___
*[`OpenSim/Actuators/ModelOperators.h` line 220 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38rCBO04JRZatjG6bO:-O3Dsm_s7sshvBzvmjPt:b5o4u2n) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Actuators/ModelOperators.h#L220)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

In that case should it prescribe motion to all the joint coordinates that are listed in the columns? (Instead of only the selected ones as I have now)
</blockquote></details>

Yes, I think we should use the columns a dictate which coordinates are prescribed.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 2093 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38rvLtASH1R05kOs6i:-O3Dt07Q3PL-wR8COIJO:byq1y1y) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Moco/Test/testMocoConstraints.cpp#L2093)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Looks like I can use the Manager class to get states
</blockquote></details>

A better way is to get the state from initilizing the model's system:

```
SimTK::State& state = model.initSystem();
```


<!-- Sent from Reviewable.io -->

2024-08-01 19:18 UTC, AllisonJohn reviewed
Yes, changes have been pushed now. I couldn't figure out how to remove testMocoConstraints without deleting it so I just pasted back the original code.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-:-O3EL_Dh-_xc6_vutcdB:btxc14p)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/ModelOperators.h` line 216 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38qCIb7hvcaAQSlcYc:-O3EMa_6BOj9NvckHkFb:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Actuators/ModelOperators.h#L216)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I don't see this change. Perhaps you forgot to push some commits?
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/ModelOperators.h` line 220 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38rCBO04JRZatjG6bO:-O3EMa-HEb_hTvHaQehS:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Actuators/ModelOperators.h#L220)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Yes, I think we should use the columns a dictate which coordinates are prescribed.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoConstraints.cpp` line 2093 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O38rvLtASH1R05kOs6i:-O3EMiLJ54C02iS7ANU2:bw3vo97) ([raw file](https://github.com/opensim-org/opensim-core/blob/86339c808d6ca6e6667cee509b1082cb3e2bbaf6/OpenSim/Moco/Test/testMocoConstraints.cpp#L2093)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

A better way is to get the state from initilizing the model's system:

```
SimTK::State& state = model.initSystem();
```
</blockquote></details>

Yes I did use that along with the Manager... maybe the Manager is not actually necessary? I just copied it from a test in testActuators


<!-- Sent from Reviewable.io -->

2024-08-01 20:40 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/Test/linear_move.sto` line 0 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EdjvB0lXj8vjlyFZ-:-O3EdjvB0lXj8vjlyFZ0:b-6rkeii) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/Test/linear_move.sto#L0)):*
When I tested using this file I had to copy it into the build folder for it to work, is it ok to commit changes to the build folder?


<!-- Sent from Reviewable.io -->

2024-08-01 22:16 UTC, AllisonJohn commented
*[`OpenSim/Actuators/ModelOperators.h` line 233 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EkgNx5HSlUzTqktX9:-O3Ez6tU5s7xQkDB3iJz:be6wqkz) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/ModelOperators.h#L233)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

If we don't throw an exception that a column label does not match a valid Coordinate value, we should make a note of it in the doc-string for this operator.
</blockquote></details>

yeah I wasn't sure if it should ever through errors now because there could be many other columns that are not joint values, for example the /actuator column is ok to have in the table. Should it throw an error only if the table has a joint value column that is not in the model?


<!-- Sent from Reviewable.io -->

2024-08-01 22:34 UTC, AllisonJohn commented
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 157 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EmV9M3VenmidTZ252:-O3F0xwg9vrXw25lBtkD:bg5rzml) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/Test/testModelProcessor.cpp#L157)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

After switching to `TableProcessor`, you can just create this table programmatically inside the test.
</blockquote></details>

would I use InverseKinematics to get the data for the table? I used a MocoStudy to make linear_move.sto


<!-- Sent from Reviewable.io -->

2024-08-02 17:56 UTC, nickbianco requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862)* status: 2 of 4 files reviewed, 11 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Actuators/ModelOperators.h` line 233 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EkgNx5HSlUzTqktX9:-O3JDI7z0rNLLFf1CeFH:b-n8avbh) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/ModelOperators.h#L233)):*
Continue drafting this PR assuming that we will ignore columns that do not match a Coordinate value path. We can add an exception later if we want.

> Should it throw an error only if the table has a joint value column that is not in the model?

At the very least we should print a warning via `log_warn`.
___
*[`OpenSim/Actuators/ModelOperators.h` line 213 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3JCuyS8FCEFZtjRaMp:-O3JCuyT5kYR20m8Dh3B:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/0c35c5347f06826cd6f3492d93dc1a4b45029518/OpenSim/Actuators/ModelOperators.h#L213)):*
> ```objc
> 
> /// Prescribe motion to Coordinate%s in a model by providing a table containing
> /// time series data of Coordinate values. Any columns in the provided tbale
> ```





_Suggestion:_
```objc
/// time series data of Coordinate values. Any columns in the provided table
```
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 157 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EmV9M3VenmidTZ252:-O3JDpv13F4XUKciH7_Z:bciuqo2) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/Test/testModelProcessor.cpp#L157)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

would I use InverseKinematics to get the data for the table? I used a MocoStudy to make linear_move.sto
</blockquote></details>

You could just create a table from scratch. You could populate the table with values from a `Function` (e.g., `Sine`).


<!-- Sent from Reviewable.io -->

2024-08-03 03:13 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/ModelOperators.h` line 214 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3Efy7ZC4tvbUjhTs_M:-O3FDAk2EyOeLdA8Amt1:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/ModelOperators.h#L214)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

A revised the documentation here for clarity. FYI, "Coordinate%s" is not an accident: the `%` symbol allows Doxygen to create a link to the Coordinate class while also providing the correct pluralization (i.e., the `%`  is not included in the auto-generated docs).
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/ModelOperators.h` line 218 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EisAy5nGde9hJ_1ek:-O3FJeAe66yp4LY6ONE8:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/ModelOperators.h#L218)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think we should actually make this property type `TableProcessor`, rather than a string to a file. `TableProcessor` will allow a user to provide a table via a file or programmatically.  Thus, I would rename the property to something like `coordinate_values` and update the doc string.
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/ModelOperators.h` line 229 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EjFIF0Sk4Anmk2ZYF:-O3F6HfLCJiOtUubNNFR:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/ModelOperators.h#L229)):*
> ```objc
>         TimeSeriesTable table = TimeSeriesTable(get_motion_file());
>         GCVSplineSet statesSpline(table);
>         for (std::string pathString: table.getColumnLabels()) {
> ```

Done.
___
*[`OpenSim/Actuators/ModelOperators.h` line 233 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EkgNx5HSlUzTqktX9:-O3KwTxf2iL-EukZ7MXw:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/ModelOperators.h#L233)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Continue drafting this PR assuming that we will ignore columns that do not match a Coordinate value path. We can add an exception later if we want.

> Should it throw an error only if the table has a joint value column that is not in the model?

At the very least we should print a warning via `log_warn`.
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/ModelOperators.h` line 213 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3JCuyS8FCEFZtjRaMp:-O3Kv_Y1CDb4-Bky2HVN:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/0c35c5347f06826cd6f3492d93dc1a4b45029518/OpenSim/Actuators/ModelOperators.h#L213)):*
> ```objc
> 
> /// Prescribe motion to Coordinate%s in a model by providing a table containing
> /// time series data of Coordinate values. Any columns in the provided tbale
> ```

Done.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 129 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EljT81DwPCqod3sHL:-O3F59bQ4AF4rdsOWa4y:b-94uyv3) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/Test/testModelProcessor.cpp#L129)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Since you just need a simple model with a coordinate for this test, you could instead use [ModelFactory::createSlidingPointMass()](https://simtk.org/api_docs/opensim/api_docs45/classOpenSim_1_1ModelFactory.html#abce2780a5c35c1bc2746ce7e78c973da) here. (ModelFactory might be useful for future tests too).
</blockquote></details>

Unfortunately createSlidingPointMass adds the slider as a component instead of a joint. I don't know if it would mess up other tests to change that method.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 157 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EmV9M3VenmidTZ252:-O3LB9TU8IC0XIr9XYe7:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/Test/testModelProcessor.cpp#L157)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

You could just create a table from scratch. You could populate the table with values from a `Function` (e.g., `Sine`).
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 177 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EmeDp6hrAHQYh6e3T:-O3FCOQK3oYQipDxOwQV:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/Test/testModelProcessor.cpp#L177)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

You should only need to integrate once and then check that the coordinate values are valid at each time step. You can use this example to see how to extract a StatesTrajectory using StatesTrajectoryReporter after a forward integration: https://github.com/opensim-org/opensim-core/blob/f529ee84d40595f9e89b399a59575a974758c685/Bindings/Python/examples/posthoc_StatesTrajectory_example.py#L46.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-06 17:05 UTC, nickbianco requested changes
Getting close! I left another round of comments.

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-:-O3cdeJ490aS4vxp5KW6:b-h4ug7o)* status: all files reviewed, 14 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Actuators/ModelOperators.h` line 25 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3YTAek9Ia5RW6eynWB:-O3YTAek9Ia5RW6eynWC:b-kc9o0k) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L25)):*
> ```objc
> #include <OpenSim/Actuators/ModelFactory.h>
> #include <OpenSim/Common/GCVSplineSet.h>
> #include <OpenSim/Simulation/Model/ExternalLoads.h>
> ```

nit: I would keep includes from the same libraries grouped together:



_Suggestion:_
```objc
#include "ModelProcessor.h"
#include <OpenSim/Actuators/ModelFactory.h>
#include <OpenSim/Common/GCVSplineSet.h>
#include <OpenSim/Simulation/Model/ExternalLoads.h>
#include "OpenSim/Simulation/TableProcessor.h"
```
___
*[`OpenSim/Actuators/ModelOperators.h` line 224 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3YSNlY1h_9pZrr5hnd:-O3YSNlY1h_9pZrr5hne:b-tmkyv) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L224)):*
> ```objc
>             ModOpPrescribeCoordinateValues, ModelOperator);
>     OpenSim_DECLARE_PROPERTY(table, TableProcessor,
>             "TableProcessor of a TimeSeriesTable with motion to prescribe.")
> ```

Consider a more descriptive property name like `coordinate_values`. The property type already indicates that it is a table.
___
*[`OpenSim/Actuators/ModelOperators.h` line 236 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3YS_3-4DyL4gAfFDP-:-O3YS_3-4DyL4gAfFDP0:b-p7c6lr) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L236)):*
> ```objc
> 
>         for (const std::string& pathString: table.getColumnLabels()) {
>             OPENSIM_THROW_IF_FRMOBJ(!model.hasComponent("actuator"), Exception, fmt::format("no{}", pathString));
> ```

What is this check for?
___
*[`OpenSim/Actuators/ModelOperators.h` line 239 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3YTMqwAXdFM4yqN2cW:-O3YTMqwAXdFM4yqN2cX:b-pdurev) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L239)):*
> ```objc
>             ComponentPath path = ComponentPath(pathString);
>             if (path.getNumPathLevels() < 2
>                     || path.getSubcomponentNameAtLevel(0) != "jointset"
> ```

Joints may not necessarily be in the JointSet. I think we should strip off "/value" and the coordinate name and then check if the joint exists. In other words, if a generic path would be "/path/to/joint/coordinate_name/value", then we should strip off "coordinate_name" and "value" and check if a Joint exists at "/path/to/joint".
___
*[`OpenSim/Actuators/ModelOperators.h` line 244 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3caHlB8GaNk9BM3DTO:-O3caHlB8GaNk9BM3DTP:b-ujp3kh) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L244)):*
> ```objc
>             }
>             std::string jointName = path.getSubcomponentNameAtLevel(1);
>             if (!model.hasComponent<Joint>("jointset/"+jointName)) {
> ```

Per my comment above, the argument here should be updated to "/path/to/joint".
___
*[`OpenSim/Actuators/ModelOperators.h` line 246 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3caYv965bYs9_6idDC:-O3caYv965bYs9_6idDD:b-mneil) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L246)):*
> ```objc
>             if (!model.hasComponent<Joint>("jointset/"+jointName)) {
>                 log_warn("Path '{}' is a joint value column of the table,"
>                          " but it is not in the model.");
> ```

This could be a simpler message, e.g., "
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 129 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EljT81DwPCqod3sHL:-O3YhZVAAYB1cb0tDdZX:b6z1bcl) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/Test/testModelProcessor.cpp#L129)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Unfortunately createSlidingPointMass adds the slider as a component instead of a joint. I don't know if it would mess up other tests to change that method.
</blockquote></details>

Per my comment above, we should be able to detect if it's a Joint, whether it is in the JointSet or not.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 29 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cb8rW5B1NOm1xQyao:-O3cb8rW5B1NOm1xQyap:b-8atru) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L29)):*
> ```cpp
> #include <OpenSim/Simulation/SimbodyEngine/PinJoint.h>
> 
> using namespace OpenSim;
> ```

Keep the previous include pattern:



_Suggestion:_
```cpp
#include "OpenSim/Common/Sine.h"
#include <OpenSim/Actuators/CoordinateActuator.h>
#include <OpenSim/Actuators/Millard2012EquilibriumMuscle.h>
#include <OpenSim/Actuators/ModelOperators.h>
#include <OpenSim/Analyses/MuscleAnalysis.h>
#include <OpenSim/Moco/osimMoco.h>
#include <OpenSim/Simulation/SimbodyEngine/PinJoint.h>

#include <catch2/catch_all.hpp>

using namespace OpenSim;
```
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 153 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cbH8lBz_-Z4QaKSq2:-O3cbH8lBz_-Z4QaKSq3:bkbpeiq) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L153)):*
> ```cpp
> 
> /// create a TimeSeriesTable with one column of data which is the sine function.
> TimeSeriesTable createSineData(std::string label, double interval, double duration) {
> ```

Since this is specific to the test, I don't think we need a helper function for this. You can just move this into the main test.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 159 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3ccIAI5FvlRljG8A9i:-O3ccIAJ1bMmCRx-6I5q:b-7m6t46) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L159)):*
> ```cpp
>         times.push_back(i * interval);
>     }
>     SimTK::Matrix positions = SimTK::Vector(numEntries);
> ```

nit: 



_Suggestion:_
```cpp
    SimTK::Matrix positions(numEntries, 1);
```
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 160 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3ccrJn5dyqEzIjotzi:-O3ccrJn5dyqEzIjotzj:bb7lc5i) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L160)):*
> ```cpp
>     }
>     SimTK::Matrix positions = SimTK::Vector(numEntries);
>     SimTK::Vector x = SimTK::Vector(1);
> ```

nit:



_Suggestion:_
```cpp
    SimTK::Vector x(1);
```
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 166 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cd55H770tNFTZfxfm:-O3cd55H770tNFTZfxfn:bcr2zub) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L166)):*
> ```cpp
>     }
>     std::vector<std::string> labels = {label};
>     r [...]

2024-08-07 18:04 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862)* status: all files reviewed, 11 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/ModelOperators.h` line 224 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3YSNlY1h_9pZrr5hnd:-O3hjdj38-1OrH_bVWoy:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L224)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Consider a more descriptive property name like `coordinate_values`. The property type already indicates that it is a table.
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/ModelOperators.h` line 236 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3YS_3-4DyL4gAfFDP-:-O3hjyFs-eQnUL72WE29:b-98wjdh) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L236)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

What is this check for?
</blockquote></details>

whoops I think it was left over from debugging
___
*[`OpenSim/Actuators/ModelOperators.h` line 239 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3YTMqwAXdFM4yqN2cW:-O3hwPQg4-hjNrG-QT9y:b-xep4b9) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L239)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Joints may not necessarily be in the JointSet. I think we should strip off "/value" and the coordinate name and then check if the joint exists. In other words, if a generic path would be "/path/to/joint/coordinate_name/value", then we should strip off "coordinate_name" and "value" and check if a Joint exists at "/path/to/joint".
</blockquote></details>

ohh ok I was misinterpreting your slack message. Now it works for joints as components too, so I changed the warning to happen only when the column has "jointset" in it because if it was some other component that is not a joint that would still be ok
___
*[`OpenSim/Actuators/ModelOperators.h` line 244 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3caHlB8GaNk9BM3DTO:-O3hwFR1DyXfXTnapC2X:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L244)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Per my comment above, the argument here should be updated to "/path/to/joint".
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/ModelOperators.h` line 246 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3caYv965bYs9_6idDC:-O3hwK4k7X5FrWZXID7z:b-cw8joq) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L246)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

This could be a simpler message, e.g., "
</blockquote></details>

I think your quote got cut off
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 129 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EljT81DwPCqod3sHL:-O3hxzCP7F9lY0byQeUh:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/Test/testModelProcessor.cpp#L129)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Per my comment above, we should be able to detect if it's a Joint, whether it is in the JointSet or not.
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 29 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cb8rW5B1NOm1xQyao:-O3i-ORL-nfSFQ3KSVy4:bkwkoiw) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L29)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Keep the previous include pattern:
</blockquote></details>

Ah I need to stop using clion's automatic includer
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 153 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cbH8lBz_-Z4QaKSq2:-O3hy3c60UScYLNt4mW8:b-kcas3a) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L153)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Since this is specific to the test, I don't think we need a helper function for this. You can just move this into the main test.
</blockquote></details>

Now I use it twice in the sections
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 166 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cd55H770tNFTZfxfm:-O3hyAIk7YN9WC8yCagm:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L166)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

You might be able to save a line here:
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 194 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3YSwOH7vuDGW1ZqPLI:-O3hz4SHElBLhd79t3Zd:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L194)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

The Linux builds are failing because of the implicit type conversion here. You can fix it like so:
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 200 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cdPDR51ju5eoXIQYp:-O3hz5HD1fQvPrk6fr18:balgc7f) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L200)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Do you know why you needed to increase the margin here?
</blockquote></details>

Hmm not sure. I thought it might be because of not using the Manager anymore but not sure why that would change it.


<!-- Sent from Reviewable.io -->

2024-08-07 23:56 UTC, nickbianco requested changes
@AllisonJohn getting closer. I added a few more comments about reducing duplication and improving clarity.

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-:-O3jGGD97gYYKU1xL0H_:br2paal)* status: all files reviewed, 6 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Actuators/ModelOperators.h` line 246 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3caYv965bYs9_6idDC:-O3jDD7_BOQjnk4lmP_v:bn24o74) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L246)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

I think your quote got cut off
</blockquote></details>

My bad, I forgot to finish the comment. I meant to say that this could be modified to be a bit clearer:



_Suggestion:_
```objc
                log_warn("Found column label '{}', but it does not match "
                         "a joint coordinate value in the model.");
```
___
*[`OpenSim/Actuators/ModelOperators.h` line 224 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3jCcuW-zs9JXhArnBK:-O3jCcuW-zs9JXhArnBL:bvp03h7) ([raw file](https://github.com/opensim-org/opensim-core/blob/97d2ce339fcdb2cbb0042108c08e56eaae0f8af7/OpenSim/Actuators/ModelOperators.h#L224)):*
> ```objc
>             ModOpPrescribeCoordinateValues, ModelOperator);
>     OpenSim_DECLARE_PROPERTY(coordinate_values, TableProcessor,
>             "TableProcessor of a TimeSeriesTable with motion to prescribe.")
> ```

nit: Update this property description to describe what the table should contain (i.e., coordinate values).
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 129 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EljT81DwPCqod3sHL:-O3jE72oC39km46KS7B1:b-b5li4p) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/Test/testModelProcessor.cpp#L129)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We should now be able to use ModelFactory::createSlidingPointMass() for this test and remove this helper function.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 153 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cbH8lBz_-Z4QaKSq2:-O3jEYmQE2SVddZkVX78:b-a6o0io) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L153)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Now I use it twice in the sections
</blockquote></details>

See my comment below.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 200 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cdPDR51ju5eoXIQYp:-O3jEM3e9PV-NaoPLviP:b-7na87o) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L200)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Hmm not sure. I thought it might be because of not using the Manager anymore but not sure why that would change it.
</blockquote></details>

Would the test fail at the original accuracy (~1e-8)?
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 168 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3jEh2y-tWdYqwhnHKM:-O3jEh2y-tWdYqwhnHKN:bxap2v8) ([raw file](https://github.com/opensim-org/opensim-core/blob/97d2ce339fcdb2cbb0042108c08e56eaae0f8af7/OpenSim/Actuators/Test/testModelProcessor.cpp#L168)):*
> ```cpp
> }
> 
> TEST_CASE("ModOpPrescribeMotion") {
> ```

Since these two test sections are nearly identical, consider avoiding duplicate code. You could put the main code into a lambda function that takes each model as an argument. This would avoid the need for the `createSineData` helper function. 

Even better: create the base model using `ModelFactor::createSlidingPointMass()` and add a second slider joint to the JointSet. Then prescribe and test both coordinates using one table passed to `ModOpPrescribeCoordinateValues`. This should remove all code duplication.


<!-- Sent from Reviewable.io -->

2024-08-08 20:50 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/ModelOperators.h` line 246 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3caYv965bYs9_6idDC:-O3nQmkk2oqD3OkIMLUA:b-r4cpu2) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L246)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

My bad, I forgot to finish the comment. I meant to say that this could be modified to be a bit clearer:
</blockquote></details>

With this message should we warn even when the column label is not a joint coordinate value?
___
*[`OpenSim/Actuators/ModelOperators.h` line 224 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3jCcuW-zs9JXhArnBK:-O3nQO5l4P4XWkWlN84s:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/97d2ce339fcdb2cbb0042108c08e56eaae0f8af7/OpenSim/Actuators/ModelOperators.h#L224)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

nit: Update this property description to describe what the table should contain (i.e., coordinate values).
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 129 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3EljT81DwPCqod3sHL:-O3nkDGA4xGgvEGAGKn7:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/5cfae127e30a750fd8a2677e325db8e0c7976197/OpenSim/Actuators/Test/testModelProcessor.cpp#L129)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

We should now be able to use ModelFactory::createSlidingPointMass() for this test and remove this helper function.
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 153 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cbH8lBz_-Z4QaKSq2:-O3nkEueEKcbOOTn6BWP:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L153)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

See my comment below.
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 200 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cdPDR51ju5eoXIQYp:-O3nRgY5--vx-Me8YRzr:b-dpngzd) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L200)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Would the test fail at the original accuracy (~1e-8)?
</blockquote></details>

Yes it fails at 1e-5
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 168 at r8](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3jEh2y-tWdYqwhnHKM:-O3nkIYDC5Jk6EOLqSwd:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/97d2ce339fcdb2cbb0042108c08e56eaae0f8af7/OpenSim/Actuators/Test/testModelProcessor.cpp#L168)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Since these two test sections are nearly identical, consider avoiding duplicate code. You could put the main code into a lambda function that takes each model as an argument. This would avoid the need for the `createSineData` helper function. 

Even better: create the base model using `ModelFactor::createSlidingPointMass()` and add a second slider joint to the JointSet. Then prescribe and test both coordinates using one table passed to `ModOpPrescribeCoordinateValues`. This should remove all code duplication.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-08 20:51 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 200 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cdPDR51ju5eoXIQYp:-O3nkYge4PWQ5ylOH1rm:b-jpmjao) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L200)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Yes it fails at 1e-5
</blockquote></details>

With two prescribed joints it fails at 1e-4 so I had to change it to -3


<!-- Sent from Reviewable.io -->

2024-08-08 21:57 UTC, nickbianco requested changes
A couple more minor things to address. It would be nice to figure out why the test accuarcy needs to be so low, and it's probably related to constraint tolerances during integration.

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-:-O3nzREnDdCr_M3Y7xQ0:br7ukft)* status: all files reviewed, 4 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Actuators/ModelOperators.h` line 246 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3caYv965bYs9_6idDC:-O3nyKUVA9BxwAlaQ0Gy:b-y2vhvm) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L246)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

With this message should we warn even when the column label is not a joint coordinate value?
</blockquote></details>

Yes, I think that's reasonable.
___
*[`OpenSim/Actuators/ModelOperators.h` line 225 at r9](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3nwV3K2zggxYZFEFFt:-O3nwV3L7S3qWm4YBPgn:b-7m6t46) ([raw file](https://github.com/opensim-org/opensim-core/blob/0fb33d7a0bb4c0dfb36e815b60de0e767e734112/OpenSim/Actuators/ModelOperators.h#L225)):*
> ```objc
>     OpenSim_DECLARE_PROPERTY(coordinate_values, TableProcessor,
>             "TableProcessor of a TimeSeriesTable with coordinate value data to "
>             "prescribe ot he model.")
> ```

nit: 



_Suggestion:_
```objc
            "The table of coordinate value data to prescribe to the model.")
```
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 200 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cdPDR51ju5eoXIQYp:-O3nz2oI6I5zIPpYWBsN:b-r5xxoe) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L200)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

With two prescribed joints it fails at 1e-4 so I had to change it to -3
</blockquote></details>

Hmm. When running the integration in the test, do you get any warnings about relaxing constraint tolerances from Simbody?
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 182 at r9](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3nyaxkAgvNThKY5OzM:-O3nyaxkAgvNThKY5OzN:b-7m6t46) ([raw file](https://github.com/opensim-org/opensim-core/blob/0fb33d7a0bb4c0dfb36e815b60de0e767e734112/OpenSim/Actuators/Test/testModelProcessor.cpp#L182)):*
> ```cpp
>     StatesTrajectory statesTraj = reporter->getStates();
> 
>     for (const std::string& path: paths) {
> ```

nit: 



_Suggestion:_
```cpp
    for (const std::string& path : paths) {
```


<!-- Sent from Reviewable.io -->

2024-08-08 22:51 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862)* status: all files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/ModelOperators.h` line 246 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3caYv965bYs9_6idDC:-O3o90tz77gCjuLHrPhE:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/ModelOperators.h#L246)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Yes, I think that's reasonable.
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/Test/testModelProcessor.cpp` line 200 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-O3cdPDR51ju5eoXIQYp:-O3oAUCe9LJjhyPEHE-U:b-qiye9b) ([raw file](https://github.com/opensim-org/opensim-core/blob/8cd2cbdb65a66f2724c2183fb0913f197fedcae2/OpenSim/Actuators/Test/testModelProcessor.cpp#L200)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Hmm. When running the integration in the test, do you get any warnings about relaxing constraint tolerances from Simbody?
</blockquote></details>

Nope no warnings


<!-- Sent from Reviewable.io -->

2024-08-09 18:09 UTC, nickbianco approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3862#-:-O3sKDBC0VSy2QJO4ZGi:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)



<!-- Sent from Reviewable.io -->

2024-08-09 18:10 UTC, merged