Make interpolate() extrapolate when newX's are outside the original range
opensim-org/opensim-core pull request #3867
Opened 2024-08-07 23:26 UTC by AllisonJohn

Fixes issue #3866

### Brief summary of changes
This will cause the returned newY to never have NaN values, which was previously assumed but not true.

### Testing I've completed
Changed the interpolate test to not accept NaN values. Ran the linked test [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=18504&p=0&start=0&view=) and it works with the change.

### Looking for feedback on...

### CHANGELOG.md (choose one)

- to be updated.

2024-08-08 21:07 UTC, AllisonJohn commented
I was looking to see if there were any other uses of interpolate that should maybe use the extrapolate option. The only one I found outside of test cases was in https://github.com/opensim-org/opensim-core/blob/main/OpenSim/Sandbox/Moco/sandboxOneLegCouplerKnee/sandboxOneLegCouplerKnee.cpp.

2024-08-08 22:30 UTC, nickbianco requested changes
@AllisonJohn looks good overall! Just a few comments on when to use the `ignoreNaNs` flag. 

It's fine to ignore sandbox files.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-:-O3o62DHAnEcqm6sK3uf:b-l67xy6)* status: all files reviewed, 3 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Common/Test/testFunctions.cpp` line 110 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-O3o0IsJ1uJP8R-0lx-D:-O3o0IsK9El7ChZmiTwG:b-bcaxtc) ([raw file](https://github.com/opensim-org/opensim-core/blob/f65f499469f821512fcaf51d3b595d4eebb0b7b3/OpenSim/Common/Test/testFunctions.cpp#L110)):*
> ```cpp
>     SECTION("First and last Y are NaN, extrapolate") {
>         SimTK::Vector x = createVector({0, 1, 2, 3, 4, 5});
>         SimTK::Vector y = createVector({std::nan("0"), 0, 3, 4, std::nan("1"), std::nan("2")});
> ```

These could be SimTK::NaNs:



_Suggestion:_
```cpp
        SimTK::Vector y = createVector({SimTK::NaN, 0, 3, 4, SimTK::NaN, SimTK::NaN});
```
___
*[`OpenSim/Moco/MocoTrajectory.cpp` line 879 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-O3o0W3T07wdOx55Xm0Y:-O3o0W3T07wdOx55Xm0Z:buwsk5s) ([raw file](https://github.com/opensim-org/opensim-core/blob/f65f499469f821512fcaf51d3b595d4eebb0b7b3/OpenSim/Moco/MocoTrajectory.cpp#L879)):*
> ```cpp
>     for (int icol = 0; icol < m_slacks.ncol(); ++icol) {
>         m_slacks.updCol(icol) =
>                 interpolate(m_time, m_slacks.col(icol), m_time, false, true);
> ```

I think both arguments should be `true` here?
___
*[`OpenSim/Moco/MocoCasADiSolver/MocoCasOCProblem.h` line 238 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-O3o1BU84-9_NlXZDfmy:-O3o1BU84-9_NlXZDfmz:b-pt2d7y) ([raw file](https://github.com/opensim-org/opensim-core/blob/f65f499469f821512fcaf51d3b595d4eebb0b7b3/OpenSim/Moco/MocoCasADiSolver/MocoCasOCProblem.h#L238)):*
> ```objc
>                 mocoTraj.appendSlack(casIt.slack_names[i],
>                         interpolate(slackTime, simtkSlacks.col(i), simtkTimes,
>                                     false, true));
> ```

Tt's probably okay to leave `ignoreNaNs` as `false` here, but I think we might as well set it to `true` as well.


<!-- Sent from Reviewable.io -->

2024-08-08 23:55 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3867)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Test/testFunctions.cpp` line 110 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-O3o0IsJ1uJP8R-0lx-D:-O3oB__H5vIQ_TdCO45A:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f65f499469f821512fcaf51d3b595d4eebb0b7b3/OpenSim/Common/Test/testFunctions.cpp#L110)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

These could be SimTK::NaNs:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoTrajectory.cpp` line 879 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-O3o0W3T07wdOx55Xm0Y:-O3oBaPRBDBYKAkEEXj0:bqi1g1c) ([raw file](https://github.com/opensim-org/opensim-core/blob/f65f499469f821512fcaf51d3b595d4eebb0b7b3/OpenSim/Moco/MocoTrajectory.cpp#L879)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think both arguments should be `true` here?
</blockquote></details>

Oh right it was set to true before
___
*[`OpenSim/Moco/MocoCasADiSolver/MocoCasOCProblem.h` line 238 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-O3o1BU84-9_NlXZDfmy:-O3oP1RAC-k32mxz2q5w:bgcjmy9) ([raw file](https://github.com/opensim-org/opensim-core/blob/f65f499469f821512fcaf51d3b595d4eebb0b7b3/OpenSim/Moco/MocoCasADiSolver/MocoCasOCProblem.h#L238)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Tt's probably okay to leave `ignoreNaNs` as `false` here, but I think we might as well set it to `true` as well.
</blockquote></details>

I noticed that as long as the extrapolate option is true here, the example test from the issue works, regardless of whether it is set true in the MocoTrajectory resample(). It could be that the interpolation in resample is redundant now that convertToMocoTrajectory is fixed.


<!-- Sent from Reviewable.io -->

2024-08-09 00:03 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3867)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/Test/testFunctions.cpp` line 127 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-O3oRNWqE7WmiLoyjHjK:-O3oRNWqE7WmiLoyjHjL:b-7ze6bg) ([raw file](https://github.com/opensim-org/opensim-core/blob/56f2a7fa813aaef7897d5292e900510a0e459b49/OpenSim/Common/Test/testFunctions.cpp#L127)):*
> ```cpp
>         SimTK_TEST_EQ(newY[3], 3);
>     }
>     SECTION("Don't ignore NaNs, extrapolate") {
> ```

I was confused about why someone would want to not ignore NaNs so I added this test. Now I realize that extrapolate doesn't always prevent NaNs so I need to change the header comment


<!-- Sent from Reviewable.io -->

2024-08-09 18:12 UTC, nickbianco approved these changes
Great fix @AllisonJohn!

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-:-O3sKqko6z-hSwYROJbM:b-nyxrtj)* status: all files reviewed, 2 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Common/CommonUtilities.h` line 97 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-O3sKZvZDrKqr8pgQTdK:-O3sKZvZDrKqr8pgQTdL:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/4ff39c28ac6fed14ff782210b4f11d42cb8d7be5/OpenSim/Common/CommonUtilities.h#L97)):*
> ```objc
> /// have NaN for any values of newX outside of the range of x. This is done with
> /// the 'extrapolate' option. If the 'extrapolate' argument is true, then the
> /// interpolant values will be extrapolated based on a piecewise function.
> ```





_Suggestion:_
```objc
/// interpolant values will be extrapolated based on a piecewise linear function.
```
___
*[`OpenSim/Moco/MocoCasADiSolver/MocoCasOCProblem.h` line 238 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3867#-O3o1BU84-9_NlXZDfmy:-O3sKkHE0B6Z_RRv1vt1:b-rw9oid) ([raw file](https://github.com/opensim-org/opensim-core/blob/f65f499469f821512fcaf51d3b595d4eebb0b7b3/OpenSim/Moco/MocoCasADiSolver/MocoCasOCProblem.h#L238)):*
> It could be that the interpolation in resample is redundant now that convertToMocoTrajectory is fixed.

I think that's right, but good to be safe here anyway.


<!-- Sent from Reviewable.io -->

2024-08-09 18:12 UTC, merged