Add `MocoParameterExpressionGoal`
opensim-org/opensim-core pull request #3869
Opened 2024-08-09 23:59 UTC by AllisonJohn

Fixes issue #3860

### Brief summary of changes
Added a new class for combining parameters with an expression in a Moco goal.

### Testing I've completed
Test case fails

### Looking for feedback on...

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

2024-08-15 22:52 UTC, AllisonJohn commented
Do I need to update https://github.com/opensim-org/opensim-core/blob/main/Bindings/moco.i? I don't think I did for the last PRs but it seems like all the goals are supposed to be there

2024-08-15 23:00 UTC, nickbianco requested changes
Great work @AllisonJohn! I left a bunch of comments.

> Do I need to update [https://github.com/opensim-org/opensim-core/blob/main/Bindings/moco.i](https://github.com/opensim-org/opensim-core/blob/main/Bindings/moco.i)? I don't think I did for the last PRs but it seems like all the goals are supposed to be there

Yes, you need to update `moco.i` so this will appear in the bindings.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-:-O4NFzhP0EOvCMbWEoQT:b-5z15bk)* status: all files reviewed, 22 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoParameter.h` line 26 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4MsJSg1GbQSmZumDtB:-O4MsJSg1GbQSmZumDtC:ba5jsvt) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoParameter.h#L26)):*
> ```objc
> #include <OpenSim/Common/Property.h>
> #include <SimTKcommon/internal/ReferencePtr.h>
> #include <SimTKcommon/internal/State.h>
> ```

Is this include necessary?
___
*[`OpenSim/Moco/MocoParameter.h` line 145 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4MsSfd45NMJ07xoYBx:-O4MsSfd45NMJ07xoYBy:b8n3uh2) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoParameter.h#L145)):*
> ```objc
>     void appendComponentPath(const std::string& componentPath)
>     {   append_component_paths(componentPath); }
>     int getElement() const {
> ```

To stay consistent with the property name:



_Suggestion:_
```objc
    int getPropertyElement() const {
```
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 27 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N5my3DGli5sLB3-TG:-O4N5my3DGli5sLB3-TH:beljsom) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L27)):*
> ```objc
> #include <lepton/ExpressionProgram.h>
> #include <SimTKcommon/internal/ReferencePtr.h>
> #include <SimTKcommon/internal/State.h>
> ```

Based on some of my comments below, you should be able to remove some includes here:



_Suggestion:_
```objc
#include "MocoGoal.h"

#include "OpenSim/Moco/MocoParameter.h"
#include <lepton/ExpressionProgram.h>
#include <SimTKcommon/internal/ReferencePtr.h>
```
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 36 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N8F-j7rHXVeeq3zKn:-O4N8F-j7rHXVeeq3zKo:b-mscizu) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L36)):*
> ```objc
> string should match the Lepton (lightweight expression parser) format.
> 
> Expressions can be any string that represents a mathematical expression, e.g.,
> ```

Some headings could be useful here:



_Suggestion:_
```objc
string should match the Lepton (lightweight expression parser) format.

# Creating expressions

Expressions can be any string that represents a mathematical expression, e.g.,
```
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 44 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N6C9x2BeshDgaTdBg:-O4N6C9x2BeshDgaTdBh:braplw2) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L44)):*
> ```objc
> +, -, *, /, and ^.
> 
> @ingroup mocogoal */
> ```

I think it would be useful to add a few code examples to the class docs here. You can use the Doxygen macro @code for this:



_Code snippet:_
```objc
# Examples

@code
// your example here
@endcode
```
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 61 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N7sYi4vKL-3EQdMeY:-O4N7sYi4vKL-3EQdMeZ:b-isoxvx) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L61)):*
> ```objc
>             std::string expression) : MocoGoal(std::move(name), weight) {
>         constructProperties();
>         setExpression(expression);
> ```

To avoid an unnecessary copy:



_Suggestion:_
```objc
        setExpression(std::move(expression));
```
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 66 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N8QTw3OxCX09WbCq2:-O4N8QTw3OxCX09WbCq3:b-19cmz5) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L66)):*
> ```objc
>     /** Set the mathematical expression to minimize. Variable names should match
>     the names set with addParameter(). See header for explanation of
>     Expressions. */
> ```

If you add a heading to the class docs above, you could refer to that instead of "Expressions".
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N7gdW-d3d_0_0tkh9:-O4N7gdX-jpR9YLC43Kq:b45h) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L68)):*
> ```objc
>     Expressions. */
>     void setExpression(std::string expression) {
>         set_expression(expression);
> ```





_Suggestion:_
```objc
        set_expression(std::move(expression));
```
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 75 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N4BLZ9J6-qsX9NDSa:-O4N4BLZ9J6-qsX9NDSb:bxdqis1) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L75)):*
> ```objc
>     parameter, but parameters with variables that are not in the expression are
>     ignored. */
>     void addParameter(MocoParameter& parameter, std::string variableName) {
> ```

I don't think we need to pass a modifiable reference to the `MocoParameter` here:



_Suggestion:_
```objc
    void addParameter(const MocoParameter& parameter, std::string variableName) {
```
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 77 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N57UC6s_9gFeScl1X:-O4N57UC6s_9gFeScl1Y:b-336y4t) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L77)):*
> ```objc
>     void addParameter(MocoParameter& parameter, std::string variableName) {
>         updProperty_parameters().appendValue(parameter);
>         updProperty_variable_names().appendValue(variableName);
> ```

It is preferable to use property macro `append_*` for this situation:



_Suggestion:_
```objc
        append_parameters(parameter);
        append_variable_names(std::move(variableName));
```
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 85 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N8u0QAKPfWD0WLyoL:-O4N8u0QAKPfWD0WLyoM:bhr686l) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L85)):*
> ```objc
>             const IntegrandInput& input, SimTK::Real& integrand) const override;
>     void calcGoalImpl(
>             const GoalInput& input, SimTK::Vector& cost) const override;
> ```

We should support both "cost" and "endpoint constraint" mode for this goal. To enable support for endpoint constraint mode, you can override `MocoGoal::getSupportsEndpointConstraintImpl()`to return `true`. We should add at least one test for [...]

2024-08-16 00:14 UTC, AllisonJohn reviewed
Will finish the last two comments soon!

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-:-O4NXKpbEnaNqbEGD_YU:b1g0qt)* status: 4 of 8 files reviewed, 21 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoParameter.h` line 26 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4MsJSg1GbQSmZumDtB:-O4NM-078Y7ivFXrb39s:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoParameter.h#L26)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Is this include necessary?
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoParameter.h` line 145 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4MsSfd45NMJ07xoYBx:-O4NMN3I4I2D-Dhk-XXL:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoParameter.h#L145)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

To stay consistent with the property name:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 27 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N5my3DGli5sLB3-TG:-O4NN4TFCEYZ2XHsZxux:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L27)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Based on some of my comments below, you should be able to remove some includes here:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 36 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N8F-j7rHXVeeq3zKn:-O4NO7dlBjbn6JW8NSm0:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L36)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Some headings could be useful here:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 61 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N7sYi4vKL-3EQdMeY:-O4NRIOM3-SntIB6e-1f:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L61)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

To avoid an unnecessary copy:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 66 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N8QTw3OxCX09WbCq2:-O4NRtcy0-XNtZ-AF9J_:b-rsrogz) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L66)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

If you add a heading to the class docs above, you could refer to that instead of "Expressions".
</blockquote></details>

Will it link to the header if I put the #?
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 68 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N7gdW-d3d_0_0tkh9:-O4NSP3G3tz5TxcqiqDW:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L68)):*
> ```objc
>     Expressions. */
>     void setExpression(std::string expression) {
>         set_expression(expression);
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 75 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N4BLZ9J6-qsX9NDSa:-O4NSVvCE8cuAFtOGQ-C:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L75)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I don't think we need to pass a modifiable reference to the `MocoParameter` here:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 77 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N57UC6s_9gFeScl1X:-O4NSfKc0liC7Y-iWrd_:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L77)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

It is preferable to use property macro `append_*` for this situation:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 3 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N7VIX9THc2m5NswNr:-O4NSxr-AgDXAvqe1nY9:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L3)):*
> ```cpp
> /* -------------------------------------------------------------------------- *
> * OpenSim: MocoExpressionBasedParameterGoal.h                                 *
>  * -------------------------------------------------------------------------- *
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 38 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N7C5Y8MApGM2yodd-:-O4NTIFGD3N-VUk8IEm4:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L38)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

We should set a stage dependency for this. I think we can set this to an earlier stage, like `SimTK::Stage::Instance`, since the parameters are just property values stored in the model. Also, we will not need integrals for this goal (see comments below):
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 41 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4NAtoV7YWn1-uGZJt0:-O4NTLa_-RjjJihOh5vE:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L41)):*
> ```cpp
> 
>     for (int i = 0; i < getProperty_parameters().size(); i++) {
>         // onylt taking the first one since they should all be the same value
> ```

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 44 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4NVNgb0QnqXkDpjPJY:-O4NVNgb0QnqXkDpjPJZ:b-7b61s0) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L44)):*
> ```cpp
>         std::string componentPath = get_parameters(i).getComponentPaths()[0];
>         const auto& component = model.getComponent(componentPath);
>         const auto* ap = &component.getPropertyByName(
> ```

Could there be a case where the parameter has the same name as a parameter in the model, but it's actually not in the model? Maybe instead of adding parameters as a MocoParameter they should just pass the name.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 50 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4NB7A2C0Ha0H_Ii2mH:-O4NTQaE5Zz2OUSNXymW:b3eyohm) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoEx [...]

2024-08-16 17:32 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3869)* status: 4 of 8 files reviewed, 21 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 44 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N6C9x2BeshDgaTdBg:-O4RC1mjA9EGl772r5IQ:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L44)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think it would be useful to add a few code examples to the class docs here. You can use the Doxygen macro @code for this:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 85 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N8u0QAKPfWD0WLyoL:-O4REiWE1UrsiPchYnPr:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L85)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

We should support both "cost" and "endpoint constraint" mode for this goal. To enable support for endpoint constraint mode, you can override `MocoGoal::getSupportsEndpointConstraintImpl()`to return `true`. We should add at least one test for that mode too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-16 18:10 UTC, nickbianco requested changes
Looking good, almost there! I requested adding a Python test for this change, let me know if you have any questions about that.

> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-:-O4RNTPsBENh69gdeg-N:b-qn4gwd)* status: all files reviewed, 6 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 66 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N8QTw3OxCX09WbCq2:-O4RKIiU6ZZpx5QhbY82:bhja0ec) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L66)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Will it link to the header if I put the #?
</blockquote></details>

Hmm, that's a good question. Based on [the Doxygen documentation](https://doxygen.nl/manual/commands.html#cmdsa), it looks like you can link to classes, methods, URLs, etc., but not comment headers.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 55 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4RM7HS7hfAU04QtCi7:-O4RM7HS7hfAU04QtCi8:b-uje12b) ([raw file](https://github.com/opensim-org/opensim-core/blob/19985abe54fbf81bdd3e8b5fae1980b26528b5dd/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L55)):*
> ```objc
> spring_goal->setExpression(fmt::format("square( p+q-{} )", STIFFNESS));
> spring_goal->addParameter(*spring1_parameter, "p");
> spring_goal->addParameter(*spring2_parameter, "q");
> ```

I think I would like to add a Python test for this functionality, to confirm that this pointer operation works as expected in scripting. Could you add a test to [test_moco.py](https://github.com/opensim-org/opensim-core/blob/5f56a5eaf11f17807372226ddf27ef639c51df7a/Bindings/Python/tests/test_moco.py)? You could reuse one of the C++ tests you've written. 
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 80 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4RKvq80uFvYP45WXi-:-O4RKvq80uFvYP45WXi0:b-vlc45e) ([raw file](https://github.com/opensim-org/opensim-core/blob/19985abe54fbf81bdd3e8b5fae1980b26528b5dd/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L80)):*
> ```objc
>     /** Set the mathematical expression to minimize. Variable names should match
>     the names set with addParameter(). See Creating Expressions above for an
>     explanation of Expressions. */
> ```

A suggestion clarity:



_Suggestion:_
```objc
    the names set with addParameter(). See "Creating Expressions" in the class 
    documentation above for an explanation of how to create expressions. */
```
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 44 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4NVNgb0QnqXkDpjPJY:-O4RMjrhDOG7iRk48mCY:b-j744pr) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L44)):*
> Could there be a case where the parameter has the same name as a parameter in the model, but it's actually not in the model?

Could you clarify this? Did you mean "parameter has the same name as a _property_ in the model"? And if the property is in the model, how could it not "actually be in the model"?
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 95 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4NDv2rA3jj9-LAgk3j:-O4RL_1s18HFYfJ12igA:bsijm26) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L95)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Can I get rid of this throw? I think I added it during debugging. There's no reason why it would be out of bounds, the methods are private
</blockquote></details>

You could change it to an assert, so that it only gets check during debug builds, which could be useful for future developers. See [OpenSim::Assertion](https://github.com/opensim-org/opensim-core/blob/5f56a5eaf11f17807372226ddf27ef639c51df7a/OpenSim/Common/Assertion.h#L4).
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 124 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4RLSJc4cmx7YHQB7sT:-O4RLSJc4cmx7YHQB7sU:bq4m3s8) ([raw file](https://github.com/opensim-org/opensim-core/blob/19985abe54fbf81bdd3e8b5fae1980b26528b5dd/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L124)):*
> ```cpp
>     for (int i = 0; i < getProperty_variable_names().size(); ++i) {
>         std::string variableName = get_variable_names(i);
>         parameterVars[variableName] = getPropertyValue(i);
> ```

Can simplify here:



_Suggestion:_
```cpp
        parameterVars[get_variable_names(i)] = getPropertyValue(i);
```


<!-- Sent from Reviewable.io -->

2024-08-16 19:18 UTC, AllisonJohn reviewed
I didn't run the test because my clion isn't set up for python, so hopefully it passes ci

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-:-O4RbjQvEvGzcm9J1VQp:bhvo6w2)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 66 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4N8QTw3OxCX09WbCq2:-O4RWHrb48HiT2MYhcQW:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L66)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Hmm, that's a good question. Based on [the Doxygen documentation](https://doxygen.nl/manual/commands.html#cmdsa), it looks like you can link to classes, methods, URLs, etc., but not comment headers.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 55 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4RM7HS7hfAU04QtCi7:-O4RbWtXC5bjwfopSEox:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/19985abe54fbf81bdd3e8b5fae1980b26528b5dd/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L55)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think I would like to add a Python test for this functionality, to confirm that this pointer operation works as expected in scripting. Could you add a test to [test_moco.py](https://github.com/opensim-org/opensim-core/blob/5f56a5eaf11f17807372226ddf27ef639c51df7a/Bindings/Python/tests/test_moco.py)? You could reuse one of the C++ tests you've written.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 80 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4RKvq80uFvYP45WXi-:-O4RWGKk1Qy-gZww-H6L:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/19985abe54fbf81bdd3e8b5fae1980b26528b5dd/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L80)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

A suggestion clarity:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 44 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4NVNgb0QnqXkDpjPJY:-O4RQhJ1Es86EYL-0CbU:bi7inrz) ([raw file](https://github.com/opensim-org/opensim-core/blob/f53f90d266c09db411803bedfd19448e1935a7c4/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L44)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

> Could there be a case where the parameter has the same name as a parameter in the model, but it's actually not in the model?

Could you clarify this? Did you mean "parameter has the same name as a _property_ in the model"? And if the property is in the model, how could it not "actually be in the model"?
</blockquote></details>

Oh I guess I meant MocoProblem instead of model since the parameters are added to the problem. So I can't get the parameter from just the name. I also got getPropertyName confused with getName. So never mind this comment!
___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 124 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-O4RLSJc4cmx7YHQB7sT:-O4RUJOc4E20UugFY6uR:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/19985abe54fbf81bdd3e8b5fae1980b26528b5dd/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L124)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Can simplify here:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-17 17:04 UTC, nickbianco commented
@AllisonJohn, the tests are currently failing because `moco.i` has not yet been updated to include `MocoExpressionBasedParameterGoal`.

2024-08-21 17:32 UTC, nickbianco approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Great job!

> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3869#-:-O4pzmde-HJbKf3gID91:b-4f25mi)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)



<!-- Sent from Reviewable.io -->

2024-08-21 17:32 UTC, merged