Convert Simulation tests to catch2
opensim-org/opensim-core pull request #3897
Opened 2024-08-30 21:52 UTC by AllisonJohn

Fixes issue #3555

### Brief summary of changes
Converted remaining test files in the simulation folder to use catch test cases

### Testing I've completed
tests still pass

### Looking for feedback on...

### CHANGELOG.md (choose one)

- no need to update because internal

2024-08-30 22:14 UTC, nickbianco requested changes
A couple minor suggestions, but looks good overall!

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3897#-:-O5_LW5LBGgieodukKbP:b-g7pm8)* status: all files reviewed, 2 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Simulation/Test/testInverseKinematicsSolver.cpp` line 243 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3897#-O5_K5fi5ZVF5A_7WVrx:-O5_K5fi5ZVF5A_7WVry:ba3dfna) ([raw file](https://github.com/opensim-org/opensim-core/blob/c95606a9e69adf1196cb7cf7d6e03d578261bb2f/OpenSim/Simulation/Test/testInverseKinematicsSolver.cpp#L243)):*
> ```cpp
>             noiseLevel*double(noise(gen)), SimTK::ZAxis );
> 
>         cout << "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" << endl;
> ```

Remove?
___
*[`OpenSim/Simulation/Test/testMomentArms.cpp` line 348 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3897#-O5_KTdk3XxEuatv_Yx6:-O5_KTdk3XxEuatv_Yx7:b-bpf6ep) ([raw file](https://github.com/opensim-org/opensim-core/blob/c95606a9e69adf1196cb7cf7d6e03d578261bb2f/OpenSim/Simulation/Test/testMomentArms.cpp#L348)):*
> ```cpp
>         SimTK::Vec2(-2*SimTK::Pi/3, SimTK::Pi/18), 0.0,
>         "VASINT of BothLegs with no mass: FAILED");
>     cout << "VASINT of BothLegs with no mass: PASSED\n" << endl;
> ```

It would be better to remove all these subtests into `SECTION`s and remove the `cout` statements. When running the test suite, the sections will show as passed or failed.

Also, watch the 80 column limit.


<!-- Sent from Reviewable.io -->

2024-08-30 22:52 UTC, AllisonJohn reviewed
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3897)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Simulation/Test/testInverseKinematicsSolver.cpp` line 243 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3897#-O5_K5fi5ZVF5A_7WVrx:-O5_OzbF20p8gdT5s07W:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c95606a9e69adf1196cb7cf7d6e03d578261bb2f/OpenSim/Simulation/Test/testInverseKinematicsSolver.cpp#L243)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`OpenSim/Simulation/Test/testMomentArms.cpp` line 348 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3897#-O5_KTdk3XxEuatv_Yx6:-O5_TG7G1gsQmxFW6AIm:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c95606a9e69adf1196cb7cf7d6e03d578261bb2f/OpenSim/Simulation/Test/testMomentArms.cpp#L348)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

It would be better to remove all these subtests into `SECTION`s and remove the `cout` statements. When running the test suite, the sections will show as passed or failed.

Also, watch the 80 column limit.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-30 23:03 UTC, AllisonJohn commented
I need to add LoadOpenSimLibrary("osimActuators"); back to some files

2024-09-03 16:55 UTC, nickbianco requested changes
A few more suggestions to clean things up.

> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3897#-:-O5sno1qBOrGlI7YTrUc:b-y4oqcc)* status: all files reviewed, 3 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Simulation/Test/testModelInterface.cpp` line 38 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3897#-O5sniMt8gHaiyMzE03W:-O5sniMt8gHaiyMzE03X:b-lmarwg) ([raw file](https://github.com/opensim-org/opensim-core/blob/e9222761045b218817839b141b1428546db72098/OpenSim/Simulation/Test/testModelInterface.cpp#L38)):*
> ```cpp
> TEST_CASE("testModelFinalizePropertiesAndConnections")
> {
>     LoadOpenSimLibrary("osimActuators");
> ```

Replace with include?
___
*[`OpenSim/Simulation/Test/testMomentArms.cpp` line 347 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3897#-O5sn4qSEZfsIrL1FNT1:-O5sn4qSEZfsIrL1FNT2:b-iw11yv) ([raw file](https://github.com/opensim-org/opensim-core/blob/e9222761045b218817839b141b1428546db72098/OpenSim/Simulation/Test/testMomentArms.cpp#L347)):*
> ```cpp
>         testMomentArmDefinitionForModel("BothLegs22.osim", "r_knee_angle", "VASINT",
>             SimTK::Vec2(-2*SimTK::Pi/3, SimTK::Pi/18), 0.0,
>             "VASINT of BothLegs with no mass: FAILED");
> ```

Similar to removing the `cout` statements, we should remove the need for an error message from `testMomentArmDefinitionForModel` since the Catch framework will tell us if the subtest passed or failed.
___
*[`OpenSim/Simulation/Test/testStatesTrajectory.cpp` line 266 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3897#-O5snZWd9KEESM15U5bn:-O5snZWd9KEESM15U5bo:b-vjh16o) ([raw file](https://github.com/opensim-org/opensim-core/blob/e9222761045b218817839b141b1428546db72098/OpenSim/Simulation/Test/testStatesTrajectory.cpp#L266)):*
> ```cpp
> 
> TEST_CASE("testPopulateTrajectoryAndStatesTrajectoryReporter") {
>     LoadOpenSimLibrary("osimActuators");
> ```

If every test needs this library, we should just include it above rather than loading it for every test.


<!-- Sent from Reviewable.io -->

2024-09-13 22:07 UTC, nickbianco commented
@AllisonJohn let me know if you wanted to finish up this PR or if you want me to take it over.

2025-02-14 18:21 UTC, closed without merging