Lowpass Filter Improved Uniform Sampling Check
opensim-org/opensim-core pull request #3978
Opened 2024-11-27 17:02 UTC by alexbeattie42

Fixes issue #3968

### Brief summary of changes

Implement an `isUniform` method to check if the vector is uniformly sampled. The implementation loosely follows the idea of the Matlab [isUniform function](https://se.mathworks.com/help/matlab/ref/isuniform.html). The implementation calculates the tolerance in this way:

>isuniform verifies that the spacing between consecutive elements in numeric vector v does not deviate from the mean spacing by more than 4*eps(max(abs(v))), provided that the mean spacing is greater than that tolerance. 

This may also fix [this issue](https://github.com/opensim-org/opensim-core/issues/3919) but I have not tested that myself yet.

### Testing I've completed

Tested locally with [this example](https://github.com/gateway240/opensim-core-examples/tree/main/LowPassFilterTime). Will add unit tests soon.

### Looking for feedback on...

@nickbianco and @aymanhab 
- do you have feedback on this method for checking the uniform sampling
- where is the correct place for the uniform sampling check function to live. Maybe `Signal`?

### CHANGELOG.md (choose one)

- Will update when PR is ready

2025-01-18 13:51 UTC, alexbeattie42 reviewed
@nickbianco could you take another look?

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-:-OGtfXg8CMMiC0E2aKqe:b-eup00k)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/TableUtilities.cpp` line 126 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OCixhTf0Fs0I0Zrt3Z1:-OGtfUreBxJEmNHukhbL:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c8c7bab5f1a2302fe05b0c97992c24b6571c1bbf/OpenSim/Common/TableUtilities.cpp#L126)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think this would be a nice addition to [CommonUtilities](https://github.com/opensim-org/opensim-core/blob/c82ded4c62260193707fa1199d35dd70340c8060/OpenSim/Common/CommonUtilities.h), as it might be useful for other table manipulation tools in OpenSim.
</blockquote></details>

Done.
___
*[`OpenSim/Common/TableUtilities.cpp` line 189 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OCiyYpe5gant9b6QpL3:-OGtfVi51Mzk_plu0_1I:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c8c7bab5f1a2302fe05b0c97992c24b6571c1bbf/OpenSim/Common/TableUtilities.cpp#L189)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Could you add some documentation in the header file describing the conditions under which a table will be resampled?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-22 20:38 UTC, nickbianco requested changes
Thanks @alexbeattie42! Made a handful of minor request, but overall looks pretty good.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-:-OHEj5OwAQnpYOhU8P2x:bnsolz9)* status: all files reviewed, 7 unresolved discussions (waiting on @alexbeattie42)

___
*[`OpenSim/Common/CommonUtilities.h` line 149 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEhTQ0834lebXxSWZA:-OHEhTQ0834lebXxSWZB:bihj5wg) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/CommonUtilities.h#L149)):*
> ```objc
>  * uniform, this value will be the mean step size. If the input is a one element
>  * vector, the step size will be NaN since a valid step size cannot be
>  * calculated with only 1 element.
> ```

I think you could reduce the indentation level for both of these list items.
___
*[`OpenSim/Common/CommonUtilities.h` line 153 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEgx1c8xGeReGtFSXQ:-OHEgx1dEHjKuhpcPp2n:b-vzqsvj) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/CommonUtilities.h#L153)):*
> ```objc
>  * @note The function uses a tolerance based on the maximum absolute value of
>  * the first and last elements in the vector, scaled by machine epsilon. If the
>  * vector is empty or contains only one element, the behavior is undefined.
> ```

Use left-aligned indent for the text in this note (like the note below.
___
*[`OpenSim/Common/CommonUtilities.h` line 156 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEgpNVCdX8ydEObCjh:-OHEgpNVCdX8ydEObCji:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/CommonUtilities.h#L156)):*
> ```objc
>  * @note The function implementation draws inspiration from Matlab's `isuniform`.
>  *       See https://mathworks.com/help/matlab/ref/isuniform.html for more details.
>  * details
> ```


___
*[`OpenSim/Common/CommonUtilities.cpp` line 77 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEhdxAE9shgqZw9gWL:-OHEhdxAE9shgqZw9gWM:bb7lc5i) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/CommonUtilities.cpp#L77)):*
> ```cpp
>     const double step_size = (end - start) / static_cast<double>((length - 1));
>     for (int i = 0; i < length; ++i) {
>         v[i] = std::fma(i, step_size,start);
> ```

nit:



_Suggestion:_
```cpp
        v[i] = std::fma(i, step_size, start);
```
___
*[`OpenSim/Common/TableUtilities.h` line 97 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEi1r_1X-CkIEujRz9:-OHEi1r_1X-CkIEujRzA:bb7lc5i) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/TableUtilities.h#L97)):*
> ```objc
>      * rows is less than 4, or if the time intervals are not suitable for
>      * resampling.
>      *
> ```

nit:
___
*[`OpenSim/Common/Test/testCommonUtilities.cpp` line 135 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEicBw3eCMfAtpyC-P:-OHEicBw3eCMfAtpyC-Q:bqpt8xx) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/Test/testCommonUtilities.cpp#L135)):*
> ```cpp
>         // Verify that the second value returned is the minimum step size found
>         REQUIRE_THAT(result.second, Catch::Matchers::WithinAbs(0.03, tol));
>     }
> ```

Not critical, but if you wanted to avoid "part 2" in the section headers here and below, you could scope the subtests like this (formatting isn't great here, but you get the idea):

```
SECTION("Non-uniform spacing") {
        {
            std::vector<double> vec3 = {1.0, 2.0, 3.5, 4.0};
            auto result = isUniform(vec3);
            REQUIRE(result.first == false);
            REQUIRE_THAT(result.second, Catch::Matchers::WithinAbs(0.5, tol));
      
            std::vector<double> vec4 = {1.0, 2.0, 3.0, 4.0, 5.1};
            result = isUniform(vec4);
            REQUIRE(result.first == false);
            REQUIRE_THAT(result.second, Catch::Matchers::WithinAbs(1.0, tol));
        }

        {
            std::vector<double> vec2 = {0.0, 0.5, 0.11, 0.16, 0.19, 0.24};
            auto result = isUniform(vec2);
      
            REQUIRE(result.first == false); // Should not be uniformly spaced
            // Verify that the second value returned is the minimum step size found
            REQUIRE_THAT(result.second, Catch::Matchers::WithinAbs(0.03, tol));
        }
    }
```
___
*[`OpenSim/Common/Test/testCommonUtilities.cpp` line 263 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEiIj599AKv7ZjqiYR:-OHEiIj599AKv7ZjqiYS:btkpg1w) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/Test/testCommonUtilities.cpp#L263)):*
> ```cpp
>     REQUIRE_THAT(result_simtk.second, Catch::Matchers::WithinAbs(rate, tol));
>     
> }
> ```

nit: Add EOL line break.


<!-- Sent from Reviewable.io -->

2025-01-23 19:36 UTC, alexbeattie42 reviewed
@nickbianco Thanks for the feedback! I have fixed the comments.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-:-OHJdJfUCf6OBUctXVNo:br89lel)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/CommonUtilities.h` line 149 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEhTQ0834lebXxSWZA:-OHJdCH1-yjfXB7wxmid:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/CommonUtilities.h#L149)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think you could reduce the indentation level for both of these list items.
</blockquote></details>

Done.
___
*[`OpenSim/Common/CommonUtilities.h` line 153 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEgx1c8xGeReGtFSXQ:-OHJdCdj3BlZr1u_GDHT:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/CommonUtilities.h#L153)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Use left-aligned indent for the text in this note (like the note below.
</blockquote></details>

Done.
___
*[`OpenSim/Common/Test/testCommonUtilities.cpp` line 135 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEicBw3eCMfAtpyC-P:-OHJdEunA73Epylh1CwA:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/Test/testCommonUtilities.cpp#L135)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Not critical, but if you wanted to avoid "part 2" in the section headers here and below, you could scope the subtests like this (formatting isn't great here, but you get the idea):

```
SECTION("Non-uniform spacing") {
        {
            std::vector<double> vec3 = {1.0, 2.0, 3.5, 4.0};
            auto result = isUniform(vec3);
            REQUIRE(result.first == false);
            REQUIRE_THAT(result.second, Catch::Matchers::WithinAbs(0.5, tol));
      
            std::vector<double> vec4 = {1.0, 2.0, 3.0, 4.0, 5.1};
            result = isUniform(vec4);
            REQUIRE(result.first == false);
            REQUIRE_THAT(result.second, Catch::Matchers::WithinAbs(1.0, tol));
        }

        {
            std::vector<double> vec2 = {0.0, 0.5, 0.11, 0.16, 0.19, 0.24};
            auto result = isUniform(vec2);
      
            REQUIRE(result.first == false); // Should not be uniformly spaced
            // Verify that the second value returned is the minimum step size found
            REQUIRE_THAT(result.second, Catch::Matchers::WithinAbs(0.03, tol));
        }
    }
```
</blockquote></details>

Done.
___
*[`OpenSim/Common/CommonUtilities.h` line 156 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3978#-OHEgpNVCdX8ydEObCjh:-OHJdD91EkK2pFTTr9xN:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c72e578d601943ef9ba8cee33dc034972296f4d0/OpenSim/Common/CommonUtilities.h#L156)):*
> ```objc
>  * @note The function implementation draws inspiration from Matlab's `isuniform`.
>  *       See https://mathworks.com/help/matlab/ref/isuniform.html for more details.
>  * details
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-24 14:28 UTC, alexbeattie42 commented
@nickbianco Is this ready to be merged now?

2025-01-25 00:08 UTC, merged