initialize api_distro to false on windows as layout doesn't change
opensim-org/opensim-core pull request #3983
Opened 2024-12-14 20:40 UTC by aymanhab

Fixes issue #3982
### Brief summary of changes
initialize variable so available in all scopes

### Testing I've completed
installed into matlab locally

### Looking for feedback on...

### CHANGELOG.md (choose one)

- no need to update because not user facing yet

2024-12-17 17:57 UTC, nickbianco requested changes
One minor request, for clarity.

2024-12-17 17:57 UTC, nickbianco commented on Bindings/Java/Matlab/configureOpenSim.m.in
> +    api_distro = false;
Minor, but it would be clearer to initialize `api_distro` in `uiGetOpenSimFolder` and return it as an additional output.

2024-12-17 21:52 UTC, aymanhab commented
ok, done @nickbianco feel free to review and/or test further.

2024-12-18 15:48 UTC, nickbianco approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3983#-:-OEPSAF0Db6a-A5VpAv0:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)



<!-- Sent from Reviewable.io -->

2024-12-18 15:48 UTC, merged

2024-12-18 18:26 UTC, aymanhab commented
Thanks @nickbianco